### ISSUE TITLE
Task 3.3: Create a new default color palette for the Fast Tile Plot

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#10]

**Comment by joellenb** [comment]
Everywhere the color palette of 8 colors for the NewtonMap is being created, changed to use a new function call createPavePalette() that specifically creates the old PAVE colors using the RGB values from the PAVE User's Guide.

![newdefaultpavecolorpalette](https://cloud.githubusercontent.com/assets/10145737/8016580/3db6b542-0bb3-11e5-8904-634cf7631931.PNG)

**Comment by joellenb** [comment]
That was done earlier. I apologize if I missed marking it as complete on our tracking spreadsheet.

Jo Ellen

________________________________

**Comment by lizadams** [comment]
Hi Jo Ellen,
I was just going into the closed task list and adding your name as the person responsible, as you had done the work.
