### ISSUE TITLE
wrf projection incorrectly specified

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#106]
Noticed that we are still seeing a shift on the West Coast of a grid cell or two for the LU_INDEX and the coastline.

used verdi_script_wrf_d02.launch to load a WRF output file from the 12km grid of the 3SAQS project using the debuger.  

Put a break in WRFConvention.java at line 269 at the break command under case1 in this section of the code:

```
  double lat1 = findAttributeDouble(ds, "TRUELAT1");
  double lat2 = findAttributeDouble(ds, "TRUELAT2");
  double centralLat = findAttributeDouble(ds, "CEN_LAT");  // center of grid
  double centralLon = findAttributeDouble(ds, "CEN_LON");  // center of grid

  double standardLon = findAttributeDouble(ds, "STAND_LON"); // true longitude
  double standardLat = findAttributeDouble(ds, "MOAD_CEN_LAT");

  ProjectionImpl proj = null;
  switch (projType) {
    case 0: // for diagnostic runs with no georeferencing
      proj = new FlatEarth();
      projCT = new ProjectionCT("flat_earth", "FGDC", proj);
```

 //          Logger.debug(" using LC "+proj.paramsToString());
          break;
        case 1:
          proj = new LambertConformal(standardLat, standardLon, lat1, lat2);
          projCT = new ProjectionCT("Lambert", "FGDC", proj);
//          Logger.debug(" using LC "+proj.paramsToString());
          break;

The values for the proj string are queried by hovering over proj within eclipse and the result is displayed here:
LambertConformal{earth_radius=6371.229, lat0=39.999996185302734, lon0=-97.0, par1=33.0, par2=45.0, falseEasting=0.0, falseNorthing=0.0}

The dataset metadata can be inspected using the command:
ncdump -h /Users/lizadams/local_git_repository/vERDI/verdi_dist/distfiles/data/test/model/3SAQS/WRF/wrfout_d02_2011-01-01_00_LU_INDEX

So these parameters are consistent between the metadata data and the Projection String.
:TRUELAT1 = 33.f   lat1, par1
:TRUELAT2 = 45.f ; lat, par2
:MOAD_CEN_LAT = 40.f ;  (standardLat, lat0)
:STAND_LON = -97.f ;        (standardLon, lon0)

The EARTH RADIUS and False Easting and False Northing are not specified in the dataset Metadata, but the EPA has said that Earth Radius for WRF should be defined as 6370.000
private static final double earthRadius = 6370.000; // km

The documentation for the method LambertConformal is available online here:
https://www.unidata.ucar.edu/software/thredds/v4.6/netcdf-java/javadoc/ucar/unidata/geoloc/projection/LambertConformal.html#LambertConformal-double-double-double-double-

I am going to try and modify the WRFConvention.java so that the earth radius is explicitly defined as 6370.000 as shown below:
  private static final double false_easting = 0; 
  private static final double false_northing = 0;
  private static final double earthRadius = 6370.000;
        case 1:
          proj = new LambertConformal(standardLat, standardLon, lat1, lat2, false_easting, false_northing,earthRadius);
          projCT = new ProjectionCT("Lambert", "FGDC", proj);
          System.out.println("Projection String in WRFConvention.java " + proj);
//          Logger.debug(" using LC "+proj.paramsToString());
          break;

I can't seem to do this to the WRFConvention.java under verdi_data_loaders, so I will try using the Developer Instructions to compile the NetCDF-java library.

**Comment by joellenb** [comment]
Sounds reasonable. I believe that we have a copy of the files that you make VERDI-specific in the verdi_data_loaders project for reference purposes only, but VERDI uses the copy that is within the library. So, follow your developer instructions and put a copy of the changed files under verdi_data_loaders when they work as planned.

I like explicitly setting all the parameters for the projection. If we don’t, then we are relying on the defaults that the library uses. Not only is the radius of the earth wrong, it may change between versions of the library. If is better for us to have control.

Jo Ellen

**Comment by lizadams** [comment]
I was able to edit the WRFConvention.java and rebuild the netCDF.java library.
Now it has a standard out message as follows.
The projection in WRFConvention.java is LambertConformal{earth_radius=6370.0, lat0=39.999996185302734, lon0=-97.0, par1=33.0, par2=45.0, falseEasting=0.0, falseNorthing=0.0}
This didn't solve the apparent grid shift
![wrf_lu_index radius_6370](https://cloud.githubusercontent.com/assets/1183863/19403168/3b89e642-9233-11e6-81dc-026905c27be8.png)

**Comment by joellenb** [comment]
Is there possibly a difference between how the values are being read (start at 1 or at 0)?

Jo Ellen

**Comment by lizadams** [comment]
Here is a discussion about there being two types of grids in WRF.
http://imdongchen.blogspot.com/2012/06/dip-into-ncl.html
"It comes out that there are two grids in WRF, the staggered grid and the mass grid. Value in mass grid is refers to value in the center of the grid while value in staggered grid means value in the boundary of the grid. So the dimension size of staggered grids is always greater than mass grids by 1. To solve the inconsistency, we average the value to mass grid points." - he shows a calculation in the link above.

**Comment by lizadams** [comment]
LU_INDEX isn't the best variable to use for these tests along the coastline LANDMASK is better.
Plot of D01 domain - looks ok
![verdi_1 6_shapefile_mpas_mpas wrfout_d01 landmask](https://cloud.githubusercontent.com/assets/1183863/19418448/06005834-9392-11e6-9c80-9d4888dee1eb.png)

**Comment by lizadams** [comment]
Plot of D02 domain, start to see a shift?
![verdi_1 6_shapefile_mpas_mpas wrfout_d02 landmask](https://cloud.githubusercontent.com/assets/1183863/19418513/12eb0b1a-9393-11e6-8363-b11a08c33995.png)

**Comment by lizadams** [comment]
Plot of D03 domain - see a difference between the HUC map and where the lake identified in the LANDMASK variable
![verdi_1 6_shapefile_mpas_mpas wrfout_d03 landmask](https://cloud.githubusercontent.com/assets/1183863/19418523/37e2c246-9393-11e6-9d44-0008955a2b81.png)

**Comment by lizadams** [comment]
Need to create a plot using Python-PseudoNetCDF and NCL and the HUC file and see if this is an issue with VERDI or an issue related to the HUC file?
Created WRF_Python_Plot.ipynb, but I don't have the definitions correct for that map.
The WRF files don't define the (XORIG, YORIG) or (Lower left corner X, Lower Left Corner Y) and I don't yet know how to calculate it from the Projection Origin, which in a CMAQ file is (PGAM, YCENT), but in the WRFOUT file is (STAND_LON,MOAD_CEN_LAT)
:MOAD_CEN_LAT = 40.f ;
:STAND_LON = -97.f ;

![python wrf_d02](https://cloud.githubusercontent.com/assets/1183863/19419099/5770b9f0-939e-11e6-8e03-934dc0e379b7.png)

**Comment by systemsgo** [comment]
Fixed
