### ISSUE TITLE
mpas - earth radius: sphere_radius = 6371229

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#117]
Used ncdump to view header  information in the rho_only.nc file.
Noticed that the MPAS model uses a different assumption for the earth's radius.
netcdf rho_only {
dimensions:
    nCells = 163842 ;
    nVertices = 327680 ;
    Time = UNLIMITED ; // (24 currently)
    nVertLevels = 50 ;
    maxEdges = 10 ;
    StrLen = 64 ;
variables:
    int indexToCellID(nCells) ;
    int indexToVertexID(nVertices) ;
    float latCell(nCells) ;
    float latVertex(nVertices) ;
    float lonCell(nCells) ;
    float lonVertex(nVertices) ;
    int nEdgesOnCell(nCells) ;
    float rho(Time, nCells, nVertLevels) ;
    int verticesOnCell(nCells, maxEdges) ;
    char xtime(Time, StrLen) ;

// global attributes:
        :model_name = "mpas" ;
        :core_name = "atmosphere" ;
        :source = "MPAS" ;
        :Conventions = "MPAS" ;
        :git_version = "unknown" ;
        :on_a_sphere = "YES" ;
        **:sphere_radius = 6371229. ;**
        :history = "mpirun -n 64 ./atmosphere_model" ;
.....
rho =
  1.219283, 1.217712, 1.215743, 1.213369, 1.210515, 1.206865, 1.202096, 
    1.196925, 1.191263, 1.180017, 1.170248, 1.158813, 1.145565, 1.129848,

**Comment by systemsgo** [comment]
That's correct - earth radius is usually one of the factors in the projection used to represent the data, and must be accounted for when displaying data coming from differing projections.
