### ISSUE TITLE
mpas - xland variable shows data appears to be lining up with map on tile plot in VERDI

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#118]
dataset: history.2013-07-10.1step.nc
variable: hpbl
Zoomed in on the Baja California coastline to see if the data appears to line up with the coastline in the US Map.  It appears shifted to me, although it isn't definitive.
![verdi_1 6_shapefile_mpas_mpas history 2013-07-10 1step hpbl tile windvectors](https://cloud.githubusercontent.com/assets/1183863/19418112/62e8dda2-938b-11e6-8464-42c2973f0c38.png)

**Comment by lizadams** [comment]
Note - the Time Series Plot does appear to work.
![verdi_1 6_shapefile_mpas_mpas t2m_only timeseries](https://cloud.githubusercontent.com/assets/1183863/19417187/6f65ac20-9374-11e6-9b6d-d8c4024ade2c.png)

**Comment by lizadams** [comment]
XLAND does line up with the background map - so this variable may be what we need to verify that data and maps are lining up!
![verdi_1 6_shapefile_mpas_mpas history 2013-07-10 1step hpbl tile xland](https://cloud.githubusercontent.com/assets/1183863/19418157/6368ef64-938c-11e6-8ad1-f3fad68bc10f.png)

**Comment by lizadams** [comment]
![verdi_1 6_shapefile_mpas_mpas history 2013-07-10 1step tile fulldomain xland](https://cloud.githubusercontent.com/assets/1183863/19418214/8464c584-938d-11e6-8d6b-fef498237504.png)

**Comment by lizadams** [comment]
If you set the max height to 1000 then Terrain appears to also show that the data lines up with the map for Baja California.
![verdi_1 6_shapefile_mpas_mpas history 2013-07-10 1step tile bajacal xland](https://cloud.githubusercontent.com/assets/1183863/19418239/0f31b0be-938e-11e6-894c-65dc4f7bbfba.png)

**Comment by systemsgo** [comment]
That's correct - xland is defined as being gray for land, and red for water.  Generally that's the best variable to use for comparing against map boundaries.
