### ISSUE TITLE
Task 3.6: Eliminate these bugs and add the ability to save contour plot animations back into VERDI

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#12]

**Comment by joellenb** [comment]
The bugs are issues with how the 3D contour plot is redrawn as the user interacts with the plot by grabbing and moving the mouse on the screen to move the plot to different views. These mouse motions can "lose" part of the plot or axes outside the plot's view window; resizing the window does not bring the missing parts back into view. Labels, such as the z-axis title, can also be flipped backwards.

**Comment by joellenb** [comment]
VERDI 1.5.0 was the first VERDI release under Java 7 and newer versions of many libraries. There appeared to be an incompatibility between these libraries, Java 7, and the libraries that had been used to save 3D contour plot animations. Determine which libraries were used for this functionality and develop a consistent set so this feature can be added back into a future release of VERDI.

**Comment by lizadams** [comment]
I can't get the contour 3D plot to work on linux using VERDI_2.0_beta_linux64_20190623.tar.gz
