### ISSUE TITLE
configure tile plot does not keep user entered number format

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#123]
VERDI resets the format value to a default instead of keeping the user entered format.
This happens for 6.3F user entered string, but it doesn't happen for 6.3E.
VERDI may be rejecting the F format string when it tries to save it?
Check in anl.verdi.plot.color in the class PalettePanel  line 815
    private ColorMap resetNumberFormat(ColorMap map, String format) throws Exception {
The default value that VERDI is currently using is incorrect. %-2.3f it should be 5.3E
![configure_plot](https://cloud.githubusercontent.com/assets/1183863/19445713/80042904-9463-11e6-99ab-4366b8696f81.png)

**Comment by joellenb** [comment]
Using Windows 64-bit compiled VERDI from 10/19/2016. Started VERDI from run.bat with logger set to DEBUG. 
Selected dataset CCTM46_P16.baseO2a.36k.O3MAX
Selected variable O3 (ppmV)[1]
Selected Tile Plot.
Drew tile plot fine including legend format 5.3E.
Selected Configure/Configure Plot.
Number format defaults to %5.3E.
![numberformattileplot_10302016](https://cloud.githubusercontent.com/assets/10145737/19840199/77f586d6-9ec7-11e6-89c2-0afd88a161e8.PNG)

Some format strings are being changed by VERDI, but it is trying to do a correction. 
6.6E is changed to 8.6E (good correction). 
8.6F looks OK but reset to -2.6f. 
0.4f looks OK but changed to -2.4f. 
0.4F looks OK but changed to -2.4f.
-2.5f stays -2.5f
-2.5e is changed to 7.5E (good correction)

Why does it keep putting that leading % into the number format? I thought that I got rid of that quirk months ago.

**Comment by systemsgo** [comment]
This now handles the number format directly as entered, with no internal conversion to NumberFormat.
