### ISSUE TITLE
CAMX d03 grid - 4km comparison between Python and VERDI plots with County Background Map

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#125]
Notice the difference of using a Discrete Scale in VERDI
Either the background map in VERDI is shifted South or the Data is shifted North?
![verdi_1 6_shapefile_mpas_camx_grd03_co_county_map](https://cloud.githubusercontent.com/assets/1183863/19461518/31cc8006-94b3-11e6-92c0-01e2e20ff4f9.png)

Continuous scale in Python
![co_lay1_camx_converted_to_cmaq_pypnc_d03_county_map](https://cloud.githubusercontent.com/assets/1183863/19461524/38614fe6-94b3-11e6-8bfe-c79ccc86731d.png)

**Comment by systemsgo** [comment]
The background map was shifted, but should be displaying correctly now.
