### ISSUE TITLE
use unidata ToolsUI to look at gridded wrf 4km output file - correctly locate LANDMASK=0 over the Great Salt Lake

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#126]
http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/tutorial/GridDatatype.html
Watched the following video, and was able to view the LANDMASK variable from the wrfout_d03_2011-01-01_00.nc

https://www.youtube.com/watch?v=GTFvdhlHivM

It shows the great Salt Lake in Utah on the background map when I selected the US Detailed Map and it correctly surrounds the area where LANDMASK=0
![toolsui grd03 landmask detailedusmap](https://cloud.githubusercontent.com/assets/1183863/19462577/d693b2b4-94bb-11e6-9443-9bd5e7435d91.png)
 where the LANDMASK variable = 0

**Comment by lizadams** [comment]
Zoomed in using VERDI to show the number of grid cells that differ between the location of the Great Salt Lake as shown in the shapefile and as defined by LANDMASK=0.

![toolsui grd03 landmask detailedusmap](https://cloud.githubusercontent.com/assets/1183863/19462764/02a337de-94bd-11e6-9980-447646a34ac8.png)

**Comment by dschwede** [comment]
What GIS layer is the source of outline of the Great Salt Lake?

**Comment by lizadams** [comment]
Using either World or HUCs provides an outline of the Great Salt Lake.  I am not sure what I used at the time I created that plot.  I think I tried uploading the exact shapefile that ToolsUI was using, to make sure that I was comparing apples to apples.

**Comment by lizadams** [comment]
I've added a wrf file that is similar to the one that I used in the image above to the google drive, as I am not sure if a similar file is available with the VERDI package.  It is a 4.5 GB size file: [wrfout_d03_2011-09-11_12:00:00](https://drive.google.com/drive/u/0/folders/1bvPnly6V5rcb943rzwGJIWL7G741m1e9)

**Comment by dschwede** [comment]
Thanks for the additional information.  This one looks like it is fixed.
