### ISSUE TITLE
tips on reading wrf file using gdal

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#129]
Quote from the following link:
"The metadata given at the main file doesn't set the geotransform properly (or, at least, I'm not able to get it), since it sets only the center point coordinates, and the deltax and deltay. But this deltas are not referenced to the same point, so getting the real geotransform is not easy.

Fortunately, the files come with the fields XLONG and XLAT, that contain the longitude and latitude for each point in the matrix. So taking the corners is possible to get the geotransform, although the coordinates have to be reprojected before:
..."

http://geoexamples.blogspot.com/2013/09/reading-wrf-netcdf-files-with-gdal.html

**Comment by systemsgo** [comment]
WRF files should display properly now.
