### ISSUE TITLE
Task 3.7: Fix a persistent bug in the VERDI code where if a title is turned off (made blank), and a plot configuration is changed in any way, the title reappears.

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#13]

**Comment by joellenb** [comment]
Blank title is now maintained.

**Comment by lizadams** [comment]
Note: I tried this using the verdi_config_v1 branch, and the title and subtitle do not seem to be turned off when I uncheck the check box. - we need to revisit this, as something may have changed when Qun implemented the Chart Theme.
