### ISSUE TITLE
mercator geo_em.d01.nc - LANDMASK doesn't match map for either toolsUI or VERDI

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#133]
![toolsuivsverdi geo_em d01 landmask](https://cloud.githubusercontent.com/assets/1183863/19542912/ba90389a-9640-11e6-9e52-3b7c421942b6.png)
![toolsui_metadata_geo_em d01](https://cloud.githubusercontent.com/assets/1183863/19542953/083583a2-9641-11e6-905b-243f3351bbbd.png)

**Comment by lizadams** [comment]
uiTools, 4corners: 36.99N, 109.0W
VERDI, 4corners: 46.169N, 112.851W

**Comment by systemsgo** [comment]
This should be working now
