### ISSUE TITLE
mercator GRIDCRO2D_mercator.nc LWMASK data doesn't match background map for VERDI

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#136]
![toolsuivsverdi_gridcro2d_mercator lwmask](https://cloud.githubusercontent.com/assets/1183863/19543388/105cdb76-9645-11e6-9ba3-b4b3857d765f.png)
![screen shot 2016-10-19 at 10 31 13 pm](https://cloud.githubusercontent.com/assets/1183863/19544275/cbf471e0-964b-11e6-935e-d0d4c55e9028.png)

**Comment by systemsgo** [comment]
Fixed
