### ISSUE TITLE
world_NOX_latlon.nc

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#137]
UITools is able to successfully plot the world background map
VERDI has difficulties with displaying the world map for this data
![toolsuivsverdi_world_nox_latlon](https://cloud.githubusercontent.com/assets/1183863/19543595/a9fcaeae-9646-11e6-86ca-bdcd90d97bc5.png)
![screen shot 2016-10-19 at 10 40 19 pm](https://cloud.githubusercontent.com/assets/1183863/19544459/13d302e6-964d-11e6-9e6e-5e87bb293303.png)

**Comment by jherwehe** [comment]
Tested using VERDI_2.0_beta.20190610 on both Linux and Windows 10; NOX from world_NOX_latlon.ncf plots correctly with world coastlines (though missing the Antarctic coastline, for now).
