### ISSUE TITLE
wrf_usgs_tx1km LANDMASK doesn't match map for VERDI - it is better for UITools

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#138]
![screen shot 2016-10-19 at 9 57 49 pm](https://cloud.githubusercontent.com/assets/1183863/19543684/4b77e1a4-9647-11e6-8c44-35587d96a1ba.png)
![screen shot 2016-10-19 at 10 28 03 pm](https://cloud.githubusercontent.com/assets/1183863/19544219/57fb44d0-964b-11e6-9c5a-e82fd1a2a2d8.png)

**Comment by lizadams** [comment]
This might help:
http://r-sig-geo.2731867.n2.nabble.com/Set-up-raster-data-in-WRF-Mercator-projection-td7590252.html

**Comment by lizadams** [comment]
Barron recommends using ncks to edit MOAD_CEN_LAT to 40 as a test to determine if VERDI is reading that or not. We would expect it to shift south.
ToolsUI is either not sensitive to that parameter or knows what to do with it.

2) calculate lat/lons within VERDI

**Comment by systemsgo** [comment]
This was due to a problem in shapefile rendering, and is fixed.
