### ISSUE TITLE
MPAS - VERDI and PyNGL: XLAND lines up with background map when zooming to Baja California

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#140]
![screen shot 2016-10-19 at 11 21 04 pm](https://cloud.githubusercontent.com/assets/1183863/19545265/dc3b5e2c-9652-11e6-893a-3205e34b532f.png)

**Comment by lizadams** [comment]
PyNGL - has different color scale but should be zoomed in to the same area
![mpas3 000002](https://cloud.githubusercontent.com/assets/1183863/19545690/3fc3e81c-9656-11e6-8bf3-8225ec64d928.png)

**Comment by systemsgo** [comment]
I don't think this is a bug.  The map used by VERDI is a different one than the one used by PyNGL but it seems to line up pretty well.  I strongly suspect if you were to use PyNGL's map file in VERDI, you'd see the same results.
