### ISSUE TITLE
lambert conformal - GRIDCRO2D_CMAS-Training doesn't match (4corners different ToolsUI and VERDI)

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#141]
![screen shot 2016-10-19 at 11 59 38 pm](https://cloud.githubusercontent.com/assets/1183863/19545897/559c3156-9658-11e6-9b69-345cb169d1ed.png)
![screen shot 2016-10-20 at 12 01 44 am](https://cloud.githubusercontent.com/assets/1183863/19545914/8cfe67f4-9658-11e6-8dfe-07cd89741cd3.png)

**Comment by lizadams** [comment]
For GDTYP Definitions in IOAPI Convention see:
https://www.cmascenter.org/ioapi/documentation/all_versions/html/GRIDS.html

**Comment by lizadams** [comment]
Copy of projection information from logfile written out from NetcdfBoxer.java
![verdi_log_crs](https://cloud.githubusercontent.com/assets/1183863/19569528/18a93d0e-96c4-11e6-851b-372b980238eb.png)

**Comment by lizadams** [comment]
Also created a plot in python using Barron Henderson's long method of plotting MCIP
see
/Users/lizadams/CMAQandPython/RAQMSandPython/mcip_landmask.ipynb
![mcip_landmask_python](https://cloud.githubusercontent.com/assets/1183863/20501643/b68d4aa8-b008-11e6-919d-db091b87e384.png)

**Comment by systemsgo** [comment]
The GIS layers were being drawn incorrectly.  Here's an updated version that seems to be closer to the MCIP method.  Please take a look and close this issue if it seems okay.

![lambertupdated](https://user-images.githubusercontent.com/1047732/32419056-33253250-c242-11e7-9999-b5a313b5d4db.png)

**Comment by systemsgo** [comment]
Fixed
