### ISSUE TITLE
specify layer in batch script for JFreeChart Plot such as timeseries plot

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#144]
In the TimeSeriesPlotTask.java file, plot contains a value for layer=0.  I am not sure how to change this, so that we can have the user set the plot layer value for a timeseries plot.

if (dataFrame != null) {
				PlotFactory factory = new PlotFactory();
				PlotPanel panel = factory.getPlot(type, verdiApp.getProject().getSelectedFormula().getFormula(),
						dataFrame, config);
				plot = panel.getPlot();

**Comment by lizadams** [comment]
I created a command line script that specifies to plot a timeseries plot for Temperature of Layer 15.
It works, and now I will run this thru the debugger to learn how to do this for the batch script option.
![Uploading TA.timeseries.layer.gif…]()

**Comment by lizadams** [comment]
The line plot can be created, but the min and max values of Temperature (K) are not set to be the min and max of that layer and timestep, so the plot is not very useful.
Is it possible to create an option for the batch script to use the min/max values?
 Or a way to allow the user to specify modify the min and max value of the variable on the Y axis.
<img width="796" alt="Line_Plot_Temperature_layer_15" src="https://user-images.githubusercontent.com/1183863/145287280-112e3d06-00bd-44fd-9835-c323097a458a.png">
 way to modify the min and max value of the variable on the Y axis.

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1.3_linux64_20220210.tar.gz on Atmos, found that this issue has resolved.**
Ran /data/scripts/verdi_script_timeseries_layer.csh with different "layer" and found that the Y-axis range for temperature did change according to the min and max of the layer, shown as below:
![issue_144_testing_20220210_1](https://user-images.githubusercontent.com/73186639/156232398-6906d6de-a20d-4fc5-878e-88b5b123aa61.png)
![issue_144_testing_20220210_2](https://user-images.githubusercontent.com/73186639/156232452-e5ebcb0b-7b7c-45f0-ad0a-87cd2b4d6a63.png)
