### ISSUE TITLE
MPAS file recognition

### ISSUE THREAD

**Issue by cjcoats** [CEMPD/VERDI#150]
The file-spec for MPAS can be found at:
https://mpas-dev.github.io/files/documents/MPAS-MeshSpec.pdf
"model_name" is NOT one of the listed required attributes, but
MPASConvention.java seems to require it.  As the sole requirement!

What the ???

**Comment by systemsgo** [comment]
It accepts mpas files with model_name or Conventions set to mpas.  It now also accepts data files with the mesh_spec attribute set.  Please let me know if there are any valid MPAS files that aren't recognized or if you see any false positives.

**Comment by cjcoats** [comment]
systemsgo wrote:
> It accepts mpas files with model_name or Conventions set to mpas. It now
> also accepts data files with the mesh_spec attribute set. Please let me
> know if there are any valid MPAS files that aren't recognized or if you
> see any false positives.

It also has a bogus hard-coded list of vertical dimensions.  In 
particular, it does NOT support normal chemical-emissions files.

For an example of how it SHOULD have been done, see:

https://github.com/cjcoats/ioapi-3.2/blob/master/m3tools/mpasstat.f90
-- 

Carlie J. Coats, Jr., Ph.D.                I/O API Author/Maintainer
6502 Glen Forest Dr.                            home: (919) 493-7695
Chapel Hill, NC  27517                        carlie@jyarborough.com

**Comment by cjcoats** [comment]
systemsgo wrote:
> It accepts mpas files with model_name or Conventions set to mpas. It now
> also accepts data files with the mesh_spec attribute set. Please let me
> know if there are any valid MPAS files that aren't recognized or if you
> see any false positives.

VERDI does NOT even recognize variable "zgrid" from a normal
MPAS-met "history" file.  That failure to recognize it is
COMPLETELY  BOGUS.

-- 

Carlie J. Coats, Jr., Ph.D.                I/O API Author/Maintainer
6502 Glen Forest Dr.                            home: (919) 493-7695
Chapel Hill, NC  27517                        carlie@jyarborough.com

**Comment by systemsgo** [comment]
zgrid is used to retrieve the elevation that's displayed in the bottom corner when you move the mouse over the map.  Would it be helpful to plot it directly in the map?  That shouldn't be too hard to add.

And yes, we know about the lack of chemical emissions support.  That's one of the enhancements we'd like to add.

**Comment by cjcoats** [comment]
systemsgo wrote:
> zgrid is used to retrieve the elevation that's displayed in the bottom
> corner when you move the mouse over the map. Would it be helpful to plot
> it directly in the map? That shouldn't be too hard to add.
>
> And yes, we know about the lack of chemical emissions support. That's one
> of the enhancements we'd like to add.

Yes -- I've been dealing with a problem of "what layer is that airplane
flying in", and trying to get that info by looking at values "by hand"
in a debugger is quite tedious.

And it's easy to imagine formulas that involve "zgrid" -- lapse-rates
for example.

Generally. VERDI should plot any variable with subscripting of the
forms
	A[nCells]
         B[Time][nCells]
         C[nCells][something]
         D[Time][nCells][something]

where if the "something" is unrecognized, it should still be treated
as a layer-dimension, using uniform layers for vertical cross sections
if necessary.  Arguably (for those doing advection research), you
should be able to replace the "nCells" dimension by "nEdges" or 
"nVertices" and plot  edge-based or vertex-based variables.

-- 

Carlie J. Coats, Jr., Ph.D.                I/O API Author/Maintainer
6502 Glen Forest Dr.                            home: (919) 493-7695
Chapel Hill, NC  27517                        carlie@jyarborough.com
