### ISSUE TITLE
Custom color ramp is lost - similar to #55

### ISSUE THREAD

**Issue by dschwede** [CEMPD/VERDI#154]
From Russ Bullock ...

I notice that “Configure Plot > Color Map” still does not conserve custom colors you have chosen when you use the “Rebuild” button to change the contour values.  It always reverts to the default color palette.  I can see why it would revert to the default palette when you change the number of tiles or the palette type, but if all you want to do is change the contour intervals, why throw away all color customization?  Maybe we need separate “Rebuild” buttons for “Color” and “Interval Start”.

**Comment by systemsgo** [comment]
This is fixed - rebuilding won't revert to the default colors anymore.
