### ISSUE TITLE
Relocate pop up space for interactive dialogue boxes

### ISSUE THREAD

**Issue by dschwede** [CEMPD/VERDI#158]
Have the “Configure Plot” and other interactive dialogue boxes pop up on the left side of the VERDI window over the “Datasets” section, instead of having them pop up covering up the plot that you’re trying to customize; it’s a nuisance to have to move the dialogue box out of the way every time.

**Comment by jherwehe** [comment]
Working with VERDI_2.0_beta.20190610:  The Configure -> Configure Plot and Controls -> Set Row and Column Ranges (and Controls -> Set Longitude and Latitude Ranges for MPAS plots) dialogue boxes pop up on the left side of the VERDI window, staying mostly out of the way during plot customization.  The load, save, and export dialogue are fine opening near the center of the VERDI window.
