### ISSUE TITLE
Task 6: Add the ability to export a graphic product from VERDI as a jpg file by right-clicking on the graphic

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#16]

**Comment by lizadams** [comment]
JFreeChart has option to do this using ChartTransferable:

22.10 ChartTransferable
22.10.1 Overview
A class representing a chart for transfer to the clipboard. You won't normally use this class directly, but rather configure the ChartPanel class to allow copying to the system clipboard (or call the ChartPanel's doCopy() method from your own code).
This class was first introduced in JFreeChart version 1.0.13.

**Comment by lizadams** [comment]
Once the chart is transferred to the clipboard we may be able to use the following code example to print it out.
http://forum.codecall.net/topic/58122-java-copy-image-from-clipboard/

**Comment by joellenb** [comment]
VERDI 1.6 Shapefiles branch has the ability to rt-click on FastTilePlot and save to a variety of graphic formats, including JPEG

**Comment by lizadams** [comment]
The  verdi_config_v1 branch only has the option to save as a png after you right click on a timeseries plot

**Comment by lizadams** [comment]
completed under the Shapefiles branch
