### ISSUE TITLE
Areal interpolation using cb_2014_us_state_500.shp

### ISSUE THREAD

**Issue by dschwede** [CEMPD/VERDI#165]
Use the areal interpolation plot with the shapefile of the US states that is used as a base map 

1) The average concentrations for the states was plotted for some states but others plot as white even though the value us within the range of the color scale.  In the figure below, the probe says Oregon has a value of 0.043 ppmV, so it should be yellow like Idaho and Washington should be green.
 2) When I selected just Washington, Oregon and Idaho and tried to do an areal interpolation plot, I got an error message “Problem with areal interpolation calculations.  Check if polygons intersect grid cells.  
3) when I try to select one of the problem states, it doesn't get outlined.

So, the map is probably the issue.  I am guessing that the border states are not closed polygons.  Plotting to states or counties is probably something people would want to do.  Hopefully, we can find a dataset that has complete polygons.

**Comment by lizadams** [comment]
[x] QA Testing using the CCTM_N1a_drydep_O3 file and the VERDI_2.0_beta/plugins/bootstrap/data/map_state/cb_2014_us_state_500k.shp
This calculation is taking awhile to create.  TargetCalculator calculated 56 areas in 301443ms
This deposition file isn't for the whole US, it is only for the central to eastern states, so I may not be reproducing the problem.
<img width="606" alt="screen shot 2018-12-13 at 6 16 02 pm" src="https://user-images.githubusercontent.com/1183863/49973281-78698980-ff02-11e8-8ac7-fec6221d3cd1.png">

[x] QA testing using the CCTM_DRYDEP_v53_mvapich2_2.3rc1_intel_17.2_intel_SE52BENCH_20110701.nc file and the VERDI_2.0_beta/plugins/bootstrap/data/map_state/cb_2014_us_state_500k.shp to see if I can reproduce the problem.  Then realized that the SE52BENCH only covers Southeast region...

[ ] Need to Find a file for DRYDEP that covers the whole US @dschwede - do you have a file that you can point me to?

**Comment by lizadams** [comment]
using 
with the following script.
```
#!/bin/csh -f
#script for testing command line options
echo 'running verdi_script_camx.csh'
foreach species ( O3 )
./verdi.sh \
         -f $cwd/data/model/CCTM_CONC_v53_intel18.0_2016_CONUS_test_20151222.nc \
         -titleString "CMAQ ${species} Layer 1" \
         -s "${species}[1]" \
         -g tile \
         -saveImage "jpg" $cwd/test.$species.png \
 #         -quit
 end
```
It takes awhile for VERDI to create the plot, but it let's the user know what it is doing, and how long it is taking by writing the following output to the console.
[lizadams@longleaf-login2 VERDI_2.0_beta]$ ./verdi_script_cmaq_12US.csh
running verdi_script_camx.csh
Calculated target 14 of 56: 00767982  size 75x48, 3600.0 in 4128ms, 0.872093023255814squares/ms
Calculated target 15 of 56: 01779792  size 61x29, 1769.0 in 810ms, 2.1839506172839505squares/ms
Calculated target 16 of 56: 01779794  size 13x25, 325.0 in 361ms, 0.9002770083102493squares/ms
Calculated target 17 of 56: 00897535  size 51x53, 2703.0 in 403ms, 6.707196029776675squares/ms
Calculated target 18 of 56: 01027616  size 65x29, 1885.0 in 5855ms, 0.3219470538001708squares/ms
Calculated target 19 of 56: 01102857  size 64x32, 2048.0 in 2210ms, 0.9266968325791856squares/ms
Calculated target 20 of 56: 01779798  size 43x29, 1247.0 in 495ms, 2.519191919191919squares/ms
Calculated target 21 of 56: 01779799  size 37x28, 1036.0 in 1422ms, 0.7285513361462729squares/ms
Calculated target 22 of 56: 01785534  size 51x34, 1734.0 in 1105ms, 1.5692307692307692squares/ms
Calculated target 23 of 56: 01455989  size 41x51, 2091.0 in 196ms, 10.668367346938776squares/ms
Calculated target 24 of 56: 01779802  size 12x23, 276.0 in 270ms, 1.0222222222222221squares/ms
Calculated target 25 of 56: 01779806  size 40x42, 1680.0 in 4300ms, 0.39069767441860465squares/ms
Calculated target 26 of 56: 01779807  size 51x42, 2142.0 in 132ms, 16.227272727272727squares/ms
Calculated target 28 of 56: 01155107  size 59x50, 2950.0 in 2884ms, 1.022884882108183squares/ms
Calculated target 29 of 56: 01779805  size 33x33, 1089.0 in 2199ms, 0.495225102319236squares/ms
Calculated target 30 of 56: 01779775  size 29x47, 1363.0 in 998ms, 1.3657314629258517squares/ms
Calculated target 31 of 56: 00068085  size 37x34, 1258.0 in 1113ms, 1.1302785265049415squares/ms
Calculated target 32 of 56: 01779778  size 59x100, 5900.0 in 14874ms, 0.3966653220384564squares/ms
Calculated target 33 of 56: 01779781  size 8x13, 104.0 in 20ms, 5.2squares/ms
Calculated target 34 of 56: 00294478  size 68x59, 4012.0 in 18383ms, 0.21824511777185443squares/ms
Calculated target 36 of 56: 01779785  size 44x29, 1276.0 in 1003ms, 1.272183449651047squares/ms
Calculated target 37 of 56: 01629543  size 44x36, 1584.0 in 6219ms, 0.25470332850940663squares/ms
Calculated target 38 of 56: 01779787  size 27x43, 1161.0 in 8926ms, 0.1300694600044813squares/ms
Calculated target 39 of 56: 00606926  size 25x14, 350.0 in 579ms, 0.6044905008635578squares/ms
Calculated target 40 of 56: 01779789  size 56x58, 3248.0 in 27322ms, 0.11887855940267916squares/ms
Calculated target 41 of 56: 01779791  size 50x42, 2100.0 in 1554ms, 1.3513513513513513squares/ms
Calculated target 42 of 56: 01779793  size 46x72, 3312.0 in 588ms, 5.63265306122449squares/ms
Calculated target 43 of 56: 01779795  size 10x22, 220.0 in 97ms, 2.268041237113402squares/ms
Calculated target 44 of 56: 01779796  size 55x42, 2310.0 in 3843ms, 0.6010928961748634squares/ms
Calculated target 45 of 56: 01779797  size 48x31, 1488.0 in 3554ms, 0.41868317388857623squares/ms
Calculated target 46 of 56: 01085497  size 31x35, 1085.0 in 880ms, 1.2329545454545454squares/ms
Calculated target 47 of 56: 01219835  size 6x8, 48.0 in 52ms, 0.9230769230769231squares/ms
Calculated target 48 of 56: 01325873  size 63x23, 1449.0 in 994ms, 1.4577464788732395squares/ms
Calculated target 49 of 56: 01779801  size 103x101, 10403.0 in 75914ms, 0.1370366467318281squares/ms
Calculated target 50 of 56: 01779803  size 58x33, 1914.0 in 5993ms, 0.31937260136826295squares/ms
Calculated target 51 of 56: 01779804  size 49x37, 1813.0 in 9948ms, 0.18224768797748292squares/ms
TargetCalculator calculated 56 areas in 238305ms

The first timestep was all orange, as it all had the same value of .035 ppmV
<img width="694" alt="Screen Shot 2019-06-25 at 6 12 51 PM" src="https://user-images.githubusercontent.com/1183863/60137428-de1db480-9774-11e9-9f90-9464e1eb03f6.png">

Using the timestep selector to advance in time, the colors for each state change.
<img width="737" alt="Screen Shot 2019-06-25 at 6 08 50 PM" src="https://user-images.githubusercontent.com/1183863/60137471-fc83b000-9774-11e9-851a-0b4c7fd3a545.png">

This appears to be working. Next step is to try a deposition variable from CCTM_DRYDEP* file.

used the following script
```
#!/bin/csh -f
#script for testing command line options
echo 'running verdi_script_camx.csh'
foreach species ( O3 )
./verdi.sh \
         -f $cwd/data/model/CCTM_DRYDEP_v53_intel18.0_2016_CONUS_test_20151222.nc \
         -titleString "CMAQ ${species} Layer 1" \
         -s "${species}[1]" \
         -g tile \
         -saveImage "jpg" $cwd/test.$species.png \
 #         -quit
 end
```
<img width="625" alt="Screen Shot 2019-06-25 at 6 29 16 PM" src="https://user-images.githubusercontent.com/1183863/60138127-335ac580-9777-11e9-88cd-b47c4fab715d.png">
