### ISSUE TITLE
switching between areal avg plot and gridded data - incorrect plot

### ISSUE THREAD

**Issue by dschwede** [CEMPD/VERDI#166]
When I switch from area averages to gridded data on the areal interpolation plot, the map looks weird in that there are abrupt lines at the state boundaries that aren’t there when I just do a regular tile plot.

**Comment by lizadams** [comment]
[x] QA tested that I do not observe weird lines at the state boundaries when switching from areal interpolation plot to gridded data.
[ ] I did notice while doing this testing that the area average option worked, but area total option is greyed out and doesn't appear to be working - will create a new issue for this.
