### ISSUE TITLE
Removing shapefiles - add "-" button

### ISSUE THREAD

**Issue by dschwede** [CEMPD/VERDI#167]
I wanted to switch out and use a different shapefile.  You can right click and delete the area file.  It seems like there should also be a “-“ button next to the “+” one as is done for datasets. Interesting that when I checked the formulas window there is only a “-“ but I can’t see the “-“ on the button.  I guess it makes sense there that there isn’t a “+” for the formula window since the “Add” button is next to the formula itself.

**Comment by lizadams** [comment]
[x] QA Tested, and confirmed that there is a "-" button next to the "+" one, and that you can successfully remove a shapefile, note that when you do that, it removes the data from the areal interpolation plot, but this doesn't close the areal interp plot window.
