### ISSUE TITLE
Error using LWMASK in formula

### ISSUE THREAD

**Issue by dschwede** [CEMPD/VERDI#168]
To screen out water values from the map, I tried multiplying O3[1] * LWMASK[2].  I got the expected messages about units issues and ignored those.  Eventually, I got a array out of bounds error.

**Comment by systemsgo** [comment]
Can you upload the file(s) you were using where this happened?  It doesn't appear to be a general problem, I suspect it's related to the data files you used.

**Comment by dschwede** [comment]
Some files you can use are
/work/MOD3DEV/sgf/data/CMAQv5.2/base/output/CCTM_DRYDEP_v52_base_20110711.nc
/work/MOD3DATA/2011_12US1/met/mcip_v43_wrf_v38_ctrl/GRIDCRO2D_20110711

**Comment by lizadams** [comment]
[ ] Liz will try using m3tshift to time shift the files so that they are on the same time range and to see if this will allow the formula O3[1] * LWMASK[2] to work.
