### ISSUE TITLE
Output data for correct time step and layer (FastAreaTilePlot)

### ISSUE THREAD

**Issue by joellenb** [CEMPD/VERDI#17]
Currently, data for the first time step and first vertical layer are always output when saving from the FastAreaTilePlot regardless of the time step and layer on the screen. Fix this so that VERDI outputs what is currently displayed to the user.

**Comment by cseppan** [comment]
I tested PNG, ASCII, and Shapefile export and all seemed to be saving the correct data with respect to time step and layer.

**Comment by cseppan** [comment]
Also just tested exporting a CSV file from the Tile Probe data table and got the expected output.

**Comment by lizadams** [comment]
this issue has been resolved.
