### ISSUE TITLE
IOAPI file not recognized in v1.6

### ISSUE THREAD

**Issue by dschwede** [CEMPD/VERDI#171]
A user created the file below according to IOAPI standards.  VERDI v 1.5 can plot it but v1.6 doesn't recognized it.

/work/MOD3EVAL/css/ENSEMBLE_JRC/ensemble_download/ndep_mmm_aqmeii23_annual_EU_7models.ioapi

**Comment by jherwehe** [comment]
VERDI_2.0_beta.20190521 is able to correctly load and plot the IOAPI file referenced above (plus other IOAPI files in that directory).
