### ISSUE TITLE
Upgrade to Java 8

### ISSUE THREAD

**Issue by dschwede** [CEMPD/VERDI#174]
EPA is distributing Java 8 update 161.  We should update VERDI as well to be compliant.

**Comment by lizadams** [comment]
VERDI version 2.1 I (currently testing VERDI_2.1_mac_20211206.tar.gz) was updated to use openJDK 16.0.2

./java -version
openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7)
OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (build 16.0.2+7, mixed mode)
