### ISSUE TITLE
time stamp error

### ISSUE THREAD

**Issue by dschwede** [CEMPD/VERDI#175]
From a user ...

This is a NRT WRF run for Mar 24. Should be 00 UTC @ t=1, but it does a similar adjustment. Almost like it thinks the dataset is 0000 EST, so it adjusts to UTC or something. The only weird thing is the NOOKSAK domain (Pacific Northwest) run adjusted + 5 hours.

![pblh](https://user-images.githubusercontent.com/17141102/38045827-f4f972ba-328b-11e8-8700-f829545fc6db.png)

 

MPAS is even stranger. This is a Aug 1, 2016 output, but it uses the current system time in UTC. I’ll go back and check, but it seems like pervious versions did not have this time stamp problem with either WRF or MPAS output.

![mpas_time_stamp](https://user-images.githubusercontent.com/17141102/38045842-fbf7a3b6-328b-11e8-8bad-be3334d6a412.png)

 Here is a link to WRF output. I tested multiple though, so any on the system should give a testbed.
/work/MOD3DEV/grc/NOOKSACK/4KM/OUTPUT/G.DIFF2_DEP1_6TH0/wrfout_19-24.nc

Here is a link to the  MPAS data
/work/MOD3DEV/grc/MPAS/OUTPUTS/46-12km/2016/history.2016-03-06.nc

**Comment by jherwehe** [comment]
No time stamp problems found in VERDI_2.0_beta.20190521 when plotting CMAQ, WRF, and MPAS files.
