### ISSUE TITLE
Outdated map of Europe

### ISSUE THREAD

**Issue by dschwede** [CEMPD/VERDI#177]
attached is the Europe map VERDI generates when visualizing data in this ioapi file:

/work/MOD3EVAL/css/ENSEMBLE_JRC/ensemble_download/precip_monthly_EU_2006_aqmeiigrid.ioapi

The map is pre-1990, it still shows East and West Germany as separate countries, shows all of Yugoslawia as single country rather than Croatia, Serbia, Slovenia and Bosnia/Herzegovina as separate countries, shows Ukraine, Belarus, Latvia, Lithuania and Estonia not as separate countries but as part of the Soviet Union, etc.
![verdi_map_europe](https://user-images.githubusercontent.com/17141102/38829717-00e4e1ee-4188-11e8-89f3-f9e51a986e9c.png)

**Comment by lizadams** [comment]
I believe that we can use a shapefile map from Natural Earth https://www.naturalearthdata.com/downloads/ 
<img width="1276" alt="qgis_display_10m_admin_0_scale_ranks_with_minor_islands" src="https://user-images.githubusercontent.com/1183863/45780263-2aa6f300-bc2b-11e8-9588-cdce17183331.png">

I've circled the download button on this screen shot of the Natural Earth Download Page.
<img width="664" alt="natural_earth_screenshot" src="https://user-images.githubusercontent.com/1183863/45783877-0e0fb880-bc35-11e8-902e-1a6c9ed43de8.png">

I've also attached the shapefile.
[ne_10m_admin_0_scale_rank_minor_islands.zip](https://github.com/CEMPD/VERDI/files/2398845/ne_10m_admin_0_scale_rank_minor_islands.zip)

Here is a link to their terms of use:
https://www.naturalearthdata.com/about/terms-of-use/

**Comment by lizadams** [comment]
@dschwede and @systemsgo - let me know if this will work as the map layer.

**Comment by dschwede** [comment]
The map looks good.  @systemsgo will need to test it.

**Comment by lizadams** [comment]
Tried to load the natural earth map as an > other map, and VERDI gave this error
![verdi_load_background_map_error](https://user-images.githubusercontent.com/1183863/46169943-6dd81600-c26a-11e8-8c19-c05be7850930.PNG)

Renamed the map to map_world.shp (so it would load instead of the current world map), and it has funny lines on it.
![world_map_from_natural_earth](https://user-images.githubusercontent.com/1183863/46170030-aaa40d00-c26a-11e8-95fa-5c333ddf1c8a.PNG)

**Comment by lizadams** [comment]
Found following websites for global shapefiles:
https://guides.library.upenn.edu/globalgis
http://www.arcgis.com/home/item.html?id=3e650cfe52b84bffacb86d028f1f0514
[Department_of_State_Large-Scale_International_Boundary_28LSIB29.zip](https://github.com/CEMPD/VERDI/files/2426334/Department_of_State_Large-Scale_International_Boundary_28LSIB29.zip)
Will try this one out in VERDI

**Comment by lizadams** [comment]
Looked at the NCL site for where they obtain their shapefiles, and found the https://www.gadm.org/ site.

**Comment by systemsgo** [comment]
I've fixed the problem opening other shapefiles.  I see the same spurious lines in the natural earth map when I view it at www.mapshaper.org - I suspect they may be part of the data set.  The Department_of_State file looks promising.  It's mostly okay, but has an odd shape extending from South Africa that I don't see in mapshaper.  Mapshaper also shows several annotations that don't appear in VERDI.  I suspect there's something in the shapefile spec that's not fully supported.  I'll continue investigating.  The gadm files are very large - ranging from several hundred MB to over 1GB.  We probably want to use something less detailed and smaller.

**Comment by lizadams** [comment]
Another possible world  shapefile, but this one has a spurious line over Canada.
TM_WORLD_BORDERS-0.3.zip
<img width="627" alt="screen shot 2018-10-01 at 2 31 37 pm" src="https://user-images.githubusercontent.com/1183863/46308038-93289500-c586-11e8-8266-8dfd3ecad7dc.png">
shapefile http://thematicmapping.org/downloads/world_borders.php

I will also try the simplified version.

**Comment by lizadams** [comment]
I can't find a shapefile that is newer, and that VERDI can display without spurious lines.
VERDI uses GeoTools for the shapefile plotting.  I thought I would try to use udig, which is another program that uses GeoTools to see if it had the same problem. http://udig.refractions.net/files/docs/latest/user/Running%20uDig.html#max-os-x 
Unfortunately, I couldn't get udig running on either my mac or the linux box. I believe this is another diversion..
https://medium.com/codefx-weekly/geotools-on-java-9-e8717e347a1f

**Comment by lizadams** [comment]
The Department of State shapefile, when displayed by VERDI has spurious lines.  I haven't found a reason why yet. An article suggests that we should move beyond using shapefiles to using other vector formats.  For future consideration.
http://switchfromshapefile.org/

**Comment by lizadams** [comment]
I was able to clean up the Department of State Shapfile using QGIS> Geometry Tools > Check Validity.
I can load the following dataset: world_NOx_latlon.ncf and display the background map with no spurious lines.
<img width="657" alt="screen shot 2018-10-12 at 1 16 52 pm" src="https://user-images.githubusercontent.com/1183863/46883736-f6d17e80-ce20-11e8-9614-206642644b3a.png">
<img width="638" alt="screen shot 2018-10-12 at 1 15 47 pm" src="https://user-images.githubusercontent.com/1183863/46883750-ffc25000-ce20-11e8-93ca-1ed8d0878d1f.png">

**Comment by lizadams** [comment]
This issue has been fixed - see update on bug #190
