### ISSUE TITLE
VERDI opens and doesn't allow the user to scale the application to fit in the window

### ISSUE THREAD

**Issue by dschwede** [CEMPD/VERDI#178]
Several people have reported that new versions don't scale to the window correctly and other behaviors.

No buttons to close the program in the upper right corner and function tabs don't stay up until I hold the mouse button down.

**Comment by lizadams** [comment]
VERDI also hides the min/max value below the plot, and or the plot color legend on the side.
```
#!/bin/csh -f
#script for testing command line options
echo 'running verdi_script_utm.csh'
foreach species ( HOUSEHOLDS )
./verdi.sh \
         -f $cwd/data/model/grid_pophous_utm.ncf \
         -s "${species}[1]" \
         -g tile \
         -saveImage "jpg" $cwd/test.$species.png \
 #         -quit
 end
```
The following plot that is displayed to the user is missing the min/max values at the bottom.
<img width="1047" alt="Screen Shot 2019-06-26 at 2 09 39 PM" src="https://user-images.githubusercontent.com/1183863/60204066-27750f00-981c-11e9-8e95-76532666d263.png">

If I adjust the window size to be more narrow, I can see the min/max values at the bottom, but the legend gets cut-off.
<img width="569" alt="Screen Shot 2019-06-26 at 2 11 17 PM" src="https://user-images.githubusercontent.com/1183863/60204212-5ab79e00-981c-11e9-82d5-4af4323c9616.png">

**Comment by lizadams** [comment]
related to issue #1

**Comment by lizadams** [comment]
This appears to be resolved.
