### ISSUE TITLE
FastAreaTilePlot data table shows incorrect time step and vertical layer

### ISSUE THREAD

**Issue by joellenb** [CEMPD/VERDI#18]
The values for the time step and the vertical layer are base-0 instead of base-1 (e.g., 0,1,2 instead of 1,2,3), which is how these data values are displayed on the screen for the user. This needs to be fixed in both the title and the tab for a data table.

**Comment by cseppan** [comment]
Just tested the data table display. Title is matching the Tile Plot interface, e.g. data from 2am, layer 3 gets titled "Tile Probe: O3[1] (3, 3, 5 - 24, 47 - 67)".
