### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#194]
David Lyder reported that memory isn't being released when you unload a dataset.
This is using the following build of VERDI: VERDI_2.0_beta_linux64_20181112.tar.gz

"When I open a data cube you can see the system allocate memory (RAM) to Verdi to do this. When I close the cube the memory was not released. I have a similar issue when writing out shape files. Memory is allocated to make the file but once it is copied to disk the memory is not released."

Using an example dataset that is provided with AMET which **6.5G** in size
https://drive.google.com/file/d/173_EjD_jChWCh-XjVvRArSWIbTL2uFhf/view?usp=sharing

When the file is loaded, I can use top to see the amount of memory

Select variable, DDEP_ANAJK
If I subset the file by [] use Time Range, and select Min: 1, Max: 24, and then select Tile Plot, then the program uses **1.7g** of RES memory.
If I try to close the tile plot, the memory doesn't get released.
If I try to remove the dataset, the memory doesn't get released.
It is only when I kill VERDI that the memory is released.

If I don't subset the file, then program uses 2.7g of RES Memory initially, but then if I step thru all of the 744 timesteps, the RES memory goes up to 3.7g.

<img width="795" alt="screen shot 2018-11-20 at 2 02 25 pm" src="https://user-images.githubusercontent.com/1183863/48795935-47fc4a00-eccc-11e8-8810-f2e04796d4b4.png">

**Comment by systemsgo** [comment]
The fact that memory doesn't down when you close a dataset doesn't indicate that there's a bug.  When the JVM "frees" memory, it isn't always released back to the operating system, and OS tools will still show it as being in use.  To test whether or not memory is released, please open a large dataset, check memory, close the dataset, and open another similarly sized dataset.  Memory usage shouldn't change much when the second dataset is opened - if it does, that means there is a problem.  I did the test, and it turns out there IS a memory problem going on - I'm working on fixing it.  Just wanted to let you know that once it's fixed, you may not notice unless you close the first data set and open a second.

**Comment by lizadams** [comment]
using VERDI_2.0_beta_linux64_20190623.tar.gz and the following verdi script:

```
#!/bin/csh -f

#script for testing command line options

echo 'running verdi_script_mpas.csh'
setenv verdi_dir /proj/ie/apps/longleaf/VERDI_2.0_jun_23/VERDI_2.0_beta
cd $verdi_dir

foreach species ( t2m )
./verdi.sh \
         -f $verdi_dir/data/model/history.2013-07-10.nc \
#          -configFile $verdi_dir/data/configs/10bin_new_config \
#         -legendBins ".008,.016,.024,.032,.04,.048,.056,.064,.072,.08" \
#         -titleString "CMAQv46 ${species} Layer 1" \
         -s "${species}[1]" \
         -g tile \
#         -saveImage "jpg" $verdi_dir/test.$species.png \
#         -animatedGIF $verdi_dir/test.$species.gif \
#          -quit
          echo 'check outputfile' `ls -lrt $verdi_dir/test.$species.png`
         # echo 'check outputfile' `ls -lrt $verdi_dir/test.$species.gif`
 end
```
VERDI appeared to only be using memory when the user is changing the timestep or layer, so it appears to be freeing the memory back to the operating system.

Following image shows VERDI isn't consuming Memory according to top.
<img width="960" alt="Screen Shot 2019-06-24 at 6 07 33 PM" src="https://user-images.githubusercontent.com/1183863/60055397-7d767500-96ab-11e9-8caa-ce8bc47d172d.png">
When I changed the timestep, I could see that VERDI was using memory, as is shown in the following screenshot of top: (see java process that is owned by lizadams)
<img width="960" alt="Screen Shot 2019-06-24 at 6 08 08 PM" src="https://user-images.githubusercontent.com/1183863/60055408-823b2900-96ab-11e9-8b96-34ae455dcdf4.png">
