### ISSUE TITLE
Lack of Antarctic coastline

### ISSUE THREAD

**Issue by jherwehe** [CEMPD/VERDI#196]
When the GIS layer shapefiles changed from map_world to Department_of_State_QGIS files, the Antarctic coastline was lost, along with interior bodies of water.  Date of change was October 15 release.

**Comment by dschwede** [comment]
We could include both Shapefiles and let people choose which one they want.  If inland lakes are more important, they can use the old one.

**Comment by jherwehe** [comment]
And perhaps we can add a separate shapefile just for the interior water bodies, to be added when needed.

**Comment by lizadams** [comment]
The following shapefile contains the major lakes. https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-lakes/
This screenshot shows VERDI with both the state_department shapefile and the ne_10m_lakes.shp loaded.
<img width="824" alt="screen shot 2018-12-10 at 1 06 58 pm" src="https://user-images.githubusercontent.com/1183863/49751530-95405b80-fc7b-11e8-8598-77b62d2624bd.png">

**Comment by lizadams** [comment]
The ne_10m_coastline.shp can be used as a replacement for the state_depart.shp
https://www.naturalearthdata.com/downloads/10m-physical-vectors/
It correctly displays the Antarctic coastline.
This VERDI plot was created with the ne_10m_coastline.shp 
<img width="835" alt="screen shot 2018-12-10 at 1 13 23 pm" src="https://user-images.githubusercontent.com/1183863/49751831-7e4e3900-fc7c-11e8-8256-3c9fc6ac4e8e.png">

**Comment by dschwede** [comment]
Can we combine the shapefiles to get one that has it all or is it enough to let people layer them as they see fit (as long as we provide hem all).  Are these shapefiles freely distributable?

**Comment by lizadams** [comment]
I am going to try and merge the three layers into one using http://michaelminn.com/linux/mmqgis/

**Comment by jherwehe** [comment]
As of the 20190618 version of VERDI 2.0 beta, the Antarctic coastline is now available as part of the default "World" GIS layer.  Plus, all "World" coastlines appear to be higher resolution than previously available, which is good when zooming into an area.
