### ISSUE TITLE
saving an Image after loading variable from command line script doesn't work for MPAS file

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#198]
The following command should work to load a dataset, then load a formula, and create a tile plot.
```
 ./verdi.command -f /applications/VERDI_2.0_beta/data/model/t2m_only.nc -s "t2m[1]" -g tile
```

It works only up to the point where it loads the dataset and then stops.  I don't see any errors, it just doesn't go to the next step of loading the formula, and creating the tileplot.
The command does produce the following output:
```
in netcdfdataset.java openDataset 1 arguments
in netcdfdataset.java openDataset 3 arguments
in netcdfdataset.java ready to return openDataset 5 arguments
```

This works for a CMAQ output file.
./verdi.command -f $cwd/data/model/CCTM47_aac_spr06.12k.CONC.2006113.O3.ncf -s "O3[1]" -g tile

**Comment by lizadams** [comment]
The loading a variable from an MPAS file from the command line works.
<img width="893" alt="t2_only_mpas tileplot" src="https://user-images.githubusercontent.com/1183863/59222263-14fda300-8b97-11e9-8d02-72f8af7ff722.png">

 The next step of saving it as an image from the command line fails.
This is likely due to the new ability of the user to specify the height and width of the Plot thru the GUI, but the ability to specify these values from the command isn't supported yet.
<img width="398" alt="height_width_mpas" src="https://user-images.githubusercontent.com/1183863/59222372-5b530200-8b97-11e9-9ff0-9dc47488f651.png">

./verdi.sh -f $cwd/data/model/t2m_only.nc -s "t2m[1]" -gtype tile -saveImage "png" $cwd/t2m_only.png -quit
in netcdfdataset.java openDataset 1 arguments
in netcdfdataset.java openDataset 3 arguments
in netcdfdataset.java ready to return openDataset 5 arguments
2019.06.10 15:43:46.326 [main] ERROR anl.verdi.commandline.ScriptHandler - Null Pointer Exception in ScriptHandler.dataMap.put 'GTYPE': null
2019.06.10 15:43:46.326 [main] ERROR anl.verdi.commandline.ScriptHandler - Null Pointer Exception in ScriptHandler.dataMap.put 'SAVEIMAGE': null

In verdi, the users can typically use either `-gtype tile` or `-g tile`.  For loading the MPAS files, it appears that only `-g tile` works.

So, using -g tile, fewer errors were generated, but it still resulted in an error when I tried to use the -SaveImage command to save the image as a png.

./verdi.sh -f $cwd/data/model/t2m_only.nc -s "t2m[1]" -g tile -saveImage "png" $cwd/t2m_only.png -quit
in netcdfdataset.java openDataset 1 arguments
in netcdfdataset.java openDataset 3 arguments
in netcdfdataset.java ready to return openDataset 5 arguments
2019.06.10 15:44:16.631 [Thread-7] ERROR anl.verdi.plot.gui.MeshPlot - Error rendering MeshPlot
java.lang.NullPointerException
	at anl.verdi.core.VerdiGUI.showIfVisible(VerdiGUI.java:266) ~[core.jar!/:?]
	at anl.verdi.plot.gui.MeshPlot$7.run(MeshPlot.java:923) [core.jar!/:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
java.lang.NullPointerException
	at anl.verdi.core.VerdiGUI.showIfVisible(VerdiGUI.java:266)
	at anl.verdi.plot.gui.MeshPlot$7.run(MeshPlot.java:923)
	at java.lang.Thread.run(Thread.java:745)

**Comment by lizadams** [comment]
tested this using the VERDI_2.0_beta_linux64_20190623.tar.gz build of VERDI
<img width="852" alt="Screen Shot 2019-06-24 at 2 12 43 PM" src="https://user-images.githubusercontent.com/1183863/60041805-3b890700-968a-11e9-9b79-6ecabd86c634.png">

When I tried to save this file as an image, it gave an error.
 ./verdi.sh -f $cwd/data/model/t2m_only.nc -s "t2m[1]" -g tile -saveImage "png" ~/t2m_only.png -quit
in netcdfdataset.java openDataset 1 arguments
in netcdfdataset.java openDataset 3 arguments
in netcdfdataset.java ready to return openDataset 5 arguments
2019.06.24 14:15:06.333 [Thread-7] ERROR anl.verdi.plot.gui.MeshPlot - Error rendering MeshPlot
java.lang.NullPointerException
	at anl.verdi.core.VerdiGUI.showIfVisible(VerdiGUI.java:266) ~[core.jar!/:?]
	at anl.verdi.plot.gui.MeshPlot$7.run(MeshPlot.java:923) [core.jar!/:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
java.lang.NullPointerException
	at anl.verdi.core.VerdiGUI.showIfVisible(VerdiGUI.java:266)
	at anl.verdi.plot.gui.MeshPlot$7.run(MeshPlot.java:923)
	at java.lang.Thread.run(Thread.java:745)

But it does create the png plot
display ~/t2m_only.png
<img width="800" alt="Screen Shot 2019-06-24 at 2 16 42 PM" src="https://user-images.githubusercontent.com/1183863/60042014-b6eab880-968a-11e9-857f-5bbaa97e80e9.png">

**Comment by lizadams** [comment]
Re-tested this with the VERDI_2.1_mac_20211206.tar.gz version, and am seeing the same behavior.
The tile plot is successfully created, but VERDI throws an error.

./verdi.sh -f $cwd/data/model/t2m_only.nc -s "t2m[1]" -g tile -saveImage "png" ~/t2m_only.png -quit
OpenJDK 64-Bit Server VM warning: Option --illegal-access is deprecated and will be removed in a future release.
in netcdfdataset.java openDataset 1 arguments
in netcdfdataset.java openDataset 3 arguments
in netcdfdataset.java ready to return openDataset 5 arguments
2021.12.08 15:54:29.068 [Thread-5] ERROR anl.verdi.plot.gui.MeshPlot - Error rendering MeshPlot
java.lang.NullPointerException: Cannot invoke "java.awt.Graphics.drawImage(java.awt.Image, int, int, java.awt.image.ImageObserver)" because "graphics" is null
	at anl.verdi.core.VerdiGUI.showIfVisible(VerdiGUI.java:266) ~[core.jar:?]
	at anl.verdi.plot.gui.MeshPlot$7.run(MeshPlot.java:924) [core.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:831) [?:?]
java.lang.NullPointerException: Cannot invoke "java.awt.Graphics.drawImage(java.awt.Image, int, int, java.awt.image.ImageObserver)" because "graphics" is null
	at anl.verdi.core.VerdiGUI.showIfVisible(VerdiGUI.java:266)
	at anl.verdi.plot.gui.MeshPlot$7.run(MeshPlot.java:924)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1.3_linux64_20220210.tar.gz, still seeing a similar error as below:
But the tile plot was successfully created and the image was saved as *.png file.** 
./verdi.sh -f /work/MOD3APP/yxu/VERDI_2.1.3/data/model/t2m_only.nc -s "t2m[1]" -g tile -saveImage "png" ~/t2m_only.png -quit
OpenJDK 64-Bit Server VM warning: Option --illegal-access is deprecated and will be removed in a future release.
in netcdfdataset.java openDataset 1 arguments
in netcdfdataset.java openDataset 3 arguments
in netcdfdataset.java ready to return openDataset 5 arguments
java.lang.NullPointerException: Cannot invoke "java.awt.Graphics.drawImage(java.awt.Image, int, int, java.awt.image.ImageObserver)" because "graphics" is null
        at anl.verdi.core.VerdiGUI.showIfVisible(VerdiGUI.java:266)
        at anl.verdi.plot.gui.MeshPlot$7.run(MeshPlot.java:926)
        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1.4_linux64_20220526.tar.gz on Atmos, found that this issue has resolved.**  
./verdi.sh -f /work/MOD3APP/yxu/VERDI_2.1.4/data/model/t2m_only.nc -s "t2m[1]" -g tile -saveImage "png" ~/t2m_only.png -quit
The title plot was successfully created and the image was saved as .png file.
![issue_198_VERDI_testing_1](https://user-images.githubusercontent.com/73186639/171487215-4e789382-8e22-4d15-9127-c5788b9b7da9.png)

**Comment by cbroker1** [comment]
Tested VERDI_2.1.4_win64_20220526.zip on Windows 11

Failed to produce plot, image did not save. 

'./run.bat -f C:/Users/carlb/Downloads/VERDI_2.1.4_win64_20220526/VERDI_2.1.4_win/data/model/t2m_only.nc -s "t2m[1]" -g tile -saveImage "png" C:/Users/carlb/Downloads/VERDI_2.1.4_win64_20220526/VERDI_2.1.4_win/data/plots/t2m_only.png -quit'

<img width="796" alt="image" src="https://user-images.githubusercontent.com/43118284/171664563-8f0a0e30-d71d-4268-a76a-03c189d8f7fa.png">

**Comment by cbroker1** [comment]
Attempting the same execution above w/o `-f` in the command, produces different error.

<img width="623" alt="image" src="https://user-images.githubusercontent.com/43118284/171683188-713aa634-d414-4d8a-90bc-e3794431ca37.png">

**Comment by dkang2** [comment]
Hi Yadong,

I tried to replicate what you did, but it generated an error message and didn't save the .png file.

./verdi.sh -f /home/dkj/VERDI/VERDI_2.1.4/data/model/t2m_only.nc -s "t2m[1]" -g tile -saveImage "png"~/t2m_only.png -quit

The error is:
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option --illegal-access=permit; support was removed in 17.0
in netcdfdataset.java openDataset 1 arguments
in netcdfdataset.java openDataset 3 arguments
in netcdfdataset.java ready to return openDataset 5 arguments
2022.06.06 14:28:41.481 [main] ERROR anl.verdi.core.VerdiPlugin - Error
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]

Did I do anything wrong?

Thanks,

Daiwen

**Comment by cbroker1** [comment]
I might be experiencing the same as @dkang2, but on Windows:

Ver - VERDI_2.1.4_win64_20220526.zip
OS - Windows 11
CMD (terminal) - ./run.bat -f C:/Users/carlb/Downloads/VERDI_2.1.4_win64_20220526/VERDI_2.1.4_win/data/model/t2m_only.nc -s "t2m[1]" -g tile -saveImage "png" ~/t2m_only.png -quit

Resulting in - 
<img width="949" alt="image" src="https://user-images.githubusercontent.com/43118284/172187217-92768e2f-c5b8-45bf-bb75-58a1a6a23cb5.png">

My error output does not give me the same level of detail, but similar..

**Comment by yadongxuEPA** [comment]
> Hi Yadong, I tried to replicate what you did, but it generated an error message and didn't save the .png file. ./verdi.sh -f /home/dkj/VERDI/VERDI_2.1.4/data/model/t2m_only.nc -s "t2m[1]" -g tile -saveImage "png"~/t2m_only.png -quit The error is: Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option --illegal-access=permit; support was removed in 17.0 in netcdfdataset.java openDataset 1 arguments in netcdfdataset.java openDataset 3 arguments in netcdfdataset.java ready to return openDataset 5 arguments 2022.06.06 14:28:41.481 [main] ERROR anl.verdi.core.VerdiPlugin - Error java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2 at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?] at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?] Did I do anything wrong? Thanks, Daiwen From: Yadong Xu ***@***.***> Sent: Wednesday, June 01, 2022 3:35 PM To: CEMPD/VERDI ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [CEMPD/VERDI] saving an Image after loading variable from command line script doesn't work for MPAS file (#198) Retested with VERDI_2.1.4_linux64_20220526.tar.gz on Atmos, found that this issue has resolved. ./verdi.sh -f /work/MOD3APP/yxu/VERDI_2.1.4/data/model/t2m_only.nc -s "t2m[1]" -g tile -saveImage "png" ~/t2m_only.png -quit The title plot was successfully created and the image was saved as .png file. [issue_198_VERDI_testing_1]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F73186639%2F171487215-4e789382-8e22-4d15-9127-c5788b9b7da9.png&data=05%7C01%7CKang.Daiwen%40epa.gov%7C69f43160b8f44f09e1e208da4405da89%7C88b378b367484867acf976aacbeca6a7%7C0%7C0%7C637897089177096294%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tjAawDkBBo7Sxd5QZtDejU7rC4N9hy8Z%2FzmI8LGnOkU%3D&reserved=0> - Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCEMPD%2FVERDI%2Fissues%2F198%23issuecomment-1144053908&data=05%7C01%7CKang.Daiwen%40epa.gov%7C69f43160b8f44f09e1e208da4405da89%7C88b378b367484867acf976aacbeca6a7%7C0%7C0%7C637897089177096294%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XSh3dCl%2FQRRH4uVdDb3OkTzHlDa6JSbPXidB7AIfBHI%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADTIXN62CA2N2YK7Y5QSOQDVM63PFANCNFSM4GKJBHLQ&data=05%7C01%7CKang.Daiwen%40epa.gov%7C69f43160b8f44f09e1e208da4405da89%7C88b378b367484867acf976aacbeca6a7%7C0%7C0%7C637897089177252052%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AtZXGdybMBMWC5WH53Cn6i45TIqcMNimpkLm8PCjODM%3D&reserved=0>. You are receiving this because you are subscribed to this thread.Message ID: ***@***.******@***.***>>

Hi Daiwen,

The only difference in the command line between yours and mine is that space after "png" inside  "-saveImage "png"~/t2m_only.png", please add it and run it again.  

Thanks,
Yadong

**Comment by yadongxuEPA** [comment]
> I might be experiencing the same as @dkang2, but on Windows:
> 
> Ver - VERDI_2.1.4_win64_20220526.zip OS - Windows 11 CMD (terminal) - ./run.bat -f C:/Users/carlb/Downloads/VERDI_2.1.4_win64_20220526/VERDI_2.1.4_win/data/model/t2m_only.nc -s "t2m[1]" -g tile -saveImage "png" ~/t2m_only.png -quit
> 
> Resulting in - <img alt="image" width="949" src="https://user-images.githubusercontent.com/43118284/172187217-92768e2f-c5b8-45bf-bb75-58a1a6a23cb5.png">
> 
> My error output does not give me the same level of detail, but similar..

Hi Carl,

Those are the log messages (used for debug purposes, not error messages. They also showed up in Atmos). Did you check if the "*.png" was saved to your work directory?

Thanks,
Yadong

**Comment by cbroker1** [comment]
Solved!

I specified a specific work directory and found the "*.png" in question. 

-CMD: ./run.bat -f C:/Users/carlb/Downloads/VERDI_2.1.4_win64_20220526/VERDI_2.1.4_win/data/model/t2m_only.nc -s "t2m[1]" -g tile -saveImage "png" C:/Users/carlb/Downloads/VERDI_2.1.4_win64_20220526/VERDI_2.1.4_win/data/plots/t2m_only.png -quit

<img width="628" alt="image" src="https://user-images.githubusercontent.com/43118284/172196936-5c5054df-acb4-4f10-984b-5065c7665347.png">

Thanks!

**Comment by dkang2** [comment]
Thanks, Yadong. It worked by adding the space.

I also tested to save the image file into different directories. It seems that besides the ~/ directory, the $cwd/ for current directory also worked, but the ./ and just specify the file name itself, it doesn't work, meaning that a whole path is needed.

Daiwen
