### ISSUE TITLE
VERDI 2.0 beta: obs data overlay is always in same place, regardless of lat/lon values

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#199]
Using VERDI_2.0_beta, the obs data isn't loaded to the correct lat/lon location.

Tested using a text file obs data: data/obs/verdiObs.4km_from_xorig_yorig.txt

Create a tile plot  in the csh shell:
verdi.sh -f $cwd/data/model/CCTM46_P16.baseO2a.36k.O3MAX -s "O3[1]" -g tile -f  $cwd/data/obs/verdiObs.4km_from_xorig_yorig.txt

Then add the observational data using
Plot> Add Overlay > Observations
Select Ozone (PPM)[2] from the Observational Dialog
Then select Add variable and OK

(It would be much better if there was a command line option for loading the obs data.)

With VERDI_2.0_beta, the obs overlay point is placed in Northern Kansas instead of off the coast of CA.
<img width="1177" alt="verdi_2 0_beta_obs_data_not_off_coast_ca" src="https://user-images.githubusercontent.com/1183863/52514255-106fb080-2bde-11e9-8a47-8fe2d9ca0b6a.png">

With VERDI_1.5.0, the obs overlay point is off the coast of California
Google Maps agrees with VERDI_1.5.0, that Latitude 32.2 and Longitude -121.029 is off the coast of California.
<img width="951" alt="verdi_1 5 0_obs_data_off_coast_ca" src="https://user-images.githubusercontent.com/1183863/52514254-106fb080-2bde-11e9-9f8c-130ce9d4bf8a.png">

If I change the longitude value in the obs file to the lat/lon value for James River State park in VA.
Timestamp(UTC)	LONGITUDE(deg)	LATITUDE(deg)	STATION(-)	ozone(ppm)
2006-07-03T00:00:00-0000	-121.029	32.2	111993	0.04

Then VERDI_1.5.0 correctly places the obs data in Southern VIrginia.

<img width="782" alt="verdi_1 5 0_observational_data_jame_river_state_park_va" src="https://user-images.githubusercontent.com/1183863/52514185-a22aee00-2bdd-11e9-986e-d9d834d82c48.png">

VERDI_2.0_beta keeps the obs data in Northern Kansas.

**Comment by systemsgo** [comment]
This file is evidently in IOAPI format, not regular netCDF. You can overlay these observations onto this CMAQ v5.3 example file to test timing and geolocation issues:

/work/MOD3DEV/jherwehe/verdi/test/CMAQ_v53_Dev/CMAQv53b1_2016_12US1_M3Dry_Bidi_OCoating/03/CCTM_ACONC_v5.3.b1_intel17.0_2016_CONUS_M3Dry_Bidi_OCoating_20160320.nc

**Comment by lizadams** [comment]
tested with VERDI_2.0_beta_linux64_20190623.tar.gz
using observational data file in text format: data/obs/verdiObs.4km_from_xorig_yorig.txt
The observational data point is correctly positioned off of the coast of California.
<img width="863" alt="Screen Shot 2019-06-24 at 1 52 14 PM" src="https://user-images.githubusercontent.com/1183863/60040600-60c84600-9687-11e9-9f35-f9f2ad6955d2.png">

**Comment by lizadams** [comment]
closing this bug - as txt based observation files are being correctly georeferenced
