### ISSUE TITLE
Unable to read obs overlay file in netCDF format

### ISSUE THREAD

**Issue by jherwehe** [CEMPD/VERDI#201]
VERDI is unable to read obs overlay files that are netCDF or IOAPI formatted, giving a "No loaders are available for the selected file" error message.  This has been a problem since at least the 20161005 version of VERDI_1.6.0_alpha (the oldest version of that series I could find).  However, text-based (.txt) obs overlay files can be read, but have the geolocation problem described in Issue #199.
VERDI 1.5.0 does still read obs overlay files with  the *.ncf and *.ioapi extensions, but seems to have a time-synchronizing problem when the time step is advanced/changed.

**Comment by jherwehe** [comment]
The example obs overlay used when the problem was discovered can be found on atmos here:

/work/MOD3EVAL/wtt/obs_data/Release_Obs_Dev/Tools/Obs_Overlay/AQS_Hourly_PAVE_VERDI_overlay_2016.ncf

This file is evidently in IOAPI format, not regular netCDF.  You can overlay these observations onto this CMAQ v5.3 example file to test timing and geolocation issues:

/work/MOD3DEV/jherwehe/verdi/test/CMAQ_v53_Dev/CMAQv53b1_2016_12US1_M3Dry_Bidi_OCoating/03/CCTM_ACONC_v5.3.b1_intel17.0_2016_CONUS_M3Dry_Bidi_OCoating_20160320.nc

**Comment by jherwehe** [comment]
Testing the 20190521 beta using the *20060703* example model and obs files under VERDI's "data" directory tree seems to work fine using the text-based obs file.

However, when testing with the IOAPI-formatted obs file and model output from the paths in my previous comment above, the IOAPI-formatted obs now load, but there is still a problem with the station sites disappearing when you advance the time one hour, then they gradually reappear when you continue to advance the time.  Eventually when you come back around to 00:00:00 UTC, no station data are visible (but they gradually reappear as you continue to advance the time).  You can see this problem more quickly if you animate the plot.  [By the way, note that O3 will need to be multiplied by 1000. to convert the CMAQ data from ppmV to ppbV  in order to match the obs file O3 units.]  It is always possible that this problem is caused by something wrong with the obs overlay file and is not a VERDI problem.

**Comment by lizadams** [comment]
Loading an observational dataset worked using VERDI_2.0_beta_linux64_20190623.tar.gz
Used the following script to load the model and obs data, but had to load the obs data onto the tile plot using the GUI, as there isn't a command to load the obs data from the command line.

```
#!/bin/csh -f

#script for testing command line options

echo 'running verdi_script_obs.csh'
setenv verdi_dir /proj/ie/apps/longleaf/VERDI_2.0_jun_23/VERDI_2.0_beta
cd $verdi_dir

foreach species ( O3 )
./verdi.sh \
         -f $verdi_dir/data/model/CCTM_ACONC_v5.3.b1_intel17.0_2016_CONUS_M3Dry_Bidi_OCoating_20160320.nc \
         -f  $verdi_dir/data/obs/AQS_Hourly_PAVE_VERDI_overlay_2016.ncf \
         -s "${species}[1]" \
         -g tile \
        #  -quit
 end
```
<img width="1177" alt="Screen Shot 2019-06-24 at 5 37 02 PM" src="https://user-images.githubusercontent.com/1183863/60053862-f4f5d580-96a6-11e9-833a-61dd8c2ec971.png">

<img width="511" alt="Screen Shot 2019-06-24 at 5 38 36 PM" src="https://user-images.githubusercontent.com/1183863/60053875-fb844d00-96a6-11e9-8b82-7af334ae18ce.png">

<img width="1191" alt="Screen Shot 2019-06-24 at 5 32 43 PM" src="https://user-images.githubusercontent.com/1183863/60053573-2de17a80-96a6-11e9-8fc5-914fcea66c08.png">

**Comment by jherwehe** [comment]
Reopening this issue because the Windows version in VERDI_2.0_beta_win64_20190623.zip will not load the binary (netCDF/IOAPI) obs overlay file provided in the examples above, giving the following error message:

![obs_overlay_load_error_in_windows_for_VERDI_2 0_beta_20190623](https://user-images.githubusercontent.com/16904596/60463846-0a28b200-9c1b-11e9-809f-3718853996ad.png)

Here is the VERDI console window after the error:

![obs_overlay_load_error_in_windows_console_for_VERDI_2 0_beta_20190623](https://user-images.githubusercontent.com/16904596/60463997-62f84a80-9c1b-11e9-83e4-b2579fc455cb.png)

Is this also a problem for the Mac?

**Comment by lizadams** [comment]
Using VERDI_2.0_beta_mac_20190623.tar.gz, I obtained the same error as observed on Windows.
<img width="1180" alt="Screen Shot 2019-07-01 at 4 51 14 PM" src="https://user-images.githubusercontent.com/1183863/60466044-94bfe000-9c20-11e9-917e-96db4a5218d1.png">

**Comment by jherwehe** [comment]
Interactively using the 20190803 version of VERDI_2.0_beta on Windows 10 and macOS (Mojave Ver. 10.14.6), both are able to load binary (i.e., IOAPI-formatted) observation overlay files now.

Liz' verdi_script_obs.csh above also works now without error (at least on Linux and Windows), including the manual loading of the IOAPI-formatted obs overlay file.  The blank error message will be encountered when the times of the displayed field and obs overlay cannot be matched (e.g., in the case where the obs overlay file has fewer times available than the displayed field and the time spinner is advanced to one of those times).

Closing this issue.
