### ISSUE TITLE
Verify calculation of statistics for Fast Area Tile Plot

### ISSUE THREAD

**Issue by joellenb** [CEMPD/VERDI#21]
The same drop-down menu of statistical measures is used for both the Fast Tile Plot and the Fast Area Tile Plot. Based upon their graphical displays, however, the statistics do not appear to be calculated consistently. The methods of calculating the statistics for the Fast Area Tile Plot need to be verified against those in use for the Fast Tile Plot.

**Comment by lizadams** [comment]
closing this bug.
