### ISSUE TITLE
VERDI_HOME directory setting in verdi.sh

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#211]
**Describe the bug**
currently in the verdi.sh script, VERDI_HOME is set by the command
#! /bin/sh
export VERDI_HOME=${PWD}

If the user tries to start VERDI in a directory **other than the install directory**, then the verdi.sh script will complain with the following type of error
./VERDI_2.0_beta/verdi.sh: line 5: cd: /proj/ie/apps/longleaf/VERDI_2.0_jun_23/plugins/bootstrap: **No such file or directory**
./VERDI_2.0_beta/verdi.sh: line 34: **../../jre/bin/java: No such file or directory**

**To Reproduce**
1. Go to the directory where the verdi was installed
2. If you run verdi.sh from this directory, it will work correctly
3. If you go to any other directory, and then use the full path to start verdi from that directory you will get an error.
4. No such file or directory

**Expected behavior**
I would expect that wherever the user runs the verdi.sh script, that it is able to reference the install directory.
I typically solve this by changing the verdi.sh to use a hard-coded path to the install directory.
#! /bin/sh
#export VERDI_HOME=${PWD}
export VERDI_HOME=/proj/ie/apps/longleaf/VERDI_2.0_jun_23/VERDI_2.0_beta
export VERDI_USER=$HOME

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [linux]
 - Version [VERDI_2.0_jun_23]

**Comment by lizadams** [comment]
I tried this on linux with the July 24th package and it isn't working.

I am trying to do the following
1. go to a directory where the data is located
2. run the verdi.sh script from that directory

In the case below I am specifying the full path to VERDI, but eventually I would like to add the verdi.sh script location to my path and just type verdi.sh.

/proj/ie/apps/longleaf/VERDI_2.0_jul24/VERDI_2.0_beta/verdi.sh -f $cwd/CCTM_CONC_v53_gcc_parallel_Bench_2016_12SE1_20160701.1var.sum01-23.nc
/proj/ie/apps/longleaf/VERDI_2.0_jul24/VERDI_2.0_beta/verdi.sh: line 5: cd: /usr/bin/plugins/bootstrap: No such file or directory
/proj/ie/apps/longleaf/VERDI_2.0_jul24/VERDI_2.0_beta/verdi.sh: line 34: ../../jre/bin/java: No such file or directory

This is what is currently in verdi.sh
```
#! /bin/sh
export VERDI_HOME=`dirname "$_"`
export VERDI_USER=$HOME
DIR=`pwd`
cd "$VERDI_HOME/plugins/bootstrap"

JAVA=../../jre/bin/java
JAVAMAXMEM="-Xmx6144M"

# Limit the number of default spawned threads (eca):
JAVAOPTS="-XX:+UseParallelGC -XX:ParallelGCThreads=1 -Duser.home=$HOME -Djava.library.path=../core/lib"

if [ "$DISPLAY" = "" ]; then
  DISPOPTS="-Djava.awt.headless=true"
fi

JAVACMD="$JAVA $JAVAOPTS $JAVAMAXMEM $DISPOPTS -classpath ./bootstrap.jar:./lib/saf.core.runtime.jar:./lib/jpf.jar:./lib/jpf-boot.jar:./lib/:../core/lib/* saf.core.runtime.Boot"

BATCHCMD=$1

if [ ! -e "$2" ]; then
   BATCHFILE="$DIR""/""$2"
else
   BATCHFILE="$2"
fi

if [ "$BATCHCMD" = "-b" -o "$BATCHCMD" = "-batch" ]; then
   if [ "$#" -eq 1 ]; then
        $JAVACMD $1
   else
        $JAVACMD $1 $BATCHFILE
   fi
else
  $JAVACMD ${1+"$@"}
fi
```

If I change the second line to specify the path to the verdi.sh on my machine:
```
#! /bin/sh
export VERDI_HOME=/proj/ie/apps/longleaf/VERDI_2.0_jul24/VERDI_2.0_beta
```
Then try and run the following command, then it works.
```
/proj/ie/apps/longleaf/VERDI_2.0_jul24/VERDI_2.0_beta/verdi.sh -f $cwd/CCTM_CONC_v53_gcc_parallel_Bench_2016_12SE1_20160701.1var.sum01-23.nc
```
VERDI is displayed to my screen with the dataset loaded.

**Comment by systemsgo** [comment]
What's the output of the following commands:

uname -a
echo $0
echo $shell

Both cases work on a fedora system but it definitely could work 
differently on a different shell or os.

**Comment by lizadams** [comment]
Hi Tony,

Here is your requested output.

uname -a
Linux dogwood-login1 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

echo $0
csh

echo $shell
/bin/tcsh

Thanks, Liz


________________________________

**Comment by systemsgo** [comment]
This should work now - it was working under bash but broken under tcsh.  The current version should work across both shells.
