### ISSUE TITLE
Improve Geolocation of Observation Overlay Sites

### ISSUE THREAD

**Issue by jherwehe** [CEMPD/VERDI#212]
**Describe the bug**
Observation site data overlaid on a CMAQ field appear close to their correct locations, but zooming in reveals that several sites are drawn over water when they should be on land.

**To Reproduce**
1. During an interactive VERDI session, load from _atmos_ this file: /work/MOD3DEV/jherwehe/verdi/test/bkx/cmaq/wr401/task4/2018/cctm/extr/201808/combine_aconc_v53_intel18.0_2018ff_12US1_201808 (or if that file is too big, load the single day file /work/MOD3DEV/jherwehe/verdi/test/bkx/cmaq/wr401/task4/2018/cctm/extr/201808/combine_aconc_v53_intel18.0_2018ff_12US1_20180817).
2. Load the obs overlay file /work/MOD3DEV/jherwehe/verdi/test/wtt/obs_data/Release_Obs_Dev/Tools/Obs_Overlay/AQS_Hourly_PAVE_VERDI_overlay_2018.ncf (or just load the one-day file /work/MOD3DEV/jherwehe/verdi/test/wtt/obs_data/Release_Obs_Dev/Tools/Obs_Overlay/AQS_Hourly_PAVE_VERDI_overlay_201817.ncf).
3. Create a tile plot of O3[1], then overlay the O3[2] observations.
4. Zoom into an area that includes Maryland to Massachusetts (for example), then notice the obs sites in Long Island Sound and offshore of New Jersey and Massachusetts.

**Expected behavior**
The AQS observation sites are all land-based and should not appear over water.

**Screenshots**

From **VERDI 2.0beta 20190820** version:
![verdi_2 0_beta_20190820_O3_20180817_18UTC_with_overlay_LISTOS_zoom_cropped](https://user-images.githubusercontent.com/16904596/64368766-f3228980-cfe8-11e9-997f-3cd2ec8ac46e.png)

From old **PAVE** executable (ca. 2004), showing better obs geolocation:
![pave_O3_20180817_18UTC_with_overlay_LISTOS_zoom_cropped](https://user-images.githubusercontent.com/16904596/64368779-f9186a80-cfe8-11e9-80ed-51dd9c97b887.png)

**Desktop:**
 - Linux and Windows
 - VERDI_2.0_beta 20190820 version

**Comment by jherwehe** [comment]
Tests with the latest 20201019 version of VERDI 2.0 on Linux seem to have fixed the obs overlay data value display problem (shown above).  Below are the (approximately) same plots as above, but now produced with the **VERDI_2.0 20201019** version:

![VERDI_2 0_20201019_18UTC_NYC_and_LIS_O3_overlay_test cropped](https://user-images.githubusercontent.com/16904596/96515696-c56fc280-1233-11eb-9c4e-7ddecdd08f65.png)

![VERDI_2 0_20201019_18UTC_CONUS_O3_overlay_test cropped](https://user-images.githubusercontent.com/16904596/96515725-d15b8480-1233-11eb-8771-1b8948861c0c.png)

Comparing the two sets of plots also revealed that the previous 20201012 version displayed too many monitoring sites, but that problem has been rectified in the 20201019 version.  Now waiting for additional testing of the obs overlay feature by CMAQ users before closing this issue.

**Comment by lizadams** [comment]
Do we want to provide an obs dataset and combine dataset along with a script to allow users to test this functionality?  I can extract the O3 variable from the files that you used.  Or we can provide the full data sets on the google drive, and allow folks to download them.

**Comment by yadongxuEPA** [comment]
Tests with the latest 20210222 version of VERDI 2.0 on Linux (Atmos) seem to have fixed the geolocation of the overlaid observations and the issue of color scale display problem (shown above). Below are the (approximately) same plots as above, produced with the VERDI_2.0 20210222 Linux64 version:
![Issue212_VERDI_testing_02232021_2](https://user-images.githubusercontent.com/73186639/108892217-9c927c00-75dd-11eb-9adf-ad34bcfbfdb5.png)
![Issue212_VERDI_testing_02232021_3](https://user-images.githubusercontent.com/73186639/108892259-a916d480-75dd-11eb-883d-709338918268.png)

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1_linux64_20210526.tar.gz and verified that this issue has resolved.
![issue_212_VERDI_testing_plot_2_20210526](https://user-images.githubusercontent.com/73186639/120389660-b76e3e00-c2fa-11eb-8f35-2ade357caae4.jpg)

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1_linux64_20210707.tar.gz, VERDI_2.1_linux64_20210809.tar.gz, and  VERDI_2.1_linux64_20210906.tar.gz, **found that the obs overlay feature was broken**.  The observational data was not displayed at all.
![issue_212_VERDI_testing_1_20210906](https://user-images.githubusercontent.com/73186639/132403761-655b38b0-b86b-4f8d-9840-1f22af01f8b0.jpg)

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1_linux64_20210913.tar.gz, **found a new issue came up that caused the testing could not be completed.  The new issue was that user could not use the features under Configure >> Configure Plot, the following error messages displayed:**
![issue_212_VERDI_testing_2_20210913](https://user-images.githubusercontent.com/73186639/133301611-34940e12-105d-4454-a06d-0395650e4099.jpg)
The obs overlay feature was working, but I was not able to confirm the details because I could not create a customized color map through "Configure Plot":
![issue_212_VERDI_testing_1_20210913](https://user-images.githubusercontent.com/73186639/133301882-4a819199-aba8-4f10-8ec3-5ec964fd9f71.jpg)

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1_linux64_20210914.tar.gz and verified that this issue has resolved.**
![issue_212_VERDI_testing_2_20210914](https://user-images.githubusercontent.com/73186639/133473326-b7c61e18-1d8f-4967-90c0-7ffcff883231.jpg)
![issue_212_VERDI_testing_1_20210914](https://user-images.githubusercontent.com/73186639/133473357-f9a9c6c9-1846-4124-a785-c6f98ba455ed.jpg)
