### ISSUE TITLE
VERDI shapefile export - grid cells shifted to west

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#223]
**Describe the bug**
Exporting LWMASK from 4km domain centered over Long Island shows that the grid cells are shifted to the West and South

**To Reproduce**
1. Download 4km file containing LWMASK variable [GRIDCRO2D_04OTC2_160930.nc](https://drive.google.com/file/d/1nB8xzgg6HwSCxA6xefmSo6UvfcbwBwD8/view?usp=sharing) 
2. Load file into verdi and create tile plot of the LWMASK variable using command 
>verdi.sh -f $cwd/GRIDCRO2D_04OTC2_160930.nc -s "LWMASK[1]" -g tile
3. Download the high resolution background map provided in [USA_States.zip](https://drive.google.com/file/d/1UaQpYk6fSC9NesGCc4AyCskT8RDQRN0N/view?usp=sharing) 
4. Click on GIS Layers> Add Map Layers > Other
5. Navigate to the folder where the USA_States.shp file is located and double click on the USA_States.shp and click open.
6. Zoom in on Block Island, Rhode Island (Island located North East of Long Island) by specifing the columns and rows in the tile plot.  For the VERDI tile plot use the following settings for the Rows and Columns:
Click on Controls > Set Row and Column > Rows: 140 .. 144, Columns 110 .. 115
7. Find the Lat/Lon Value of the upper left grid cell where the LWMASK value is 1 
> Click on Controls > Show Lat/Lon
Hover the mouse over the upper left corner of the grid cell that is colored Red or has a value of 1 and record the lat/lon value displayed in the lower right corner of the Tile Plot
41.1763N, 71.59667W
8. Export the Shapefile by clicking on 
> File > Export as Image/GIS > 
Change Files of Type to Shapefile, and set Filename to record what is being saved
LWMASK_4km_GRIDCRO2D_04OTC2_160930_zoomed_in_Block_Island
I uploaded a tar.gz file that contains the shapefiles:
[LWMASK_4km_GRIDCRO2D_04OTC2_160930_zoomed_in_Block_Island.tar.gz](https://drive.google.com/file/d/1uuNfsR2k7xXi-BKBfrmb5uSAM6jBNdOw/view?usp=sharing)

10. Load the high resolution US_STATES.shp and exported 4km_LWMASK file into QGIS and check the lat/lon value of the grid cell that has LWMASK=1 near Channel Island. VERDI reports the lat/lon value as 41.1763N, 71.59667W 
<img width="753" alt="VERDI_Lat:Lon_Value_of_LWMASK_near_Block_Island" src="https://user-images.githubusercontent.com/1183863/109838310-09c49380-7c14-11eb-8790-dadb378043a1.png">

11. The value in QGIS for the upper left corner of the grid cell near Block Island is 41.1863, 71.6661
<img width="472" alt="QGIS_Lat:Lon_of_LWMASK_from_exported_VERDI_LWMASK_4km" src="https://user-images.githubusercontent.com/1183863/109837845-9884e080-7c13-11eb-8fbb-87b52e2040dc.png">

**Expected behavior**
The shapefile export should have a grid cell with LWMASK=1 over Block Island when loaded to QGIS.

**Version Information :**
 - OS: IOS
 -VERDI 2.0 2021-02-17
 
Link to google drive with relevant files.
https://drive.google.com/drive/folders/1gdI8-_KN1hi-Y9WAhPnUgaBqCRkig2r3?usp=sharing

Header information in the GRIDCRO2D_04OTC2_160930.nc file can be examined using the command:
ncdump -h GRIDCRO2D_04OTC2_160930.nc > GRIDCRO2D_04OTC2_160930.txt
 :GDTYP = 2 ;
                :P_ALP = 33. ;
                :P_BET = 45. ;
                :P_GAM = -97. ;
                :XCENT = -97. ;
                :YCENT = 40. ;
                :XORIG = 1644000. ;
                :YORIG = -144000. ;
                :XCELL = 4000. ;
                :YCELL = 4000. ;
                :VGTYP = 7 ;
                :VGTOP = 5000.f ;
                :VGLVLS = 1.f, 0.9975f ;
                :GDNAM = "04OTC2_CROSS    " ;
                :UPNAM = "OUTGM3IO        " ;

This file contains the LAT/LON Values, So, I should be able to extract only the grid cell that is located over Block Island, and see if the LAT/LON values in the dataset match what VERDI is showing in the Tile Plot, and also what is being exported.
LAT =
  37.17028, 37.16284, 37.15538, 37.14792, 37.14042, 37.13292, 37.12539,
    37.11785, 37.11029, 37.10272, 37.09512, 37.08752, 37.07989, 37.07225,
    37.06459, 37.05691, 37.0492, 37.04149, 37.03376, 37.02602, 37.01826,
    37.01048, 37.00267, 36.99486, 36.98703, 36.97918, 36.97131, 36.96342,
    36.95552, 36.9476, 36.93967, 36.93172, 36.92375, 36.91576, 36.90775,
    36.89973, 36.8917, 36.88364, 36.87557, 36.86749, 36.85937, 36.85126,
    36.84311, 36.83496, 36.82678, 36.81859, 36.81037, 36.80215, 36.79391,

 LON =
  -78.19421, -78.14981, -78.10541, -78.06104, -78.01666, -77.97229,
    -77.92795, -77.88361, -77.83926, -77.79492, -77.75061, -77.7063,
    -77.66199, -77.61771, -77.57343, -77.52914, -77.48486, -77.44061,
    -77.39639, -77.35214, -77.30792, -77.2637, -77.21948, -77.17529,
    -77.1311, -77.08694, -77.04279, -76.9986, -76.95447, -76.91034,

To verify the LAT/LON values in the GRIDCRO2D_04OTC2_160930.nc match the values obtained by using Show Lat/Lon Values in VERDI, I loaded the LAT and LON values, and then used the mouse to show the values for each in a csv format.
<img width="938" alt="VERDI_Tile_Probe_LAT_for_Grid_Cell_Near_Block_Island" src="https://user-images.githubusercontent.com/1183863/109848213-00402900-7c1e-11eb-8d4d-1a62a565f7c6.png">
<img width="964" alt="VERDI_Tile_Probe_LON_LWMASK_GRID_CELL_near_Block_Island" src="https://user-images.githubusercontent.com/1183863/109848229-02a28300-7c1e-11eb-9f27-f2a08f959c8c.png">

Using the Probe, and putting it in the center of each grid, the values seem to match what is reported in the VERDI Tile Probe that was exported. 
Lower Grid Cell Center:
<img width="842" alt="VERDI_Tile_Probe_LAT_LON_Values_Lower_Grid_Cell_Center" src="https://user-images.githubusercontent.com/1183863/109849845-d7b92e80-7c1f-11eb-9cda-8bf19accd52d.png">

Upper Grid Cell Center:
<img width="812" alt="VERDI_GRID_PROBE_GRID_CELL_CENTER_UPPER_GRID_CELl" src="https://user-images.githubusercontent.com/1183863/109849880-e0aa0000-7c1f-11eb-9468-4b930d073da4.png">

**Comment by lizadams** [comment]
LWMASK_4km_GRIDCRO2D_04OTC2_160930_zoomed_in_Block_Island.prj 
contains the following information:

PROJCS["", GEOGCS["Sphere", DATUM["WGS_1984", SPHEROID["WGS 84", 6378137.0, 298.257223563], TOWGS84[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]], PRIMEM["Greenwich", 0.0], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH]], PROJECTION["Lambert_Conformal_Conic_2SP"], PARAMETER["central_meridian", -97.0], PARAMETER["latitude_of_origin", 40.0], PARAMETER["standard_parallel_1", 45.0], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], PARAMETER["scale_factor", 1.0], PARAMETER["standard_parallel_2", 33.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]

**Comment by lizadams** [comment]
This may be related to the different Radius assumptions between MM5 and WRF.
https://gis.stackexchange.com/questions/180004/how-to-transform-wrf-spherical-earth-to-wgs-84
From the above link:

A list of Datum Specifications which can be used in datum transformation and a list of Named Ellipses are available. You may specify the ellipsoid parameters as shown in the following examples:

For the Weather Research and Forecasting Model (WRF) sphere:
   setenv WEIGHT_FILE_WLLIPSOID "+a=6370000.0,+b=6370000.0"

For the Fifth Generation Mesoscale Model (MM5) sphere:
   setenv WEIGHT_FILE_ELLIPSOID "+a=6370993.0,+b=6370993.0"

Our older MCIP data may have been from MM5, and the newer MCIP data is from WRF.
I think we should update the assumption on the radius to WRF, and get rid of older MCIP output from our testing suite.
Or, allow the user to specify the radius of the sphere.

**Comment by lizadams** [comment]
Pehaps this reference will help. https://fabienmaussion.info/2018/01/06/wrf-projection/

**Comment by lizadams** [comment]
Confirmed that the VERDI plot matches the NCL plot of the GRIDCRO2D_04OTC2_160930.nc file, and that the LWMASK covers Block Island.  So the LWMASK correctly identifies land in the area of Block island in both the VERDI Tile Plot, and the NCL Plot.
<img width="1022" alt="Screen Shot 2021-03-05 at 3 28 57 PM" src="https://user-images.githubusercontent.com/1183863/110171119-3a99f980-7dc9-11eb-8d48-0ef104965eeb.png">
The script that I used to creat the ncl plot is attached.
To run the script, I first load the NCAR Graphics module
> module load ncarg
Then source the environment variable file
> source ncl_env.csh
Then run ncl to create the plot
> ncl plot_LWMASK.ncl
The following plot is generated.
NCL_Plot_LWMASK4km_GRIDCRO2D_04OTC2_160930.png
<img width="1022" alt="Screen Shot 2021-03-05 at 3 28 57 PM" src="https://user-images.githubusercontent.com/1183863/110171350-96fd1900-7dc9-11eb-9dc8-264a11a0473b.png">

**Comment by lizadams** [comment]
Extracted the LANDMASK variable from the wrf file, so that I would have a smaller file to work with.
> module load nco
> ncks -v LANDMASK wrfout_d01_2016-09-29_00:00:00 wrfout_d01_2016-09-29_00:00:00.LANDMASK
Loaded the wrfout file into QGIS, goal is to use QGIS to generate a shapfile.

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.0_linux64_20210427.tar.gz, found that the projection string in the exported shapefiles was changed to the followings:
PROJCS["unknown", GEOGCS["GCS_unknown", DATUM["D_unknown", SPHEROID["unknown", 6370000.0, 0.0]], PRIMEM["Greenwich", 0.0], UNIT["degree", 0.017453292519943295], AXIS["Longitude", EAST], AXIS["Latitude", NORTH]], PROJECTION["Lambert_Conformal_Conic"], PARAMETER["central_meridian", -97.0], PARAMETER["latitude_of_origin", 40.0], PARAMETER["standard_parallel_1", 45.0], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], PARAMETER["scale_factor", 1.0], PARAMETER["standard_parallel_2", 33.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]

Loaded the exported shapefiles and "USA_States.shp" into QGIS to verify (as shown in the following map).  
![Capture](https://user-images.githubusercontent.com/73186639/117510262-c19a5800-af59-11eb-8f64-c66fe49c8bef.PNG)
the exported grid cell was not shifted to west anymore and the coordinates for the upper left corner were very close to the ones shown in VERDI.

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1_linux64_20210526.tar.gz, found that the projection string in the exported shapefiles was changed to the followings:
**PROJCS["unknown", GEOGCS["GCS_unknown", DATUM["D_unknown", SPHEROID["unknown", 6370000.0, 0.0]]**, PRIMEM["Greenwich", 0.0], UNIT["degree", 0.017453292519943295], AXIS["Longitude", EAST], AXIS["Latitude", NORTH]], PROJECTION["Lambert_Conformal_Conic"], PARAMETER["central_meridian", -97.0], PARAMETER["latitude_of_origin", 40.0], PARAMETER["standard_parallel_1", 45.0], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], PARAMETER["scale_factor", 1.0], PARAMETER["standard_parallel_2", 33.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]
Loaded the exported shapefiles and "USA_States.shp" into QGIS to verify (as shown in the following map).
![issue_223_VERDI_testing_05262021_in_QGIS_1](https://user-images.githubusercontent.com/73186639/120381960-129b3300-c2f1-11eb-89d9-86bcaf7ece11.png)
the exported grid cell was not shifted to west anymore. This issue has resolved.

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1_linux64_20210626.tar.gz, found that the projection string in the exported shapefiles was changed to the followings:
PROJCS["unknown", GEOGCS["GCS_unknown", DATUM["D_unknown", SPHEROID["unknown", 6370000.0, 0.0]], PRIMEM["Greenwich", 0.0], UNIT["degree", 0.017453292519943295], **AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH]], PROJECTION["Lambert_Conformal_Conic_2SP"]**, PARAMETER["central_meridian", -97.0], PARAMETER["latitude_of_origin", 40.0], PARAMETER["standard_parallel_1", 45.0], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], PARAMETER["scale_factor", 1.0], PARAMETER["standard_parallel_2", 33.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]
Loaded the exported shapefiles and "USA_States.shp" into QGIS to verify (as shown in the following map).
![issue_223_VERDI_testing_06262021_in_QGIS_1](https://user-images.githubusercontent.com/73186639/123851728-8c6f0e00-d8e9-11eb-8f1d-76bb66a4f4a7.png)
**Although the projection string has changed slightly from the previous one, the location of the exported grid cell is accurate.**

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1_linux64_20210906.tar.gz, confirmed that the upgraded openJDK has not caused any problem on this issue.** 
![issue_223_VERDI_testing_20210906_in_QGIS_1](https://user-images.githubusercontent.com/73186639/132565331-6682ddf0-777f-499e-8b3f-3170dcc48c8b.png)
