### ISSUE TITLE
VERDI shapefile export of qv zoomed in to Block Island exports different grid cells than shown in Tile Plot

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#224]
**Describe the bug**
VERDI is able to export a shapfile of the qv variable from the history_qv_only.2016-07-04_00UTC.nc file when the user zooms in to an area that shows Block Island (NE of Long Island), but the grid cells that are exported are not the same grid cells displayed in the VERDI plot at the time of export.

**To Reproduce**
1. Load the file using
> gunzip history_qv_only.2016-07-04_00UTC.nc.gz
> ./verdi.sh -f $cwd/data/model/history_qv_only.2016-07-04_00UTC.nc -s "qv[1]" -g tile
2. Zoom into Block Island off the Coast of Long Island by:
Clicking on the Set Longitude and Latitude Ranges.
Longitude: -72 .. -71
Latitude:      41 .. 42
Show the Cell Borders by using
Click on Controls > Select check box next to [ ] Show Cell Borders
The tile plot should look like the following, note that I clicked on the Center of Block Island to display the lat/lon value there and the qv value.  (-71.577deg, 41.187deg, 7m) qv[8] .0111 kg/kg
<img width="997" alt="Screen Shot 2021-03-03 at 4 54 41 PM" src="https://user-images.githubusercontent.com/1183863/109877576-2f1bc680-7c41-11eb-8cad-f905467630da.png">

4. Then export the shapefile using 
> File> Export as Image/GIS > 
Change Files of Type to : Shapefile
Include the filename mpas_qv_history_qv_only.2016-07-04_00UTC
5. Load the shapefile into QGIS, also load a background map shapefile.
> Layer > Add Layer > Add Vector Layer
Select mpas_qv_history_qv_only.2016-07-04_00UTC.shp
Click on layer, click on properties, change type to Graduated, then Classify Equal Interval
Note, the QGIS plot shows the values of qv including a legend.
<img width="924" alt="QGIS_qv_mpas_verdi_export_zoomed_in_Block_Island" src="https://user-images.githubusercontent.com/1183863/109875498-82404a00-7c3e-11eb-9cb7-c82d03eec65a.png">

To be able to compare between the VERDI plot of the qv variable, and the QGIS plot of the exported shapefile, I then configured the verdi plot to use the same minimum, maximum value, number of bins, and color palette. 
Configure > Configure Plot > Color Map
<img width="598" alt="VERDI_Configure_Plot_qv_mpas_values" src="https://user-images.githubusercontent.com/1183863/109875484-7b193c00-7c3e-11eb-955d-ad86bb6ba396.png">

VERDI Plot that was used to export the Shapefile now looks similar, but not identical to the VERDI plot.

<img width="994" alt="Verdi_qv_mpas_variable_zoomed_in_Block_Island" src="https://user-images.githubusercontent.com/1183863/109876882-4dcd8d80-7c40-11eb-9b3c-8e87b979aa15.png">

In the exported Shapefile, there is no MPAS grid cell over Block Island.
It almost looks like the grid cells that were captured and exported are the ones above Block Island, not the ones surrounding Block Island.  I've numbered the grid cells 1-9 on both the VERDI Plot and the QGIS Plot.  The reason that I think these match up, is that the colors agree. Grid cells 1 and 5 have the highest values for the QV variable in both plots.

<img width="924" alt="QGIS_qv_mpas_verdi_export_zoomed_in_Block_Island" src="https://user-images.githubusercontent.com/1183863/109876777-2a0a4780-7c40-11eb-94e7-942c3bf9b7a8.png">

**Expected behavior**
I expected that the grid cells in the VERDI Tile Plot window, as defined by the Lat/Lon Values specified would be exported to the shapefile.  It appears that the grids that were exported were above Block Island, rather than centered over Block Island.
I would expect that incomplete grid cells would not be exported, but thought that the grid cell that contains Block Island in the VERDI Plot would have been exported.  This could be an "off by 1" indexing problem when VERDI exported the MPAS grid, if the grid cells that should have been exported were just above the Island, rather than over the island.

**Desktop (please complete the following information):**
 - Version: 2.0 2021-02-17

**Comment by lizadams** [comment]
I don't think we can tell what Is going on unless we use very similar background maps in VERDI and in the GIS program.
I used the following: 
Longitude -72 to -71
Latitude 41 to 42
I see the following plot in VERDI as compared to the Shapfile Export.
<img width="1241" alt="Screen Shot 2021-05-12 at 2 55 28 PM" src="https://user-images.githubusercontent.com/1183863/118030213-fed46080-b332-11eb-8630-a60945d3da69.png">

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1_linux64_20210526.tar.gz, tried to set the longitude/latitude as the followings:
Longitude -72 to -71
Latitude 41 to 42
Compared the plot in VERDI to the exported shapefiles in QGIS:
![issue_224_VERDI_testing_05262021_in_QGIS_edited](https://user-images.githubusercontent.com/73186639/120384815-a4f10600-c2f4-11eb-808b-4f1e61d47846.png)
It seems that the geo-referencing is correct. But the clipping process kept more cells than the ones appeared in VERDI plot.
Please review.

**Comment by dschwede** [comment]
I don't think there would be a way to clip out part of a grid cell.  More is probably better than less, in my opinion.  So, I am ok with export all of the cells that are touched by the clip boundary.

**Comment by lizadams** [comment]
Hi all,

I agree. It looks ok to me.

Liz
________________________________

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1_linux64_20210906.tar.gz, confirmed that the upgraded openJDK has not caused any problem on this issue.**
![issue_224_VERDI_testing_20210906_in_QGIS_1](https://user-images.githubusercontent.com/73186639/132565701-ce0df7f5-85d7-4635-9e6a-8a87132d514d.png)
