### ISSUE TITLE
VERDI shapefile export of GRIDCRO2D and GRIDDOT2D variables from 2016_12SE1 mcip output

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#225]
**Describe the bug**
This bug is related to #223, but demonstrates it using different input datasets and Harker's Island in NC as geographic reference point.

**To Reproduce**
1. Load datasets into verdi
verdi.sh -f $cwd/GRIDCRO2D_160702.nc -f $cwd/GRIDDOT2D_160702.nc -s "DLUSE[1]" -g tile -s "LATU[2]" -g tile
2. Zoom into the region over Harker's island for both plots
Click on Controls > Set Row and Column Ranges > Select Rows 59 .. 60, Select Columns 89 .. 89.
3. Use the Externalize this view into a Floating Window to place the plots side by side.
<img width="1160" alt="Screen Shot 2021-03-04 at 11 06 01 AM" src="https://user-images.githubusercontent.com/1183863/109992928-c3396c80-7cd9-11eb-99c0-2fac53de1cca.png">

4. Use File > Export as Image/GIS > 
Select the File Format: Shapefile
Specify the filenames: 
LATU_GRIDDOT2D_160702_zoomed_in_Rows59_60_Col_89_89_island_near_Hatterous
DLUSE_GRIDCRO2D_160702_Zoomed_in_ROW59_60_COL_89_89

5. Load files into QGIS
Layer > Add Vector Layer > Categorize the variable and zoom into layer

<img width="909" alt="QGIS_LATU_GRIDCRO2D_and_LATU_GRIDDOT2D" src="https://user-images.githubusercontent.com/1183863/110001071-f8e25380-7ce1-11eb-9205-d29760822bb9.png">

A zoomed out image in QGIS showing all of the outer banks, and the full extent of both exported grid cells.
<img width="958" alt="QGIS_showing_LATU_GRIDDOT2D_shifted_to_West" src="https://user-images.githubusercontent.com/1183863/110001335-4959b100-7ce2-11eb-96e6-b84b1379e267.png">

**Expected behavior**
The Grid Cell boundary between rows 59 and 60 for the LATU_GRIDDOT2D file should be directly over Harker's Island according to the VERDI Tile Plot Display. The exported shapefile shows this boundary shifted to the West and perhaps a bit  South as well.

 - OS: iOS
 - Version 2.0 2021-02-17

Using QGIS, examining the Properties > Information, the following information including the Extent for each of the files was obtained.

<img width="1047" alt="Screen Shot 2021-03-04 at 12 32 43 PM" src="https://user-images.githubusercontent.com/1183863/110004859-e1a56500-7ce5-11eb-9591-0fbb58ce23d6.png">
<img width="987" alt="Screen Shot 2021-03-04 at 12 32 29 PM" src="https://user-images.githubusercontent.com/1183863/110004861-e23dfb80-7ce5-11eb-9677-000faf600700.png">

**Comment by lizadams** [comment]
I also plotted the LANDMASK variable from the WRF output used to generate the MCIP output.
<img width="1156" alt="Screen Shot 2021-03-04 at 4 10 49 PM" src="https://user-images.githubusercontent.com/1183863/110031043-6c955800-7d04-11eb-925c-a1dba1b89264.png">
<img width="842" alt="Screen Shot 2021-03-04 at 4 10 41 PM" src="https://user-images.githubusercontent.com/1183863/110031046-6d2dee80-7d04-11eb-837d-e5919540cc5e.png">

**Comment by lizadams** [comment]
In the following documentation they mention that the corner_lats and corner_lons global attributes in a WPS-generated GEOGRID file must be known: https://ral.ucar.edu/sites/default/files/public/WRFHydro_GIS_Preprocessor_v5.pdf

"Compatibility of the pre-processing tools with subsetted domainsMany programs such as NCO and NCL will allow a user to subset a 2D netCDF file. However, only files that are generated using the WPS geogrid.exe program may be used as input to the WRF-Hydro ArcGIS Pre-processing tools. This is because the georeferencing of GEOGRID files requires the corner latitude and longitude to be known. This is stored in the ‘corner_lats’ and ‘corner_lons’ global attributes in a WPS-generated  GEOGRID  file.  If  a  user  wishes  to  subset  a  WRF  domain,  they  must  also  update  the values in these attributes in order for the domain to be properly georeferenced."

The ncdump GRIDCRO2D_04OTC2_160930.nc file contains the LAT and LON values a the cell centers.
LON:var_desc = "longitude at cell centers

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1_linux64_20210906.tar.gz, confirmed that the upgraded openJDK has not caused any problem on this issue.** 
![issue_225_VERDI_testing_20210906_in_QGIS_1](https://user-images.githubusercontent.com/73186639/132566256-cf6713be-b9f9-4751-b021-0bd099a84f3e.png)
