### ISSUE TITLE
Found prj string that may work for exporting shapefile from VERDI

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#231]
**Describe the bug**
To address shapefile export issue I used R to export a shapefile of a geo_em.d01.nc file.  Using the *.prj string that it generated:
PROJCS["unknown",GEOGCS["GCS_unknown",DATUM["D_unknown",SPHEROID["unknown",6370000.0,0.0]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-98.0],PARAMETER["Standard_Parallel_1",30.0],PARAMETER["Standard_Parallel_2",60.0],PARAMETER["Latitude_Of_Origin",34.830005645752],UNIT["Meter",1.0]]

I am able to replace that string with what VERDI is using to generate a correctly georeferenced file.  Note, this geo_em.d01.nc file is 30 km, and so it isn't the highest resolution file.  It would be best to get a 4km geo_em* file. But, I think that the projection string is correct, as it is un projected, and doesn't assume a WGS_1984 spheroid, which is what VERDI is currently using.
PROJCS["", GEOGCS["Sphere", DATUM["WGS_1984", SPHEROID["WGS 84", 6378137.0, 298.257223563], TOWGS84[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]], PRIMEM["Greenwich", 0.0], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH]], PROJECTION["Lambert_Conformal_Conic_2SP"], PARAMETER["central_meridian", -98.0], PARAMETER["latitude_of_origin", 34.83000564575195], PARAMETER["standard_parallel_1", 60.0], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], PARAMETER["scale_factor", 1.0], PARAMETER["standard_parallel_2", 30.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]
~         
<img width="980" alt="Screen Shot 2021-03-08 at 10 25 17 PM" src="https://user-images.githubusercontent.com/1183863/110416457-c1690380-8061-11eb-9ae0-eefde006c86f.png">
<img width="494" alt="Screen Shot 2021-03-08 at 10 58 39 PM" src="https://user-images.githubusercontent.com/1183863/110416515-e0679580-8061-11eb-8b92-b2e32612f46d.png">

I have also tested this using the 4km replacing
PROJCS["", GEOGCS["Sphere", DATUM["WGS_1984", SPHEROID["WGS 84", 6378137.0, 298.257223563], TOWGS84[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]], PRIMEM["Greenwich", 0.0], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH]], PROJECTION["Lambert_Conformal_Conic_2SP"], PARAMETER["central_meridian", -97.0], PARAMETER["latitude_of_origin", 40.57356643676758], PARAMETER["standard_parallel_1", 45.0], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], PARAMETER["scale_factor", 1.0], PARAMETER["standard_parallel_2", 33.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]

With

PROJCS["unknown",GEOGCS["GCS_unknown",DATUM["D_unknown",SPHEROID["unknown",6370000.0,0.0]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-97.0],PARAMETER["Standard_Parallel_1",45.0],PARAMETER["Standard_Parallel_2",33.0],PARAMETER["Latitude_Of_Origin",40.57356643676758],UNIT["Meter",1.0]]

And it puts the LANDMASK over Block Island.

<img width="350" alt="Screen Shot 2021-03-08 at 10 47 22 PM" src="https://user-images.githubusercontent.com/1183863/110416361-9a123680-8061-11eb-8f98-f6f1e560b9d2.png">

<img width="964" alt="Screen Shot 2021-03-08 at 11 16 21 PM" src="https://user-images.githubusercontent.com/1183863/110417872-5cfb7380-8064-11eb-8c07-77b596be87cc.png">

To generate the shapefile using R, I used the following tutorial.
https://ral.ucar.edu/sites/default/files/public/geoSpatial.html
and 
the geogrid file found in this tutorial
https://www2.mmm.ucar.edu/wrf/OnLineTutorial/CASES/JAN00/geogrid.php
along with the raster to shapefile tutorial
https://gis.stackexchange.com/questions/332619/r-raster-to-shapefile

**Comment by lizadams** [comment]
Using a 4km geo_em.d03.nc file, I was able to repeat the steps to use R to export the data as a shapefile.
The 4km file is available at this link. 
https://drive.google.com/drive/folders/10AypuLoizaGRGLmJnIe2cy83sS3FaKUj?usp=sharing
QGIS and VERDI now agree on the lat/lon location of the grid cell shown in the following images, located near Cape Lookout, in NC Outer Banks.
<img width="658" alt="Screen Shot 2021-03-09 at 12 05 25 PM" src="https://user-images.githubusercontent.com/1183863/110510052-cd3fde80-80d0-11eb-9d68-fbb12f828094.png">
<img width="913" alt="Screen Shot 2021-03-09 at 12 04 50 PM" src="https://user-images.githubusercontent.com/1183863/110510060-cf09a200-80d0-11eb-9bf5-a2d4b82628d7.png">

**Comment by lizadams** [comment]
I created a shapefile using R for the LANDMASK variable from geo_em.d03.nc and brought it into QGIS using
Add Layer > Add Vector Layer  - this layer is in pink and named geogrid_landmask.shp
Also loaded the high resolution map USA_STATES.shp
Then loaded the shapefile output from VERDI.  This is loaded as LANDMASK_geo_em.d03_zoomed_in_row327_col436.shp and colored orange.  It is almost a full grid cell away from the R generated shapefile.
If I modify the VERDI generated projection
PROJCS["", GEOGCS["Sphere", DATUM["WGS_1984", SPHEROID["WGS 84", 6378137.0, 298.257223563], TOWGS84[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]], PRIMEM["Greenwich", 0.0], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH]], PROJECTION["Lambert_Conformal_Conic_2SP"], PARAMETER["central_meridian", -97.0], PARAMETER["latitude_of_origin", 36.77481460571289], PARAMETER["standard_parallel_1", 45.0], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], PARAMETER["scale_factor", 1.0], PARAMETER["standard_parallel_2", 33.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]

And instead use a modified version of the R generated projection:

PROJCS["unknown",GEOGCS["GCS_unknown",DATUM["D_unknown",SPHEROID["unknown",6370000.0,0.0]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-97.0],PARAMETER["Standard_Parallel_1",45.0],PARAMETER["Standard_Parallel_2",33.0],PARAMETER["Latitude_Of_Origin",36.7748146057],UNIT["Meter",1.0]]
Then re-load the shapefile, I get the purple layer, which is close, but not identical to the R generated shapefile.

<img width="983" alt="Comparison_of_geo_em d03_4km_shapefile_export_near_Cape_Lookout" src="https://user-images.githubusercontent.com/1183863/110513590-658b9280-80d4-11eb-801b-ad18d77863be.png">

**Comment by dschwede** [comment]
Great detective work, Liz.  I think this also raises (again) the issue of what projection should be the default for the shapefile. There seems to be a difference of opinion and I know Byeong Kim (GA DNR) has expressed his opinion.

**Comment by lizadams** [comment]
Here is Byeong Kim's presentation: https://www.cmascenter.org/conference/2009/slides/kim_note_applications_2009.pdf That presentation was prior to CMAQ model change to use the same sphere radius as WRF using radius of 6370000m.

In 2011 Todd Plessel wrote the following in an e-mail to Donna: 
"I could easily modify
verdi_core/src/gov/epa/emvl/GridShapefileWriter.write() method
to accept a boolean argument to choose to
1. Convert computed latitudes to WGS84 and write WGS84 .prj file (current behavior) or
2. Do not convert computed latitudes and write a hard-coded 6370000m sphere .prj file.
The GUI would have to be changed (not as easily?) to expose this choice.
Todd"

**Comment by lizadams** [comment]
This tool may be of assistance.
https://mygeodata.cloud/cs2cs/

**Comment by lizadams** [comment]
Using Tony's latest build: VERDI_2.0_mac_20210327.tar.gz
~                              

Exported the shapefile and obtained the following projection string.
PROJCS["", GEOGCS["Sphere", DATUM["WGS_1984", SPHEROID["WGS 84", 6371000.0, 298.257223563], TOWGS84[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]], PRIMEM["Greenwich", 0.0], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH]], PROJECTION["Lambert_Conformal_Conic_2SP"], PARAMETER["central_meridian", -97.0], PARAMETER["latitude_of_origin", 36.77481460571289], PARAMETER["standard_parallel_1", 45.0], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], PARAMETER["scale_factor", 1.0], PARAMETER["standard_parallel_2", 33.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]

I loaded it into QGIS, and it is not correct.

I modified the prj string to use the sphere instead of spheriod, and it looks correct now.

PROJCS["unknown",GEOGCS["GCS_unknown",DATUM["D_unknown",SPHEROID["unknown",6370000.0,0.0]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.017453292519943295]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-97.0],PARAMETER["Standard_Parallel_1",45.0],PARAMETER["Standard_Parallel_2",33.0],PARAMETER["Latitude_Of_Origin",36.77481460571289],UNIT["Meter",1.0]]

<img width="928" alt="Screen Shot 2021-03-29 at 2 39 36 PM" src="https://user-images.githubusercontent.com/1183863/112884534-9ccedd00-909d-11eb-9cbb-c8cac91d6cf6.png">

Tony, can you try replacing 
PROJCS["", GEOGCS["Sphere", DATUM["WGS_1984", SPHEROID["WGS 84", 6371000.0, 298.257223563], TOWGS84[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]

with

PROJCS["unknown",GEOGCS["GCS_unknown",DATUM["D_unknown",SPHEROID["unknown",6370000.0,0.0]],PRIMEM["Greenwich",0.0]

I think everything else can remain the same.

**Comment by dschwede** [comment]
The info below is similar to the CMAQ link from before, but is written from a WRF perspective.  It might be helpful.  Note that although the date seems old, it was just updated.

https://fabienmaussion.info/2018/01/06/wrf-projection/

They also cite a journal article written on this topic

https://journals.ametsoc.org/view/journals/mwre/141/6/mwr-d-12-00351.1.xml

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.0_linux64_20210427.tar.gz, used input dataset "geo_em.d03.nc" to export a small shapefiles. 
The domain is shown in VERDI as below:
![Issue_231_VERDI_testing_04272021_1](https://user-images.githubusercontent.com/73186639/117195136-ec967780-adb2-11eb-9fb6-b68f7341f94e.png)
The above tile plot then was exported to shapefiles and I noticed that the projection string has changed to the followings:
PROJCS["unknown", GEOGCS["GCS_unknown", DATUM["D_unknown", SPHEROID["unknown", 6370000.0, 0.0]], PRIMEM["Greenwich", 0.0], UNIT["degree", 0.017453292519943295], AXIS["Longitude", EAST], AXIS["Latitude", NORTH]], PROJECTION["Lambert_Conformal_Conic"], PARAMETER["central_meridian", -97.0], PARAMETER["latitude_of_origin", 36.77481460571289], PARAMETER["standard_parallel_1", 45.0], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], PARAMETER["scale_factor", 1.0], PARAMETER["standard_parallel_2", 33.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]].
**To verify the projection accuracy, the shapefiles were loaded into QGIS as below:**
![Issue_231_VERDI_testing_04272021_2](https://user-images.githubusercontent.com/73186639/117195300-223b6080-adb3-11eb-9eb3-297616c546cb.png)
The agreements are very close. The calculated distance between the left lower corner ([34.60953,-76.58295] vs [34.609162, -76.579713]) from these two maps is about 0.3 km.

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1_linux64_20210526.tar.gz, used input dataset "geo_em.d03.nc" to export a small shapefiles.
The domain is shown in VERDI as below:
![Issue_231_VERDI_testing_04272021_1](https://user-images.githubusercontent.com/73186639/120381210-22fede00-c2f0-11eb-8626-dec0e5268cc3.png)
The above tile plot then was exported to shapefiles and the projection string has changed to the followings:
**PROJCS["unknown", GEOGCS["GCS_unknown", DATUM["D_unknown", SPHEROID["unknown", 6370000.0, 0.0]]**, PRIMEM["Greenwich", 0.0], UNIT["degree", 0.017453292519943295], AXIS["Longitude", EAST], AXIS["Latitude", NORTH]], PROJECTION["Lambert_Conformal_Conic"], PARAMETER["central_meridian", -97.0], PARAMETER["latitude_of_origin", 40.0], PARAMETER["standard_parallel_1", 45.0], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], PARAMETER["scale_factor", 1.0], PARAMETER["standard_parallel_2", 33.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]
To verify the projection accuracy, the shapefiles were loaded into QGIS as below:
![issue_231_VERDI_testing_05262021_in_QGIS_1](https://user-images.githubusercontent.com/73186639/120380717-850b1380-c2ef-11eb-91f0-d74ddb625f29.png)
It is consistent with the one shown in VERDI. This issue has resolved.
