### ISSUE TITLE
O3_tileplot_png.txt script doesn't work when subdomain option is used

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#234]
**Describe the bug**
O3_tileplot_png.txt when run in the script editor should produce a tile plot of Layer 1 O3 that covers US.

**To Reproduce**
1. Go to VERDI > File > View Script Editor > Select O3_tileplot_pnt.txt
2. Click Run
3. VERDI will generate a popup window
<img width="876" alt="Screen Shot 2021-03-31 at 12 09 18 AM" src="https://user-images.githubusercontent.com/1183863/113089309-65535400-91b5-11eb-9853-4f9ae8651985.png">

4. Use display to view the tile plot that was generated.
<img width="799" alt="Screen Shot 2021-03-31 at 12 05 44 AM" src="https://user-images.githubusercontent.com/1183863/113089346-79975100-91b5-11eb-9466-919d61412dbe.png">
5. Edit the script to remove the subdomain option
Edit the O3_tileplot_png.txt to remove the subDomain option by commenting it out
#subdomain 20 20 40 50
Then a full tile plot is generated

[CCTM46_P16 baseO2a 36k O3MAX_tile](https://user-images.githubusercontent.com/1183863/113090226-4e156600-91b7-11eb-9d07-d5209c74f046.png)

**Expected behavior**
Expect that the subdomain option would allow you to generate a tile plot that is windowed in to the specified columns and rows.

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.0_linux64_20210427.tar.gz, the issue still persists. "O3_tileplot_png.txt" script did not work when subdomain option was used.  Another issue is that the file path & name in the finished notification was incorrect (it pointed to the wrong sub-directory and wrong file name). Actually the resulted figure was in ../../data/plots/
![Issue_234_VERDI_testing_04272021_2](https://user-images.githubusercontent.com/73186639/116725167-98a12280-a9af-11eb-8455-b53722c86cde.png)
![Issue_234_VERDI_testing_04272021_1](https://user-images.githubusercontent.com/73186639/116725338-cb4b1b00-a9af-11eb-9280-5c64902e0e29.png)

**Comment by lizadams** [comment]
The name in the Finished running batch script file is correct.  It is the name of the batch script, not the name of the png file that is created. 

/Applications/VERDI_2.0/plugins/bootstrap/../../data/scripts/O3_tileplot_png.txt | Wed Apr 28 03:51:20 UTC 2021
-- | --

The name of the PNG file is
/applications/VERDI_2.0/data/plots/CCTM46_P16.baseO2a.36k.O3MAX_tile.png

I do see the same error in the png image that is created that you see, which is likely due to the subdomain option in the O3_tileplot_png.txt script.

#subdomain     -- xmin ymin xmax ymax     
subdomain=20 10 75 50 
You can see the subdomain looks like it may only contain one grid cell, rather than the subdomain that was requested in the script.

**Comment by yadongxuEPA** [comment]
> The name in the Finished running batch script file is correct. It is the name of the batch script, not the name of the png file that is created.
> 
> /Applications/VERDI_2.0/plugins/bootstrap/../../data/scripts/O3_tileplot_png.txt	Wed Apr 28 03:51:20 UTC 2021
> The name of the PNG file is
> /applications/VERDI_2.0/data/plots/CCTM46_P16.baseO2a.36k.O3MAX_tile.png
> 
> I do see the same error in the png image that is created that you see, which is likely due to the subdomain option in the O3_tileplot_png.txt script.
> 
> #subdomain -- xmin ymin xmax ymax
> subdomain=20 10 75 50
> You can see the subdomain looks like it may only contain one grid cell, rather than the subdomain that was requested in the script.

Thanks for your comments, Liz.  You are correct. The file path & name in the notification was for the script itself, not the resulting map.  I will edit my previous comments and remove the false alarm.

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1_linux64_20210906.tar.gz and VERDI_2.1_win64_20210906.zip, confirmed that the upgraded openJDK has not caused any problem on this issue.**
