### ISSUE TITLE
Support VERDI on Windows 8.1

### ISSUE THREAD

**Issue by joellenb** [CEMPD/VERDI#24]
Test VERDI on computers running the 64-bit Windows 8.1 operating system and, if available, the 32-bit Windows 8.1 operating system. Develop installation packages for these systems. Document their capabilities and how to execute VERDI on this operating system.

**Comment by jherwehe** [comment]
Microsoft ended mainstream support for Windows 8.1 on January 9, 2018, and will end extended support (i.e., security patches) on January 10, 2023.  Since most users are running Windows 10 on 64 bit computers these days, there is little to no need to support VERDI on 32- and 64-bit Windows 8.1 PCs.
