### ISSUE TITLE
Shapefile export of Polar Stereographic GRID_CRO2D file

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#241]
**Describe the bug**
Load the following file into VERDI and save it as a shapefile.
Note: this is a MCIP output file with grid resolution of 108 km.  It would be better to have a finer resolution file to work with.
./verdi.sh -f $cwd/data/model/GRIDCRO2D_2006075_polar_stereographic.ncf -s "LWMASK[1]" -g tile

**To Reproduce**
1. Load the file into verdi and create tile plot of LWMASK variable
 ./verdi.sh -f $cwd/data/model/GRIDCRO2D_2006075_polar_stereographic.ncf -s "LWMASK[1]" -g tile
2. Click on File > Export As Image/GIS > 
3. Select File Format: Shapefile (*.shp *.shx *..)
4. Type in a name in the Save As Text Box at the top of the window 
Save As: LWMASK_GRIDCRO2D_2006075_polar_stereographic
5. Load the shapefile into QGIS
6. Layer >  Add Layer > Add Vector Layer
Select Source Dataset: LWMASK_GRIDCRO2D_2006075_polar_stereographic.shp
Click on the layer and edit properties
Change from Simple to Categorized, select Column: LWMASK
Select Categorize
Zoom to map layer

**Expected behavior**
Compare the gridded data to the coastline using the DETAILED_STATES shapefile.

This plot shows the QGIS shapefile has the corner over land.
<img width="1062" alt="Screen Shot 2021-04-01 at 2 51 03 PM" src="https://user-images.githubusercontent.com/1183863/113340450-eae01c80-92f9-11eb-93d1-f8ea74f365b5.png">

**Screenshots**

The projection defined here:
https://github.com/CEMPD/VERDI/blob/75e78ceb7a60a131307cc0aeb07194a76634458a/verdi_data_loaders/src/anl/verdi/loaders/polar_stereographic_wkt.vt
Is used to create the prj string when the shapefile is exported.

PROJCS["WGS 84 / SCAR IMW SU36-40", GEOGCS["WGS 84", DATUM["WGS_1984", SPHEROID["SPHERE", 6371007.0, 0.0]], PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH]], PROJECTION["Polar_Stereographic"], PARAMETER["central_meridian", -98.0], PARAMETER["latitude_of_origin", 90.0], PARAMETER["scale_factor", 0.8535533905932737], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]

This plot shows VERDI with the corner over the intercoastal waterway.
<img width="648" alt="LWMASK_polar_sterographic_verdi" src="https://user-images.githubusercontent.com/1183863/113342033-f5031a80-92fb-11eb-846a-184f62ba72bf.png">

When I modify the PRJ string to use the following:
PROJCS["unknown",GEOGCS["GCS_unknown",DATUM["D_unknown",SPHEROID["unknown",6370000.0,0.0]], PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH]], PROJECTION["Polar_Stereographic"], PARAMETER["central_meridian", -98.0], PARAMETER["latitude_of_origin", 90.0], PARAMETER["scale_factor", 0.8535533905932737], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]

Then reload the file into QGIS, it looks like the corner is located in the correct position.
<img width="1024" alt="LWMASK_polar_stereographic_corrected_prj_QGIS" src="https://user-images.githubusercontent.com/1183863/113342391-6e9b0880-92fc-11eb-9415-5d4271d2000e.png">

I believe the projection string in this file:
https://github.com/CEMPD/VERDI/blob/75e78ceb7a60a131307cc0aeb07194a76634458a/verdi_data_loaders/src/anl/verdi/loaders/polar_stereographic_wkt.vt
Should be modified to use
PROJCS["unknown",GEOGCS["GCS_unknown",
    DATUM["D_unknown",
      SPHEROID["unknown",6370000.0,0.0]]
    PRIMEM["Greenwich",0, AUTHORITY["EPSG","8901"]],
    UNIT["degree", 0.017453292519943295],
    AXIS["Geodetic longitude", EAST],
    AXIS["Geodetic latitude", NORTH]],
  PROJECTION["Polar_Stereographic"],
  PARAMETER["central_meridian", $central_meridian],
  PARAMETER["latitude_of_origin", $lat_origin],
  PARAMETER["scale_factor", $scale],
  PARAMETER["false_easting", 0],
  PARAMETER["false_northing", 0],
  UNIT["m", 1.0],
  AXIS["x", EAST],
  AXIS["y", NORTH]]

That file is used to create the projection string and is called by:
https://github.com/CEMPD/VERDI/blob/75e78ceb7a60a131307cc0aeb07194a76634458a/verdi_data_loaders/src/anl/verdi/loaders/PolarStereographicWKTCreator.java

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.0_linux64_20210427.tar.gz (repeated steps 1-4 as described under "To Reproduce"), found that the projection string for the exported shapefiles is not changed.** 

PROJCS["WGS 84 / SCAR IMW SU36-40", GEOGCS["WGS 84", DATUM["WGS_1984", SPHEROID["SPHERE", 6371007.0, 0.0]], PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH]], PROJECTION["Polar_Stereographic"], PARAMETER["central_meridian", -98.0], PARAMETER["latitude_of_origin", 90.0], PARAMETER["scale_factor", 0.8535533905932737], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1_linux64_20210526.tar.gz, found that the projection string for the exported shapefiles has changed into:
**PROJCS["unknown", GEOGCS["GCS_unknown", DATUM["D_unknown", SPHEROID["unknown", 6370000.0, 0.0]]**, PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH]], **PROJECTION["Polar_Stereographic"]**, PARAMETER["central_meridian", -98.0], PARAMETER["latitude_of_origin", 90.0], PARAMETER["scale_factor", 0.8535533905932737], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1_linux64_20210626.tar.gz, found that the projection string for the exported shapefiles has changed into:
**PROJCS["WGS 84 / SCAR IMW SU36-40", GEOGCS["WGS 84", DATUM["WGS_1984",** SPHEROID["SPHERE", 6370000.0, 0.0]], PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH]], **PROJECTION["Polar_Stereographic"]**, PARAMETER["central_meridian", -98.0], PARAMETER["latitude_of_origin", 90.0], PARAMETER["scale_factor", 0.8535533905932737], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]
Loaded the shapefiles into QGIS and verified the location of the grid corner is still correct.
![issue_241_VERDI_testing_06262021_in_QGIS_1](https://user-images.githubusercontent.com/73186639/123863999-3b1a4b00-d8f8-11eb-8809-0c93309b2dc0.png)
However, "WGS 84" is back to the projection string, should we be concerned ?  Please review.

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1_linux64_20210707.tar.gz, found that "WGS 84" still appeared in the projection string for the exported shapefiles:
**PROJCS["WGS 84 / SCAR IMW SU36-40", GEOGCS["WGS 84", DATUM["WGS_1984",** SPHEROID["SPHERE", 6370000.0, 0.0]], PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH]], **PROJECTION["Polar_Stereographic"]**, PARAMETER["central_meridian", -98.0], PARAMETER["latitude_of_origin", 90.0], PARAMETER["scale_factor", 0.8535533905932737], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1_linux64_20210809.tar.gz, found that "WGS 84" was removed from the projection string for the exported shapefiles:
**PROJCS["unknown", GEOGCS["GCS_unknown", DATUM["D_unknown", SPHEROID["SPHERE", 6370000.0, 0.0]],** PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH]], **PROJECTION["Polar_Stereographic"]**, PARAMETER["central_meridian", -98.0], PARAMETER["latitude_of_origin", 90.0], PARAMETER["scale_factor", 0.8535533905932737], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1_linux64_20210906.tar.gz, confirmed that the upgraded openJDK has not caused any problem on this issue.**
![issue_241_VERDI_testing_20210906_in_QGIS_1](https://user-images.githubusercontent.com/73186639/132585449-dde1f14d-1a5f-4cfa-b9b2-5752aedf57c1.png)
