### ISSUE TITLE
Shapefile Export of GRIDCRO2D_mercator 

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#242]
**Describe the bug**
incorrect prj string causes the gridded data shapefile export to be in incorrect location as compared to background map

**To Reproduce**
1. Load file and variable and create tileplot: verdi.sh -f /applications/VERDI_2.0/data/model/GRIDCRO2D_mercator -s "LWMASK[1]" -g tile
<img width="899" alt="VERDI_LWMASK_GRIDCRO2D_mercator" src="https://user-images.githubusercontent.com/1183863/113346338-b708f500-9301-11eb-8123-cd131119b8e5.png">

2. Export Shapefile: File > Save Export as Image/GIS > 
3. Select File Format : GIS
4. Name file: LWMASK_GRIDCRO2D_mercator
3. examine the projection string used in the newly saved shapefile
4. more  LWMASK_GRIDCRO2D_mercator.prj
It appears to be using the WGS_1984 datum, which is incorrect.
PROJCS["", GEOGCS["Sphere", DATUM["WGS_1984", SPHEROID["WGS 84", 6378137.0, 298.257223563], TOWGS84[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]], PRIMEM["Greenwich", 0.0], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH]], PROJECTION["Mercator_2SP"], PARAMETER["standard_parallel_1", 0.0], PARAMETER["latitude_of_origin", 0.0], PARAMETER["central_meridian", -84.0], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]

Load it into QGIS as a vector layer, and compare to background map, see that it appears to be shifted North as compared to the coastline.
<img width="938" alt="VERDI_Exported_Shapefile_with_incorrect_prj" src="https://user-images.githubusercontent.com/1183863/113346416-d2740000-9301-11eb-945c-db02131457f8.png">

Modified the projection string to use:
PROJCS["unknown",GEOGCS["GCS_unknown",DATUM["D_unknown",SPHEROID["unknown",6370000.0,0.0]], PRIMEM["Greenwich", 0.0], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH]], PROJECTION["Mercator_2SP"], PARAMETER["standard_parallel_1", 0.0], PARAMETER["latitude_of_origin", 0.0], PARAMETER["central_meridian", -84.0], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]

Reloaded the shapefile with the corrected projection string into QGIS
<img width="969" alt="Fixed_prj_VERDI_exported_shapefile" src="https://user-images.githubusercontent.com/1183863/113346555-018a7180-9302-11eb-92d8-0b85ac2c552e.png">

Need to update this code:
https://github.com/CEMPD/VERDI/blob/75e78ceb7a60a131307cc0aeb07194a76634458a/verdi_data_loaders/src/anl/verdi/loaders/mercator_wkt.vt

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.0_linux64_20210427.tar.gz (repeated steps 1-5 as described under "To Reproduce"), found that the projection string for the exported shapefiles is not changed.
PROJCS["", GEOGCS["Sphere", DATUM["WGS_1984", SPHEROID["WGS 84", 6370000.0, 298.257223563], TOWGS84[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]], PRIMEM["Greenwich", 0.0], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH]], PROJECTION["Mercator_2SP"], PARAMETER["standard_parallel_1", 0.0], PARAMETER["latitude_of_origin", 0.0], PARAMETER["central_meridian", -84.0], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]

**Comment by lizadams** [comment]
When I do a search for the string WGS_1984 in the github repository I only see this being used for the MPASShapefileWriter.java 
The only other place where WGS_1984 is found is for the background maps, as those maps do use that Datum.
So, I can't tell where the string is getting written. 
https://github.com/CEMPD/VERDI/search?q=WGS_1984

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1_linux64_20210526.tar.gz, found that the projection string for the exported shapefiles has changed into:
**PROJCS["unknown", GEOGCS["GCS_unknown", DATUM["D_unknown", SPHEROID["unknown", 6370000.0, 0.0]],** PRIMEM["Greenwich", 0.0], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH]], **PROJECTION["Mercator_2SP"]**, PARAMETER["standard_parallel_1", 0.0], PARAMETER["latitude_of_origin", 0.0], PARAMETER["central_meridian", -84.0], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1_linux64_20210626.tar.gz, found that the projection string for the exported shapefiles **is the same** as the ones as the previous 20210526 build. 
PROJCS["unknown", GEOGCS["GCS_unknown", DATUM["D_unknown", SPHEROID["unknown", 6370000.0, 0.0]], PRIMEM["Greenwich", 0.0], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH]], PROJECTION["Mercator_2SP"], PARAMETER["standard_parallel_1", 0.0], PARAMETER["latitude_of_origin", 0.0], PARAMETER["central_meridian", -84.0], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]
Loaded the shapefiles into QGIS and verified the projected locations are consistent with the previous ones.
![issue_242_VERDI_testing_06262021_in_QGIS](https://user-images.githubusercontent.com/73186639/123861890-ae6e8d80-d8f5-11eb-8190-bb9797ab1d7b.png)

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1_linux64_20210906.tar.gz, confirmed that the upgraded openJDK has not caused any problem on this issue.** 
![issue_242_VERDI_testing_20210906_in_QGIS](https://user-images.githubusercontent.com/73186639/132585123-05edb29a-9bd6-4432-ac75-0b5790145820.png)
