### ISSUE TITLE
Java Reflection Error

### ISSUE THREAD

**Issue by cwsimmon** [CEMPD/VERDI#249]
Reported by Russ Bullock

Anytime an item in a file is plotted (any plot) for the first time, a "severe error" results (see example below) and a multitude of java messages are also written to the command prompt window.  Plotting functions still appear to work after this error.

_Jun 15, 2021 3:35:36 PM org.geotools.resources.NIOUtilities log
SEVERE: Error attempting to close a mapped byte buffer : java.nio.DirectByteBuffer
JVM : 15.0.1 Oracle Corporation
java.lang.IllegalAccessException: class org.geotools.resources.NIOUtilities$1 cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @12fcc71f_

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1_linux64_20210914.tar.gz and VERDI_2.1_win64_20210914.zip, verified that the issue has resolved.**
No more error messages popped-up in the command prompt window during plotting.
