### ISSUE TITLE
VERDI fails to load a saved project file

### ISSUE THREAD

**Issue by joellenb** [CEMPD/VERDI#25]
VERDI has the capability to save and load a project file, which is in XML format. When loading a saved file, Java throws a NoClassDefFoundError. But, VERDI is able to successfully save and load a plot configuration file, which is also in XML format.
Fix the bug that prevents VERDI from loading a project file.

**Comment by lizadams** [comment]
Plot configuration xml works - can we switch the methods of handling the project xml file to that used by the plot configuration method and the theme configuration - so that these are all consistent and that they all work.

**Comment by cseppan** [comment]
In commit 1791b21, I updated the Xstream configuration so that the project XML file can be read successfully.
