### ISSUE TITLE
Wind vector striping

### ISSUE THREAD

**Issue by cwsimmon** [CEMPD/VERDI#252]
Reported by Russ Bullock

There was no MPAS model data containing wind vectors included in the software package, so I extracted only the 3-d zonal and meridional wind components from a daily MPAS-A output file (history file) along with the necessary mesh definition data and loaded the resulting file into Verdi.  The wind vector display is showing spurious North/South stripes of vectors just east and west of the Greenwich meridian when the full domain is first displayed.  The stripe to the east is most obvious.  These do not appear on any zoomed or windowed maps, but they reappear with the Max_Zoom_Out command.

**Comment by yadongxuEPA** [comment]
**To Reproduce**
Steps to reproduce the behavior:

1) Load the extracted wind components file "UV_only.2016-07-04.nc" (provided by Russ Bullock) into verdi and create tile plot of "uReconstructMeridional" variable.
2) On the top menu bar, go to Controls, check the box in front of "Show Wind Vectors" in the dropdown menu.

Tested with VERDI_2.1_linux64_20210707.tar.gz and confirmed that there were some North/South wind vector stripes when the map was Max_Zoom_Out.  
![issue_252_VERDI_testing_1_07072021](https://user-images.githubusercontent.com/73186639/126841408-c2f8d421-9689-475b-b2c2-400f8117d167.jpg)

**Comment by lizadams** [comment]
What do the variable names mean?  uReconstructMeridonal and uReconstructZonal?  
Should I add tileplots of both of these variables to the User Manual?
<img width="877" alt="Screen Shot 2021-08-18 at 4 39 44 PM" src="https://user-images.githubusercontent.com/1183863/129969258-f2e0a912-ae96-4b8e-904a-6a9c35378d6c.png">
<img width="881" alt="Screen Shot 2021-08-18 at 4 39 54 PM" src="https://user-images.githubusercontent.com/1183863/129969274-ad57cd04-7438-4fc1-8002-35e2dcdf61b9.png">

**Comment by yadongxuEPA** [comment]
Hi Liz,
I think "uReconstructMeridional" means **meridional wind components** and "uReconstructZonal" means **zonal wind components**.

Yadong

**Comment by lizadams** [comment]
The files for this testing are available on the following google drive.
https://drive.google.com/drive/folders/1ykwOX9h7YwB07bX7fD7wNOmCkLOJPSDb?usp=sharing

There is a large file size limit of 100 M that we can't exceed on github.
The compressed size is 500 M 514M Aug 22 09:06 mpas_UV_only.2016-07-04.nc.gz

the CMAS account currently owns the github/cempd/VERDI account, and we cant use github LFS using a forked account
I am not sure how to use the command line using an account other than my lizadams account.  Need to resolve this issue and see if we can get large files supported under VERDI.

**Comment by lizadams** [comment]
Added instructions on how to download the file from the google drive, and also added two plots demonstrating how to display the wind vectors under this section of the documentation.
https://github.com/CEMPD/VERDI/blob/master/doc/User_Manual/VERDI_ch12.md#mpas-netcdf-data-convention

There is still a line in the middle of the plot when you display the full map, as described above by Russ Bullock and Yadong Xu.

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1_linux64_20211203.tar.gz, the issue has improved, but not completely resolved.**
We can see that the North/South wind vector stripes substantially decreased when max zoom-out, but there were still some stripes left.  
![issue_252_testing_20211203_1_marked](https://user-images.githubusercontent.com/73186639/144926737-b5e8fc88-700a-4490-a4b7-cb92a65cec18.png)
![issue_252_testing_20211203_2](https://user-images.githubusercontent.com/73186639/144926748-5f6254f3-64aa-4603-9b29-4f0ec2d5271d.png)
