### ISSUE TITLE
MPAS data probe location error

### ISSUE THREAD

**Issue by cwsimmon** [CEMPD/VERDI#253]
Reported by Russ Bullock

When a tile plot of MPAS data is open and you plot a time series of probed cells (or bar plot of probed cells), the title and legend on the time series plot indicates the average for the entire domain is being plotted, as it indicates “-180 - 180, -90 - 90” instead of the location of the probe.  For CMAQ and WRF data, the I,J index of the probed cell is indicated correctly.

**Comment by yadongxuEPA** [comment]
Tested with **VERDI_2.1_linux64_20210707.tar.gz** and **VERDI_2.1_win64_20210707.zip** and confirmed that the issue did not appear in the latest 20210707 build. The time series of probed cells and bar plot of the probed cells **did indicate** the correct location.   
![issue_253_VERDI_testing_1_07072021](https://user-images.githubusercontent.com/73186639/125690099-0e5ed473-164d-483a-80ab-18c0514ac9a2.jpg)
![issue_253_VERDI_testing_2_07072021](https://user-images.githubusercontent.com/73186639/125690110-3bf1c6c6-5337-4e6d-9be9-cee16641eb28.jpg)
![issue_253_VERDI_testing_3_07072021](https://user-images.githubusercontent.com/73186639/125690119-7b05dbaa-7d8a-452e-b239-721963120990.jpg)

**Comment by lizadams** [comment]
Confirmed that a probe time series and time series bar plots did confirm the correct locations using the latest mac build.
VERDI_2.1_mac_20210916.tar.gz
