### ISSUE TITLE
User Guide needs information on "show wind vectors" option

### ISSUE THREAD

**Issue by cwsimmon** [CEMPD/VERDI#254]
Reported by Russ Bullock

In the on-line User Guide, I could find no reference to the “show wind vectors” option of the Controls tool for tile plots of MPAS data.  This option does not appear for other model data.  In general, the User Guide does not contain any information relevant for the use of Verdi to work with MPAS model data.

**Comment by lizadams** [comment]
Need to add this option "show wind vectors" to Table 11-1. Tile and Areal Interpolation Plot Pull-down Menu Options in the User Manual.
I will also look at adding an example plot to show this feature.
