### ISSUE TITLE
Error message needed for invalid selection

### ISSUE THREAD

**Issue by cwsimmon** [CEMPD/VERDI#258]
Requested by Russ Bullock

When opening an area file from ../data/hucRegion and selecting an invalid file (not *.shp), clicking “next” results in no action.  The “next” button remains highlighted but there is not indication of an invalid selection.  It would be helpful to new users to have such an indication.

**Comment by lizadams** [comment]
verified that this issue is fixed, and that the "Please select a valid shapefile ending in .shp" error message is displayed using the mac version VERDI_2.1_mac_20210916.tar.gz
