### ISSUE TITLE
Remove unneeded (duplicate) file from distribution package

### ISSUE THREAD

**Issue by cwsimmon** [CEMPD/VERDI#261]
Reported by Russ Bullock

The software distribution contains MPAS water vapor mixing ratio (qv) data files in both uncompressed and compressed (gzip) formats.  One of these could be eliminated to save space.

**Comment by lizadams** [comment]
This duplicate file issue was fixed in the VERDI_2.1_mac_20210809.tar.gz build.
The history_qv_only.2016-07-04_00UTC.nc file is under VERDI_2.1/data/model
The duplicate history_qv_only.2016-07-04_00UTC.nc.gz file has been removed from the build.
