### ISSUE TITLE
User guide formatting edits

### ISSUE THREAD

**Issue by cwsimmon** [CEMPD/VERDI#262]
Reported by Patrick Campbell
* Text has run off the PDF page on Page 17.  
* Text has run off the PDF page on Page 26.  
* Missing Figure reference (“Fig- ??”) on Page 30.
* Reference to Figure 6-8 seems to be a typo on Page 36.
* Text has run off the PDF page on Page 40.
* Text has run off the PDF page on Page 117.

**Comment by lizadams** [comment]
fixed these items in the User Manual, and also updated the VERDI version number (2.1) and release date 08/30/2021 as a placeholder.
Note: we can modify the release date as needed.
There is still something wrong with the figure captions starting with chapter 12, that I need to re-examine.
[VERDIUserManual.pdf](https://github.com/CEMPD/VERDI/files/6927514/VERDIUserManual.pdf)
