### ISSUE TITLE
Increase default Java memory settings

### ISSUE THREAD

**Issue by cwsimmon** [CEMPD/VERDI#263]
Requested by Patrick Campbell
* Needed to increase memory setting to at least 4096M to avoid heap space errors when testing Areal Interpolation Plots using the provide shapefiles.
* Needed to increase memory setting to 2048M to  avoid memory issues when opening MPAS file example provided in VERDI release package

**Comment by yadongxuEPA** [comment]
Confirmed with VERDI_2.1_linux64_20210809.tar.gz and VERDI_2.1_win64_20210809.zip, the default Java memory settings have been increased.
In Windows build, the "JAVACMD" in the "run.bat" file has been updated.
![issue_263_VERDI_testing_2_20210809](https://user-images.githubusercontent.com/73186639/129954605-c8c48453-74c5-4800-a962-e041d5a0325c.jpg)
In Linux build, the "JAVAMAXMEM" in the "verdi.sh" file has been updated. 
![issue_263_VERDI_testing_1_20210809](https://user-images.githubusercontent.com/73186639/129954818-fb4ce132-c56d-478e-bc1a-bde72d6436b6.jpg)

**Comment by lizadams** [comment]
The mac version does not have an updated value.  It needs to be increased to 4096
verdi.command

JAVA=java
JAVAMAXMEM="-Xmx1024M"

**Comment by lizadams** [comment]
Confirmed that this was fixed in the mac build VERDI_2.1_mac_20210916.tar.gz
JAVAMAXMEM="-Xmx4096M"
