### ISSUE TITLE
Warning prompt for overwriting files

### ISSUE THREAD

**Issue by cwsimmon** [CEMPD/VERDI#268]
Requested by Patrick Campbell

I notice that saving a figure as the same name does not prompt a warning, and is in “clobber mode”.  I would suggest having a prompt for the user to confirm they want to overwrite new exported file, rather than clobber mode.

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1_linux64_20210914.tar.gz and VERDI_2.1_win64_20210914.zip, verified that the issue has not resolved.**  When new exported files were saved as the same names as before, there was no prompt message showing up. The files just got overwritten by default.

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1_linux64_20211203.tar.gz, the issue has resolved.**
Tried to save a tile plot in different format, including bmp,jpg,png and shape files, with an existing file name, the prompt message did show up.  
![issue_268_testing_20211203_1](https://user-images.githubusercontent.com/73186639/144924911-e6671ed9-04ba-4594-9d6a-37cf517a3b59.png)
![issue_268_testing_20211203_2](https://user-images.githubusercontent.com/73186639/144924923-7e7cf759-a1dd-4e76-9edb-eaf86bc1dae3.png)
