### ISSUE TITLE
user reported JDK is not 16.0 for Linux

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#291]
**Describe the bug**
User on CMAS Center Forum reported an issue running VERDI 2.1.1.
https://forum.cmascenter.org/t/verdi-2-1-1-linux-gnu-compiler-yellow-screen-only-on-launch-executable-slf4j-binding-messages/2917/4
I couldn't reproduce the issue of only a yellow screen appearing, but was able to confirm the discrepancy in Java versions in the build.

**To Reproduce**
For the Linux Version, it does appear that the java release is 15.0.1.
cd [install_path]/VERDI_2.1.1/jre/bin
./java --version
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9-18)
OpenJDK 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)

For MacOS, the install version is 16.0.2
./java --version
^[[O^[[I^[[O^[[Iopenjdk 16.0.2 2021-07-20
OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7)
OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (build 16.0.2+7, mixed mode)

For WindowsOS, the install version is
openjdk version “16” 2021-03-16
OpenJDK Runtime Environment (build 16+36-2231)
OpenJDK 64-Bit Server VM (build 16+36-2231, mixed mode, sharing)

**Expected behavior**
Expect that all 3 OS builds use a 16 version of Java, consistent with the existing documentation.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Version [2.1.1

**Additional context**

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1.3_linux64_20220210.tar.gz, found that the JDK version has been updated to 16.0.2. This issue has resolved.**
![image](https://user-images.githubusercontent.com/73186639/154546352-cd7f9d98-3f32-4ca3-b091-b75b6d13e489.png)
