### ISSUE TITLE
Variable name length constraint for shapefile export

### ISSUE THREAD

**Issue by dschwede** [CEMPD/VERDI#294]
**Describe the bug**
If a variable name is longer than 10 characters, no data is output to the shapefile on export.

**To Reproduce**
1. Open a file
2. Plot a variable with a name longer than 10 characters or create a new one with a long name and plot it
3. Export the data as a shapefile
4. Examine the exported file to see if it contains the correct data

**Expected behavior**
If the character length must be constrained, an error message should be displayed indicating the export failed and the reason.

**Desktop (please complete the following information):**
 - EPA atmos system - Linux

**Comment by yadongxuEPA** [comment]
Tested with VERDI_2.1.4_linux64_20220323.tar.gz on Atmos, found that this issue has been resolved.  
step 1: loaded model data  "CCTM46_P16.base02a.36k.O3Max" to VERDI
step 2: created a new variable "1000*(NO[1]+NO2[1])" under "Formulas" tab
step 3: generate a tile plot in VERDI, shown as below:
![VERDI_2 1 4_testing_issue_294_2](https://user-images.githubusercontent.com/73186639/165375615-74002769-f330-47c4-9aa1-ce6b39cc170b.png)
step 4: exported the tile plot to shapefiles
step 5: loaded the shapefiles to QGIS, found that the long name was truncated but the data is preserved ( the values are consistent with the ones shown in the tile plot in VERDI)
![issue_294_VERDI_in_QGIS_1](https://user-images.githubusercontent.com/73186639/165375999-cfb8556a-6b98-4dac-b255-f9ba395f50d9.png)
![issue_294_VERDI_in_QGIS_2](https://user-images.githubusercontent.com/73186639/165376019-bd37b194-c9e8-46fb-85dc-f48d653b7ae0.png)

**Comment by cbroker1** [comment]
Tested with VERDI_2.1.4_win64_20220526.zip on Windows 11 machine, and verified export constraint (in Python). 
(followed @yadongxuEPA's test protocol above)

<img width="662" alt="image" src="https://user-images.githubusercontent.com/43118284/171631649-1f79e1dc-7aed-4884-8f95-befb2267f3bf.png">
