### ISSUE TITLE
Task 2.2 Drop the old BIN format along with the shape2bin utility distributed with VERDI

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#3]

**Comment by joellenb** [comment]
Planned for VERDI v1.6. This work in in-process. Manual clipping, projecting, etc. of geographic files are being replaced by GeoTools and NetCDF-Java libraries.

**Comment by lizadams** [comment]
GeoTools has a tutorial and also the following slides:
Slideshow: http://es.slideshare.net/jgarnett/geospatial-for-java
Tutorial: http://docs.geotools.org/latest/userguide/tutorial/

**Comment by joellenb** [comment]
On Shapefiles branch the old files in .bin format (both regular and compressed) and the old shape2bin utility have been removed.
