### ISSUE TITLE
Windows 11 - cannot load t2m_only.nc dataset.

### ISSUE THREAD

**Issue by cbroker1** [CEMPD/VERDI#300]
**Describe the bug**
On my Windows 11 home machine, I cannot load the `t2m_only.nc` dataset, across multiple versions of VERDI. Need a second person to reproduce, to rule out possible issues with home machine.

**To Reproduce**
1. Load VERDI GUI w/`run.bat`
2. Under Datasets, Click on `+` to load local dataset
3. Select `t2m_only.nc` and click Open.
4. 'Wheel of Death' see screenshot for cursor.

**Expected behavior**
I expect the dataset to load, instantly, and populate the `Dataset` and `Variables` fields.

**Screenshots**
(note cursor 'Wheel of Death')
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/43118284/172619309-d703cfee-99f1-4c7b-a92b-c3c7efcf550c.png)

**Desktop (please complete the following information):**
 - Windows 11
 - Version 10.0.22000 Build 22000
 - VERDI: `VERDI_2.1.4_win64_20220526.zip` and `VERDI_2.1.3_win64_20220302.zip`
 - Java: 17.0.2.0

**Closing Thoughts**
@yadongxuEPA did not see this issue w/Windows 10 (tested w/`VERDI_2.1.4_win64_20220526.zip`)

**Comment by lizadams** [comment]
@lizadams tested loading t2m_only.nc dataset using VERDI_2.1.4_win64_20220526.zip on Windows 10 Enterprise and did not see this issue. I was able to load the t2m variable and create a tile plot.
