### ISSUE TITLE
Minor Typo in VERDI About Box

### ISSUE THREAD

**Issue by jherwehe** [CEMPD/VERDI#303]
**Describe the bug**
"Visual" should be changed to "Visualization" in the VERDI About box to match existing documentation.

**To Reproduce**
1. Open VERDI by running verdi.sh
2. Click on 'Help'
3. Click on 'About'
4. See "Visual" (image capture of box provided below)

**Expected behavior**
The About box should say "Visualization" as in Visualization Environment for Rich Data Interpretation (VERDI).

**Screenshots**
![image](https://user-images.githubusercontent.com/16904596/178821764-57d95b59-5689-4655-81b4-e71ab0b4fb2d.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - VERDI Version: 2.1.4 2022-07-06

**Additional context**
This is a very minor cosmetic issue.

**Comment by yadongxuEPA** [comment]
**Retested VERDI_2.1.4_linux64_20220809.tar.gz on Atmos, found that this issue has resolved.**
![VERDI_testing_issue_303_1](https://user-images.githubusercontent.com/73186639/183727359-1efaa617-7ae0-44a5-9287-8e7271ec5f6e.png)
