### ISSUE TITLE
"Configure Plot" control does not work with "Contour Plot"

### ISSUE THREAD

**Issue by yadongxuEPA** [CEMPD/VERDI#304]
**Describe the bug**
When tried to use "Configure Plot" to change or customize color scales, the contour plot did not display the correct color. 

**To Reproduce**

1) Load this file "CCTM_LTNGEMIS3D_WWLLNs_20160701.nc" under /work/MOD3APP/verdi/VERDI_2.1.4_testing_files
2) Create "Contour Plot" for variable "NO[1]"
3) Change to "time step" to 3 and "Layer" to 29, notice that the NO values are quite low at the automatic color scale
![VERDI_testing_issue_299_2_new_data_file](https://user-images.githubusercontent.com/73186639/179847052-4214af5a-8268-48f7-a184-ec03fbc0abba.png)

4) Click on "Configure" >> "Configure Plot" >> "Color Map" and create a customized color scale
![VERDI_testing_issue_299_3_new_data_file](https://user-images.githubusercontent.com/73186639/179847111-3ebc74b0-eafe-4eb9-b076-4447395ca650.png)

**Expected behavior**
The contour plot should display the correct customized color scales.

Desktop (please complete the following information):

EPA atmos system - Linux

**Comment by lizadams** [comment]
Tested using VERDI_2.1.4_mac_20220720.tar.gz

Observed the same behavior as Yadong above.

Uploaded dataset from atmos to the google drive: [CCTM_LTNGEMIS3D_WWLLNs_20160701.nc](https://drive.google.com/file/d/1HWf7EPdNJwjTte2O7m6dDyTvEkBUB_yZ/view?usp=sharing) and downloaded to the VERDI_2.1.4/data/model directory.

A temporary work-around of not being able to set the Min/Max values for the Color Map is to use more Tiles.

```
./verdi.sh -f $cwd/data/model/CCTM_LTNGEMIS3D_WWLLNs_20160701.nc -s "NO[1]" -g contour
```
Select Timestep 3
Select Layer 29
Select Configure > Configure Plot > Color Map
Select Palette by clicking on Newton RGB(AVS) Palette
Selected the Newtown RGB(AVS) Palette, and use the radio button above to change the Number of Tiles to  50.
Then click on Rebuild, then Click on Apply, then Click on OK.

<img width="927" alt="Screen Shot 2022-07-20 at 5 12 10 PM" src="https://user-images.githubusercontent.com/1183863/180083421-588871d6-40b5-43c2-943e-6710022f9d3e.png">


That generated the following plot.
<img width="696" alt="Screen Shot 2022-07-20 at 5 24 17 PM" src="https://user-images.githubusercontent.com/1183863/180084756-dd5be690-099f-4bd3-9938-69483cad0433.png">


<img width="836" alt="Screen Shot 2022-07-20 at 5 12 27 PM" src="https://user-images.githubusercontent.com/1183863/180083472-147cf192-5181-44b1-ab3f-904469fdfc2b.png">

**Comment by yadongxuEPA** [comment]
**Retested VERDI_2.1.4_linux64_20220809.tar.gz on Atmos, found that this issue has partially resolved.**
The contour plot did respond to the changes in the automatic or customized color scales, but it seems the maximum value on the color scale cannot be changed. Note that the maximum value for the color scale stayed at 54.
![VERDI_testing_issue_304_1](https://user-images.githubusercontent.com/73186639/183749439-89b3d27b-5e1e-4878-893f-81c65493dc63.png)
![VERDI_testing_issue_304_2](https://user-images.githubusercontent.com/73186639/183749448-51789e87-f61e-4a58-aa9b-5f7bdf7446b2.png)

**Comment by yadongxuEPA** [comment]
Retested VERDI_2.1.4_linux64_20220823.tar.gz on Atmos, found that "configure plot" function has been improved (the contour plot did respond to the customized color scale and user could set the maximum color value). 
![VERDI_testing_issue_304_retest_2](https://user-images.githubusercontent.com/73186639/186214847-9f6257bd-47c2-4f30-9d3a-772eadfdf294.png)

**However, the following minor issues were found:**

issue 1: the following error messages appeared in VERDI command window as soon as "Contour plot" was clicked.
![VERDI_testing_issue_304_retest_3](https://user-images.githubusercontent.com/73186639/186214518-ad0abe2e-d421-4531-bc48-100bb9d01de2.png)

issue 2: After the dialog window of "configure plot" closed, the previously customized maximum color value was not saved (noticed the max value went back to the default automatic value.  
![VERDI_testing_issue_304_retest_4](https://user-images.githubusercontent.com/73186639/186215783-3118ce95-c8c4-4f55-8a0d-fe7e6900caa9.png)

issue 3: If user want to change the previously customized color values one more time, the contour plot did not respond to the changes. 
![VERDI_testing_issue_304_retest_5](https://user-images.githubusercontent.com/73186639/186216400-4d41e317-c235-4594-8034-1d6b94fb7a1f.png)

**Comment by dkang2** [comment]
In addition to the issues Yadong has pointed out. It would be nice if the vertical axis (the 0-50 range as in the last figure) can be redrawn to match the color legend bar. For example, when the range on the color bar is changed to 0-24, the vertical axis also changes to maximum at 24 (0-24) instead of 0-50. In that way, not only the colors change, but the peaks of the data points also change. Some hidden data that is too small in the larger range should be now visible under a smaller value of maximum customized by user.

**Comment by yadongxuEPA** [comment]
**Retested VERDI_2.1.4_linux64_20220909.tar.gz on Atmos, found that the issue has not resolved.**  The "configure plot" function for the contour plot still behaved the same way as the ones described as in VERDI_2.1.4_linux64_20220823.tar.gz.

**Comment by dkang2** [comment]
I played it a little further with the configuration. Yes, it was resolved the previous issues as Yadong pointed out. But I found another small issue with the configuration file. After the changed configuration was saved in a file, when I brought back the same contour plot and tried to open the saved configuration file, the pop-up window doesn't have a "load" button. Only the "save" button is there. I tested a title plot, it worked well. It should be only a small bug with misplaced button.

**Comment by yadongxuEPA** [comment]
Retested "Load configuration" feature on "Contour plot" with VERDI_2.1.4_linux64_20220925.tar.gz on Atmos, found that loading a saved configuration file worked ok. 

![Screenshot_VERDI_issue_304_config_2](https://user-images.githubusercontent.com/73186639/192337793-612f688e-553f-4c88-844b-b1c0494ea44f.png)

**However, there was the following error messages popped-up in the command window** after I closed the VERDI GUI window.  
![Screenshot_VERDI_issue_304_config_3](https://user-images.githubusercontent.com/73186639/192337837-a06a4cfd-add6-4d3f-8dc5-d55680b1c565.png)

**Comment by lizadams** [comment]
Tested VERDI_2.1.4_mac_20220925.tar.gz on mac.
In examining the contour plot, could modify the min and max values. I didn't see error messages.

I am not really sure that the contour plot is showing what we want to display. Shouldn't the vertical layers be listed along the vertical axis instead of the concentration of NO in moles/sec? I don't really know what this would look like, but I imagine that sometimes there is no concentrations at the lower level, and high concentrations at the upper level, and this is the type of visualization that we need of these files. Would it be possible to see a chemical plume or cloud of NO with a contour plot that had the z axis correspond to vertical layers?

**Comment by yadongxuEPA** [comment]
**Retested VERDI_2.1.4_linux64_20221007.tar.gz on Atmos, confirmed that the issue has resolved.**

**Comment by lizadams** [comment]
Tested using VERDI_2.1.4_mac_20221007.tar.gz and confirmed that the issue was resolved.

**Comment by yadongxuEPA** [comment]
Checked VERDI_2.1.5_linux64_20231222.tar.gz and it worked.

**Comment by lizadams** [comment]
Tested on a mac using VERDI_2.1.5_mac_20240103.tar.gz and found issues to be resolved.
I did not see a message after shutting down the contour plot and then VERDI Gui.

**Comment by yadongxuEPA** [comment]
**Tested VERDI_2.1.5_linux64_20240124.tar.gz on Atmos and found this issue has resolved.**
