### ISSUE TITLE
VERDI legend placement

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#307]
**Describe the bug**

Zac Aldeman submitted the following issue to the CMAS Forum.
https://forum.cmascenter.org/t/verdi-legend-placement/3594/4

I've confirmed the bug on 2.1.3 and 2.1.4. I haven't tried older versions.

**To Reproduce**
1. Download the gridded emissions file for the  CONUS2 domain: https://github.com/lizadams/VERDI/blob/master/verdi_dist/distfiles/data/release/model/emis_mole_all_20151222_12US2_nobeis_norwc_2016fh_16j.CO.ncf
Note, this file is not exactly the same as what Zac used, so the units are not the same. The domain is the same.
3. Run the following script 
./verdi.command -f ~/downloads/emis_mole_all_20151222_12US2_nobeis_norwc_2016fh_16j.CO.ncf -s "CO[1]" -titleString "Daily Total Emissions:CO" -subTitle1 "Grid: 12US2 - Simulation: LADCO_2016d" -subTitle2 "Inventory Sector: nonpt" -g tile -saveImage "png" ~/downloads/emissions.CO.png -quit
4. Note, the legend gets moved to the size due to the length and font size of the Title String, and the number of subTitles.
5. If you remove -subTitle2, then the legend looks ok.
6. This also happens when you add these titles and subtitles to the GUI using configure 

**Expected behavior**
Titles and Subtitles can be added without impacting the position of the legend on the tile plot.

**Screenshots**
Plot with Title and 2 subtitles.
![emissions CO](https://user-images.githubusercontent.com/1183863/192632702-e705e48d-ceeb-434e-8a20-7ef40908e0d2.png)

Plot with Title and only 1 subtitle.
![emissions CO onesubtitle](https://user-images.githubusercontent.com/1183863/192632829-e9a427e3-179d-4319-8903-b6c079feaae6.png)

**Desktop (please complete the following information):**
 - OS: mac

 - Version: 2.1.4 and 2.1.3

**Additional context**

**Comment by yadongxuEPA** [comment]
**Retested VERDI_2.1.4_linux64_20220930.tar.gz on Atmos, found that the issue has resolved.** 
![image](https://user-images.githubusercontent.com/73186639/193628651-444f461e-eaf4-4306-b192-0829044491a2.png)
![Screenshot_VERDI_issue_307_1](https://user-images.githubusercontent.com/73186639/193628764-e26791ec-2642-4dc3-893a-996dd63c8e18.png)

**Comment by yadongxuEPA** [comment]
**Retested VERDI_2.1.4_linux64_20221007.tar.gz on Atmos, confirmed that the issue has resolved.**

**Comment by yadongxuEPA** [comment]
Checked VERDI_2.1.5_linux64_20231222.tar.gz on Atmos and it worked.

**Comment by lizadams** [comment]
Checked VERDI_2.1.5_mac_20240103.tar.gz on mac and it worked.
