### ISSUE TITLE
Opening MPAS mesh file with an error

### ISSUE THREAD

**Issue by dkang2** [CEMPD/VERDI#324]
**Describe the bug**
An MPAS mesh file in netcdf format can't be opened

**To Reproduce**
1. verdi -f /work/MOD3DEV/dkj/MPAS/data/x1.2621442.grid.nc
2. The following error window pops up and verdi freezes:
**Screenshots**
<img width="649" alt="image" src="https://github.com/CEMPD/VERDI/assets/15109047/7cf6f070-e73b-40de-98e3-a8e9bcf31298">

**Desktop (please complete the following information):**
 - OS: Linux (on EPA Atmos)

**Additional context**

**Comment by dkang2** [comment]
This new feature works very well and it has achieved the desired results.

<img width="476" alt="image" src="https://github.com/CEMPD/VERDI/assets/15109047/5fdb9ae5-2c1d-43f3-aad8-7444ba50a89a">

**Comment by yadongxuEPA** [comment]
**Retested VERDI 2.1.4 20230924 builds on Atmos, confirmed that the new feature of displaying MPAS mesh structure works well.**

![Github_issue_324_meshStructure](https://github.com/CEMPD/VERDI/assets/73186639/f296f881-f676-4ca8-a3ab-7e23348886e5)

**Comment by yadongxuEPA** [comment]
**Retested VERDI 2.1.4 20231012 builds on Atmos, confirmed that the new feature of displaying MPAS mesh structure works well.**

**Comment by lizadams** [comment]
I added a small mesh file to the github branch but, when I went to visualize it I couldn't see the mesh.
<img width="1762" alt="Screen Shot 2023-11-01 at 9 57 47 AM" src="https://github.com/CEMPD/VERDI/assets/1183863/e48f7368-d238-43ff-a195-8cbf3286bcd3">

Is there a pull down menu option that I need to set to visualize it, or do I need to zoom into some region to find a mesh definition?

I know that the x1.2621442.nc file is too large to put in the VERDI distribution on github, so the file that Daewen had shared with me was much smaller, x1.40962.grid.nc.

netcdf x1.40962.grid {
dimensions:
	nCells = 40962 ;
	nEdges = 122880 ;
	nVertices = 81920 ;
	maxEdges = 10 ;
	maxEdges2 = 20 ;
	TWO = 2 ;
	vertexDegree = 3 ;
	nVertLevels = 1 ;
	Time = UNLIMITED ; // (0 currently)


[x1.40962.grid.nc.tar.gz](https://drive.google.com/file/d/1ra-Rwkuc-l8ERg-Xza-ridARNq4dE8Ph/view?usp=drive_link)

File that has been used above for testing
[x1.2621442.tar](https://drive.google.com/file/d/1ZjtKIzuQgRsRTnaOTKtoFjlFiwAUf4LC/view?usp=drive_link)

**Comment by lizadams** [comment]
I figured it out, the user needs to use the pull down menu option
Tile Plot > Controls > Show Cell 
<img width="1226" alt="VERDI_mesh_structure_plot" src="https://github.com/CEMPD/VERDI/assets/1183863/0da46079-e4f4-45bf-89b5-12159e72d280">
Borders


I will add this to the documentation.

**Comment by dkang2** [comment]
Thanks, Liz, for doing all these updates. It is in a very good shape to have the VERDIv2.1.5 release.

**Comment by yadongxuEPA** [comment]
Checked VERDI_2.1.5_linux64_20231222.tar.gz on Atmos and it worked.

**Comment by lizadams** [comment]
Using VERDI_2.1.5_mac_20240103.tar.gz

Tried using the CLI option to create a tile plot using the meshStructure variable, and it failed. 

This works in the GUI. Using the GUI, after creating the tile plot, I was able to select Controls>Show Cell Borders, and then zoom in to see the mesh structure.

Error message from the command line option:

 ./verdi.command -f $cwd/data/model/x1.40962.grid.nc -s "meshStructure[1]" -g tile
in netcdfdataset.java openDataset 1 arguments
in netcdfdataset.java openDataset 3 arguments
in netcdfdataset.java ready to return openDataset 5 arguments
2024.01.04 18:34:52.250 [main] ERROR anl.verdi.commandline.ScriptHandler - Error in ScriptHandler.dataMap.put 'G'
java.lang.NullPointerException: Cannot invoke "anl.verdi.data.DataFrameAxis.getOrigin()" because the return value of "anl.verdi.data.Axes.getTimeAxis()" is null
	at anl.verdi.commandline.ScriptHandler$14.run(ScriptHandler.java:579) [core.jar:?]
	at anl.verdi.commandline.ScriptHandler.handleOptions(ScriptHandler.java:1525) [core.jar:?]
	at anl.verdi.commandline.ScriptHandler.run(ScriptHandler.java:167) [core.jar:?]
	at anl.verdi.core.VerdiPlugin.run(VerdiPlugin.java:168) [core.jar:?]
	at saf.core.runtime.CorePlugin.runApplicationRunnable(CorePlugin.java:93) [saf.core.runtime.jar:?]
	at saf.core.runtime.CorePlugin.run(CorePlugin.java:48) [saf.core.runtime.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at saf.core.runtime.Boot.run(Boot.java:178) [saf.core.runtime.jar:?]
	at saf.core.runtime.Boot.main(Boot.java:388) [saf.core.runtime.jar:?]

**Comment by yadongxuEPA** [comment]
Checked VERDI_2.1.5_linux64_20240103.tar.gz on Atmos with command line and got the same error:
 
![image](https://github.com/CEMPD/VERDI/assets/73186639/056675c8-7169-4cf0-99e7-29c6145662b8)

**Comment by yadongxuEPA** [comment]
Additional re-test also done on VERDI_2.1.4_linux64_20231013.tar.gz (before Java update) on Atmos with command line and got the same error:
![image](https://github.com/CEMPD/VERDI/assets/73186639/c766f32c-3411-4268-99c1-b2628a3b3730)

**Comment by lizadams** [comment]
Testing after Tony's build of VERDI_2.1.5_mac_20240124.tar.gz

```
cd /Users/lizadams/downloads/VERDI_2.1.5_01_24
./verdi.command -f $cwd/../x1.40962.grid.nc -s "meshStructure[1]" -g tile

```

Output:

```
in netcdfdataset.java openDataset 1 arguments
in netcdfdataset.java openDataset 3 arguments
in netcdfdataset.java ready to return openDataset 5 arguments
```

Then in the GUI selected Control > Show Cell Borders

Saved screenshot showing successful display of the mesh structure.

<img width="1901" alt="Screen Shot 2024-01-25 at 10 58 04 AM" src="https://github.com/CEMPD/VERDI/assets/1183863/d2f50424-69ed-4fb4-8229-6b8806511df0">

This test was successful

**Comment by yadongxuEPA** [comment]
**Checked VERDI_2.1.5_linux64_20240124.tar.gz on Atmos with command line and confirmed that this issue has resolved.**
