### ISSUE TITLE
Support sub-domain on a Vertical Cross Section Plot

### ISSUE THREAD

**Issue by yadongxuEPA** [CEMPD/VERDI#326]
**Is your feature request related to a problem? Please describe.**
Yes, this issue was first reported on CMAS forum by a user under this link
https://forum.cmascenter.org/t/verdi-cross-section-plot-in-script/4156/3

I confirmed this issue using the command line described as below and got the same error:
![image](https://github.com/CEMPD/VERDI/assets/73186639/abe92716-1a57-4a7d-877d-86acbb98b296)

**Describe the solution you'd like**
Add "subDomain" as one of the argument options for "verticalCrossPlot".  Just like what we have for a tile plot.
See the example as below:
![image](https://github.com/CEMPD/VERDI/assets/73186639/e2e1d86e-c67e-4a82-a99b-e0b26dc82fe1)

![image](https://github.com/CEMPD/VERDI/assets/73186639/bf3d14b3-5ddc-4408-b151-2506f4bb412d)

**Comment by lizadams** [comment]
Another issue on this has been posted to the CMAS Center Forum.
https://forum.cmascenter.org/t/how-can-i-use-subdomain-command-for-crossplot-in-verdi/4299

**Comment by yadongxuEPA** [comment]
**Retested VERDI 2.1.4 20230831 builds on Atmos, found that this issue has improved, but not fully resolved yet.** 
1) the error messages are more clearer now if user chose a row number is lower than the minimum Y set after "-subDomain"
![issue_326_vertical_cross_section_in_script_error_message](https://github.com/CEMPD/VERDI/assets/73186639/37a622a8-54aa-48d5-9b27-b6a8bd42503c)
2) When user chose a correct row number. For example, "Y 70" as shown below, somehow, VERDI loaded a vertical cross section plot at "row 31" 
![image](https://github.com/CEMPD/VERDI/assets/73186639/b12cfaa6-c715-48e7-ad8d-3b5339a00154)
![issue_326_vertical_cross_section_in_script_Y_70_commandline](https://github.com/CEMPD/VERDI/assets/73186639/6bc8c7ae-c58a-4c74-aa98-e2c9e43e843e)
3) Tried to use the following script by set the row number to 70, surprisingly the saved vertical cross section plot went to "row 31". 
![image](https://github.com/CEMPD/VERDI/assets/73186639/b264460c-69e8-4d87-b180-c3a0855f8075)
![issue_326_vertical_cross_section_in_script_Y_70](https://github.com/CEMPD/VERDI/assets/73186639/06c81af0-6497-479c-90ce-8977dabdbef7)
**Users actually want the saved image only display the vertical cross plot between the columns set between "Xmin" and "Xmax", in this example, it should be between 20-60 on X-axis instead of 1-141.**

**Comment by yadongxuEPA** [comment]
**Retested VERDI 2.1.4 20230911 builds on Atmos, found that this issue has not resolved**, we still have the same issues with the 20230831 builds as described above.

**Comment by yadongxuEPA** [comment]
**Retested VERDI 2.1.4 20230924 builds on Atmos, confirmed that this issue has resolved.**
Tested two ways with "-subDomain":
1) in command line: ./verdi.sh -f /work/MOD3APP/yxu/VERDI_2.1.4/data/model/CCTM46_P16.baseO2a.36k.O3MAX -s "O3[1]" -subDomain 20 40 60 80 -verticalCrossPlot Y 70
![Github_issue_326_command_line](https://github.com/CEMPD/VERDI/assets/73186639/a5a202cf-923f-428b-a9c7-f6a83d449252)
2) in a script:
![image](https://github.com/CEMPD/VERDI/assets/73186639/46c88404-9219-4e75-8a7b-3684dc6d4914)
![Github_issue_326_in_script](https://github.com/CEMPD/VERDI/assets/73186639/92e153a3-2368-4209-a331-b7b2b2f9b225)

**Comment by yadongxuEPA** [comment]
Retested VERDI 2.1.4 20231012 builds on Atmos, confirmed that this issue has resolved.

**Comment by yadongxuEPA** [comment]
Checked VERDI_2.1.5_linux64_20231222.tar.gz on Atmos and it worked.

**Comment by lizadams** [comment]
Tested using VERDI_2.1.5_mac_20240103.tar.gz

 ./verdi.sh -f $cwd/data/model/CCTM46_P16.baseO2a.36k.O3MAX -s "O3[1]" -subDomain 20 40 60 80 -verticalCrossPlot Y 70

The vertical cross section plot was successfully created.

**Comment by lizadams** [comment]
Re-tested using VERDI_2.1.5_mac_20240124.tar.gz, vertical cross section plot was successfully created

**Comment by yadongxuEPA** [comment]
**Checked VERDI 2.1.5 20240124 builds on Atmos, confirmed that it worked.**
