### ISSUE TITLE
High Priority: Update Java in VERDI to Java SE 17.0.8 or greater

### ISSUE THREAD

**Issue by jherwehe** [CEMPD/VERDI#330]
**Describe the bug**
High Priority:  A Java security vulnerability has been identified in VERDI by ORD/OSIM via a NESSUS scan on my Linux workstation.  They have told me that **Java should be updated to Java SE 17.0.8 or greater**, or I need to delete VERDI from my workstation.  Here is the Java version in the recent 20231013 build of VERDI 2.1.4:

[jherwehe@d2626ut7920g ~/verdi/VERDI_2.1.4.20231013/jre/bin]$ ./java --version
java 17.0.2 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing

This Java update needs to be completed before releasing VERDI 2.1.5.

**To Reproduce**
Steps to reproduce the above Java version report:
1. Go to the ./jre/bin directory under any installed version of VERDI.
2. Type './java --version' to see the above Java version output.

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by yadongxuEPA** [comment]
Java has been updated in 20231222 builds
![image](https://github.com/CEMPD/VERDI/assets/73186639/e0f25303-ada4-4885-8908-e70f4c9b4efa)

**Comment by dkang2** [comment]
Confirmed.

**Comment by lizadams** [comment]
using VERDI_2.1.5_mac_20240103.tar.gz
Confirmed that I am seeing the same java version on the mac.
cd VERDI_2.1.5/jre/Contents/Home/bin
./java --version
java 21.0.1 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)
