### ISSUE TITLE
replace JAI with JAI-EXT

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#34]
Evaluate JAI-EXT.
Note: they are using MAVEN to build
http://www.geo-solutions.it/blog/developers-corner-jai-ext-the-open-source-replacement-for-oracle-jai/

**Comment by joellenb** [comment]
The only VERDI code that imports from com.sun.media is in verdi_core: anl/verdi/plot/io/TIFConvert.java. All other com.sun.media imports are within the org/geotiff/image/jai or the org/libtiff/jai java code. The version of the jai libraries in VERDI are still from 2006.
Prior to changing the library, other libraries used by VERDI need to be checked for any dependencies on the JAI libraries.
