### ISSUE TITLE
Shapefiles: redesign manner in which the components of the FastTilePlot are arranged and displayed

### ISSUE THREAD

**Issue by joellenb** [CEMPD/VERDI#40]
The following graphic illustrates how VERDI's Fast Tile Plot currently lays out its components.
https://www.draw.io/#G0Byc9bjXZNTDdb05HZzlvVWx5R2c
Each group of components is shown in its own rectangular box. Currently the colored box represents how the legend, axes, and tiles themselves are all grouped into one Rectangle2D object on the VERDI screen. Note that the box in the center ("Tiles") contains the actual colored grid cells.

The goal of this section of the project is to overlay the tiles with shapefiles, either those included with the VERDI distribution or a shapefile provided by the user. However, the current generation of this chart in VERDI appears to be incompatible with how GeoTools draws a shapefile.

VERDI reads gridded data from a NetCDF data file, extracts the data to be displayed based on grid cell, time step, layer, and parameter, and then converts the geographic coordinates in the data file to (x,y) screen coordinates in a Rectangle2D object for display. These data, as well as the legend, axes, and related tics and labels, are all loaded into a single widget (colored rectangle on the above sketch) for display in VERDI.

GeoTools, on the other hand, reads and displays shapefiles in many different geographic projections and converts all shapefiles to be displayed together into a common projection. The shapefile is then displayed into something like that shown here:

http://docs.geotools.org/stable/userguide/_images/jmapframe1.jpg

Note that, except for the frame title and two widget bars, GeoTools uses the entire frame to display the shapefile in the selected geographic projection. There appears to be a fundamental difference between how VERDI draws georeferenced data (in an x,y rectangle in units of display) and how GeoTools draws georeferenced data (in a geographic projection).

In order to successfully draw shapefiles onto the tiles, the "Tiles" portion of the VERDI screen must be extracted from the current widget configuration and changed to a GeoTools mapping widget. Also, the data read from the NetCDF file need to be maintained in georeferenced form (i.e., not be translated to [x,y] screen coordinates).

NOTE: The following steps have already been completed.
1. Open the standard shapefiles distributed with VERDI.
2. Present a file chooser widget for the user to select any shapefile for use in VERDI.
3. Open, read, and determine the extents and projection of each shapefile.
4. Determine the projection of the data in the NetCDF data file.
5. Define the translator to reproject the shapefile data to the projection of the data file.

**Comment by joellenb** [comment]
Steps involved in changing the layout of the Fast Tile Plot to be compatible with rendering shapefiles:
1. Determine the name of the class of each of the major components of the Fast Tile Plot pane.
2. Determine where in the VERDI source code the class is instantiated and populated with data.
3. Locate how VERDI assembles the instance of each of those classes and determine the required path and functions to get to the completed object from the Fast Tile Plot when preparing for rendering.
4. Retain the existing code for opening and reading the data from a NetCDF data file. The goal is to use the existing data structure within VERDI while retaining all geographic information.
5. Identify which objects go into which rectangles (shown in sketch above).
6. Design a new object (JPanel) with a new layout (GridBagLayout) manager such that the box labeled "Tiles" will not be bound with the legend and axes widgets.
7. Construct the replacement "Tiles" rectangle as a GeoTools object (JMapPane) to hold both the grid cells and the shapefiles.

Goals include:
1. Retain object names and links to configuration data.
2. Continue to support graphic output formats currently used to save the Fast Tile Plot as an image file.
3. Construct the GridBagLayout such that, when the user resizes the screen, the lengths of the axes match the respective sides of the plot itself.

**Comment by lizadams** [comment]
County Shapefiles are loading slowly, as may be expected due to the large filesize 113M for the Census Tiger Boundary shapefile tl_2015_us_county.shp.  Here is a plot that shows the high concentrations of ozone for timestep 22 for the CCTM46_P16* file.
![ozone_tstep_22_cctm46_p16](https://cloud.githubusercontent.com/assets/1183863/14023410/96626306-f1ba-11e5-8375-fdd817426a79.png)
