### ISSUE TITLE
NullPointerException error when try to add USA Counties to tile plot

### ISSUE THREAD

**Issue by joellenb** [CEMPD/VERDI#48]
at anl.verdi.plot.gui.VerdiBoundaries.draw(VerdiBoundaries.java:128)
at gov.epa.emvl.Mapper.draw(Mapper.java:137)
at anl.verdi.plot.gui.FastTilePlot$5.run(FastTilePlot.java:614)
Thread

Pulled latest code today (4/1/2016). On Windows started VERDI from command window. Selected CCTM46_... dataset, O3(ppmV)[1] variable, moved to Time Step 20, Layer 3.
selected GIS Layers/Add Map Layer/USA States
zoomed into NE US
selected GIS Layers/Add Map Layer/USA Counties
Above error was thrown. Cursor on VERDI still in "wait" cursor.

**Comment by joellenb** [comment]
Tried again starting as a clean run. Using same dataset and variable. Advanced to time step 2, still layer 1, no zooming or panning.
selected GIS Layers/Add Map Layer/USA States
selected GIS Layers/Add Map Layer/USA Counties
Exact same error with same line numbers as above, so zooming did not affect this behavior.

**Comment by cseppan** [comment]
I'm guessing this is due to not having the full county shapes file loaded from Git LFS. See issue #54 for info on how to get the full file.
