### ISSUE TITLE
NullPointerException error when try to Edit Layer; simple style; fill color

### ISSUE THREAD

**Issue by joellenb** [CEMPD/VERDI#49]
Started new VERDI session. Selected CCTM46... dataset, O3 (ppmV)[1] variable. Did not change time step or layer.
Selected GIS Layers/Configure GIS Layers. (NOTE: only GIS layer is default North America map)
Highlighted the only layer in the Manage Layers box. Selected Edit Layer button.
Brought up Edit Style box. Stayed in the default Simple Style tab. clicked on the red box for the Fill Color. Brought up box Select a Fill Color. Clicked the top-left color (white). Clicked OK.
Errors thrown. 
Edit Layer box Fill Color now shows a white box. Clicking the Finish button throws errors but does not do anything with the Edit Layer box or on the tile plot map. Have to click the Cancel button to return back to the Configure GIS Layers box.
![editstyle_chgfillcolor_04012016](https://cloud.githubusercontent.com/assets/10145737/14218747/2876621e-f824-11e5-9485-61df173b4331.PNG)

**Comment by cseppan** [comment]
For now, I've disabled the Add Layer and Edit Layer buttons in the Configure GIS Layer interface.

**Comment by lizadams** [comment]
Tested using VERDI_2.0_beta_linux64_20190623.tar.gz
still see that the Add Layer and Edit Layer button are disabled (greyed out), even after selecting a layer.

<img width="1195" alt="Screen Shot 2019-06-25 at 2 10 11 PM" src="https://user-images.githubusercontent.com/1183863/60122372-0c8a9800-9753-11e9-8f7b-82fee7f30e50.png">
You can add layers from the 
GIS Layers > Add Map Layers 
Then use the Move Up or Move Down option for the layers, but it isn't clear if that does anything
Configure GIS Layers > Manage Layers > Move Up 
The Remove Layer option works
Configure GIS Layers > Manage Layers > Remove Layer
