### ISSUE TITLE
Task 2.5: Replace binary map files with similar Shapefiles

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#5]
Shapefile replacements are available on killdevil. Google spreadsheet for more information: 
https://docs.google.com/spreadsheets/d/1ArdI1a5arUFFh_NCGXmpg4EPDyX95HDaqWEFud3YSAI/edit?usp=sharing

**Comment by joellenb** [comment]
For VERDI 1.6 binary files for county boundaries, etc. have been removed from the VERDI distribution and Shapefiles have been added.
