### ISSUE TITLE
World boundaries do not match North America, States

### ISSUE THREAD

**Issue by joellenb** [CEMPD/VERDI#52]
The country boundaries in the World map do not align with the North America, States, HUC boundaries. Need to investigate this or get an updated version of the World map. Here is example zoomed in to Pacific northwestern states.
![worldmapboundaries_donotlineup_04012016](https://cloud.githubusercontent.com/assets/10145737/14220824/91e429d2-f830-11e5-8ce3-769e0ef51c32.PNG)

**Comment by cseppan** [comment]
I fixed the inconsistent datum and ellipsoid in the map_world shapefile. Now the various GIS layers are aligning properly. Here's the world map and North American layers:

![world_na_alignment](https://cloud.githubusercontent.com/assets/7329179/14649907/2ce3d5a4-0637-11e6-8ec4-7b0f08a7e43e.png)
