### ISSUE TITLE
color ramp issue

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#55]
Reported by Russ Bullock - April 5, 2016

The displayed min/max in FastTilePlot basically calls out the extremes in the plot being viewed at the time.  Just that window of the horizontal domain, just that layer, and just that timestep.

But the color map (a.k.a. legend) for the tile plot is based on the extremes of the entire data set when the plot is first rendered.  Then the user can edit the plot configuration or read in a stored config.

By the way, one of the biggest issues I've had with Verdi is that when you change the color for a particular contour interval, and then make any additional modifications, like alter the contour values, the colors revert back to the default for the type of color map you chose in the first place.  I can see why it would do that if you pick a color map with a different number of contour intervals.  But if all you want to do is change the range of the contour values, why not leave the colors alone?

**Comment by lizadams** [comment]
Reported by Tony Howard - April 8, 2016

I see the colormap issue.  I also notice that when I click one of the other colormaps and then go back to the original, any edits are lost.
But once I customize an interval, those are kept regardless of what I do in the dialog.  If I customize a color map, choose a different one, then go back to the first, I would like to see my customization kept.

It might be nice if they kept any customization to the colormap as long as the dialog remains open - if I rebuild the intervals, change and then return to a colormap, etc, the changes would remain.  Users will still want a way to reset colors (and probably intervals too), so maybe they could shrink the Reverse button and add a button beside it to reset all values to defaults.

**Comment by lizadams** [comment]
Reported by Donna Schwede - April 8, 2016
BTW ... the option under "control" to set the col/row range to view works on the linux version but not on the Windows version

**Comment by joellenb** [comment]
Donna Schwede's comment about the "control" to set the col/row range to view is working on the Windows version.

**Comment by lizadams** [comment]
using VERDI_2.0_beta_linux64_20190623.tar.gz
```
#!/bin/csh -f

#script for testing command line options

echo 'running verdi_script.csh'

foreach species ( O3 )
./verdi.sh \
         -f $cwd/data/model/CCTM46_P16.baseO2a.36k.O3MAX \
          -configFile $verdi_dir/data/configs/10bin_new_config \
         -titleString "CMAQv46 ${species} Layer 1" \
         -s "${species}[1]" \
         -g tile \
         -saveImage "jpg" $verdi_dir/test.$species.png \
 #         -quit
 end
```
Verified that the user can change the color map without loosing their settings for the min and max values.
The user can also use the Control > set Column and Row Ranges to specify what subdomain to plot.
<img width="770" alt="Screen Shot 2019-06-25 at 11 21 00 AM" src="https://user-images.githubusercontent.com/1183863/60111211-8ca50380-973b-11e9-8cd2-b3d1d3b265bb.png">
<img width="1177" alt="Screen Shot 2019-06-25 at 11 20 13 AM" src="https://user-images.githubusercontent.com/1183863/60111212-8ca50380-973b-11e9-8fbd-7520a39419de.png">
