### ISSUE TITLE
Configure footer issues Time Series, Time Series Bar, and Scatter Plot

### ISSUE THREAD

**Issue by joellenb** [CEMPD/VERDI#59]
Configure/Configure Plot/Labels/Footer
There are blocks for Line One and Line Two, each with a Show Text checkbox, Text, Font, and Color inputs. Default state is for Show Text boxes to be unchecked.
Checking a Show Text box allows the user to enter a Text and to pick a Font and a Color. However, neither the Apply nor the OK button displays the footer at the bottom of the plot.

**Comment by lizadams** [comment]
Testing with VERDI_2.1_mac_20211206.tar.gz, I was able to add a test label to the Domain Axis, Range Axis, Footer
The text added to the labels was retained even when I changed the timestep.
Marking this bug as fixed.
