### ISSUE TITLE
areal interpolation plot compared to QGIS - boundaries not lining up correctly in VERDI

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#61]
![areal_o3_huc8_nc](https://cloud.githubusercontent.com/assets/1183863/14467363/fcecaf6c-00a8-11e6-87f1-d01480c9b006.png)
![qgis_huc08_nc_state_boundary](https://cloud.githubusercontent.com/assets/1183863/14467474/7e4877bc-00a9-11e6-9119-c5acc20558b5.png)
Note: when I save the areal interpolation plot as an exported shapefile and then bring it into QGIS, then the huc08 lines are drawn over the existing wbdhuc8 data, so there isn't an issue with the shapefile export.
There is only an issue with how the data is being displayed in VERDI on the Areal interpolation plot.
It may be an issue with incorrectly drawing the data when you zoom in?

**Comment by cseppan** [comment]
The areal interpolation code (both the calculations and display) is still using the ucar.unidata.geoloc.Projection class to deal with different coordinate reference systems. This library doesn't handle datum shifting / ellipsoid changes. The sample HUC shapefile was using the WGS84 datum, which doesn't match the perfect sphere assumed for input datasets, so the display in Verdi was shifted (and the underlying grid-to-area calculations would have been slightly off).

I updated the sample HUC shapefile with a reprojected version using the perfect sphere datum. This fixes the calculation and display issue.

A top priority once more time is available will be to switch the areal interpolation code to use GeoTools, which can handle ellipsoid changes. For now, the release notes need to include the known limitation that for areal interpolation, the selected shapefile needs to use degrees for units (not meters), and should use the datum 
DATUM["unknown", SPHEROID["SPHERE", 6370000.0, 0.0], TOWGS84[0, 0, 0]]

**Comment by systemsgo** [comment]
The areal interpolation code is now using GeoTools and the projections should line up.

**Comment by lizadams** [comment]
The huc boundaries in the areal interpolation plot are correctly lined up with the state boundaries. 
![dryox_n_basecase dat_areal_interp](https://cloud.githubusercontent.com/assets/1183863/17142536/78850ad0-531e-11e6-9420-2d3fdbde1a3f.png)
The figure below matches the Areal Plot: Area Totals figure in the VERDI user manual.
![dryox_n_areal_interp_area_totals](https://cloud.githubusercontent.com/assets/1183863/17142691/098d09b0-531f-11e6-9651-0364a2a2f467.png)
