### ISSUE TITLE
area information table should reflect values for the timestep viewed in the areal interpolation plot

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#62]
to export data to a shapefile from a different timestep depends on the information table having the correct data.

![areal_inter_o3_huc08_colorado_timestep1 val_ 03499](https://cloud.githubusercontent.com/assets/1183863/14470716/1b4ad9b0-00b9-11e6-8d05-5d50beda3013.png)
![areal_inter_o3_huc08_colorado_timestep13 val_ 0246](https://cloud.githubusercontent.com/assets/1183863/14470718/1b4e9672-00b9-11e6-9382-a90c298bd850.png)
![area_spreadsheet__area_10180002_o3_huc08_colorado_timestep13 val](https://cloud.githubusercontent.com/assets/1183863/14470717/1b4d0104-00b9-11e6-9164-34056d80951b.png)

**Comment by joellenb** [comment]
NOTE: Issue is for time step and layer, not solely time step.

**Comment by cseppan** [comment]
Issue is fixed by commit 79a6222f9275745a3f522a43aab2b56c582be7c5.
