### ISSUE TITLE
GIS layer display doesn't wrap around

### ISSUE THREAD

**Issue by cseppan** [CEMPD/VERDI#64]
Example using world_NOX_latlon.ncf dataset:

<img width="1548" alt="world_nox_latlon" src="https://cloud.githubusercontent.com/assets/7329179/14589452/87e6480c-04b0-11e6-8122-2faed05c6703.png">

**Comment by lizadams** [comment]
This has been fixed as of VERDI_2.0_beta_linux64_20190623.tar.gz
verified using the following script
```
#!/bin/csh -f

#script for testing command line options

echo 'running verdi_script_world.csh'

foreach species ( NOX )
./verdi.sh \
         -f $cwd/data/model/world_NOX_latlon.ncf \
         -s "${species}[1]" \
         -g tile \
 end
```
<img width="1183" alt="Screen Shot 2019-06-25 at 11 15 47 AM" src="https://user-images.githubusercontent.com/1183863/60110794-ac87f780-973a-11e9-83ce-49d339eabdde.png">
