### ISSUE TITLE
Problem with Areal interpolation calculations. Check if polygons intersect grid cells

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#71]
Loading file CCTM46_P16_baseO2a.36k.O3MAX with variable O3[1] and areas file huc03.shp and asking for an areal interpolation plot and am getting a textbox warning "Problem with Areal interpolation calculations. Check if polygons intersect grid cells".
![screenshot_verdi_1 6 0_alpha_areal_interpolation_issue](https://cloud.githubusercontent.com/assets/1183863/14718488/f4cf3066-07c4-11e6-9c97-33157e91380a.png)
I don't think that there should be an issue in this case as the dataset loaded has gridded data over the region where the huc03 file is located.  The Areal Interpolation Plot was created and I could see the results of the areal interpolation in the Area Information Spreadsheet.

**Comment by systemsgo** [comment]
Fixed in shapefile_mpas
