### ISSUE TITLE
VERDI unit testing

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#77]
Donna has asked in the past about unit testing of VERDI.  I took a look in Eclipse and found
under verdi_core there is a test directory and a Pave_Tests.launch script

The **Pave_Tests.launch** relied on a pave_core project that didn't exist so I changed it to verdi_core
I tried to run it, and obtained a no tests found with test runner Junit 4.
I then added the test project to the verdi_core build path using:
project -> Java build path -> Source -> add the test folder
![verdi_add_test_folder_to_build_path](https://cloud.githubusercontent.com/assets/1183863/14894064/d7afa274-0d3f-11e6-90cf-6137f3cdcff3.png)

I've renamed Pave Tests.launch to Verdi Test.launch
To run the unit tests in eclipse right click on **Verdi Test.launch**, Select **Run As**, Select **Verdi Test** (note there is a J Unit Symbol next to Verdi Test.
![verdi_run_unit_test](https://cloud.githubusercontent.com/assets/1183863/14893923/3c3f777e-0d3f-11e6-9e4f-3bad3a2e69f6.png)

The unit tests ran with the results shown in the following image:
![verdi_unit_test_result](https://cloud.githubusercontent.com/assets/1183863/14893667/4707257c-0d3e-11e6-886f-e6bafcd5a349.png)
For the failed tests, you can see the results of the stack trace by clicking on them. (see in the image above that the failed test that is highlighted has it's stack trace on the right hand side.)

**Comment by Chiakiyang** [comment]
Hi,May I ask you a question about VERDI? I am writing the shell script to get plots and I don't know how to specify the layer height by script. Does VERDI support the layer height definition by scripts?

**Comment by lizadams** [comment]
Hi Chiakiyang,

To view the command line options use the following from the directory where VERDI is installed.
./verdi.sh  -help
Or if on a mac
./verdi.command -help

I was able to use the -layer option to specify VERDI to create a plot for the 3rd layer in the file and save it as a GIF image.
The order of the commands may be important, ie. You need to specify the variable name prior to the layer, and the type of plot you would like to save after both.

verdi.sh -f "./METCRO3D_CMAS-Training" -s TA[1] -layer 3 -g tile -saveImage "GIF" ./METCRO_TA_layer3.gif

Thanks,
Liz

Elizabeth Adams
Research Associate, Institute for the Environment
University of North Carolina, Chapel Hill
http://www.ie.unc.edu/cempd
100 Europa Drive
Suite 490, Room 4045, CB 1105
Chapel Hill, NC 27517
voice: 919-843-0518
cell: 919-678-1513

**Comment by Chiakiyang** [comment]
Hi Liz,
I am using VERDI_1.5.0. It seems that the  -layer option is replaced by -level option.
