### ISSUE TITLE
check location of help files

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#79]
There seemed to be two locations for the help documentation. 
core/help
bootstrap/help
We need to edit the XML files used when building VERDI to use the same location as we are using in  the HELP Dialog, so that we no longer have two locations.

**Comment by joellenb** [comment]
When I tried to get rid of core/help completely, the build or run-time windowing system failed. My solution was to put a dummy text file into core/help. Build, run-time, and Git all work now.
