### ISSUE TITLE
Animate Plots: time steps in dialog box different from in plots

### ISSUE THREAD

**Issue by joellenb** [CEMPD/VERDI#83]
Animating 2 plots at the same time using the Plots menu of the main VERDI window. Set the time steps to be 10-22, times 10:00 to 22:00. Time steps in plots show 11-23, times 10:00 to 22:00.
![animate2plots_05212016](https://cloud.githubusercontent.com/assets/10145737/15451049/b270b7b8-1f7e-11e6-987a-185142135be5.PNG)

**Comment by lizadams** [comment]
using VERDI_2.0_beta_linux64_20190623.tar.gz
test using the following script
```
#!/bin/csh -f
#script for testing command line options
echo 'running verdi_script.csh'

foreach species ( O3 )
./verdi.sh \
         -f $cwd/data/model/CCTM46_P16.baseO2a.36k.O3MAX \
          -configFile $cwd/data/configs/10bin_new_config \
         -titleString "CMAQv46 ${species} Layer 1" \
         -s "${species}[1]" \
         -g tile \
         -saveImage "jpg" $cwd/test.$species.png \
 #         -quit
 end
```
adding the NOX variable, undocking both plots, then placing them side by side.
<br>


Selecting the animate plots
<br>
Specify the starting timestep as 10, and the ending timestep as 15 for the animation:
<br>
VERDI starts with timestep 11 and ends with timestep 16

image of the starting timestep:
<img width="1224" alt="Screen Shot 2019-06-25 at 3 03 32 PM" src="https://user-images.githubusercontent.com/1183863/60126232-845cc080-975b-11e9-9bd0-9c197e3b2483.png">


image of the ending timestep:
<img width="1239" alt="Screen Shot 2019-06-25 at 3 02 49 PM" src="https://user-images.githubusercontent.com/1183863/60126141-54152200-975b-11e9-8d18-474560d60652.png">

**Comment by jherwehe** [comment]
Working with the 20190623 version of VERDI_2.0_beta (this problem exists on all platforms):  VERDI's Time Step spinner above the plot starts counting time steps at 1 (like a Fortran-based array) as one would expect.  But the Animate Plots dialogue box Starting Time Step spinner starts counting at 0 (like a C-based array), which is unnatural to most users.

Fix the coding for the Starting Time Step in the Animate Plots dialogue box to initially begin at 1 by default (do likewise for the Ending Time Step spinner).

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1_linux64_20211203.tar.gz, the issue has resolved.**  
Tested animating 2 plots at the same time using the Plots menu of the main VERDI window, found that the time steps displayed in both plots were consistent with the ones in the Animate Plots dialogue box. 
![issue_83_testing_20211203_1](https://user-images.githubusercontent.com/73186639/144927735-a01de368-8223-4282-a41c-3489937721bc.png)
