### ISSUE TITLE
error when loading mpas file x1.642.grid.nc

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#85]
contents of file  ~lizadams/verdi/verdi.log after trying to load file from the website: 
https://people.sc.fsu.edu/~jburkardt/data/netcdf_mpas/netcdf_mpas.html

It looks like VERDI is tries load the file using the spreadsheet loader and throws and error before it gets to load it using the MPAS loader.

5803 12:33:56.680 [AWT-EventQueue-0] DEBUG anl.verdi.core.VerdiApplication - in VerdiApplication.loadDataset
5804 12:33:56.681 [AWT-EventQueue-0] DEBUG anl.verdi.core.Project - in Project getDatasetAsList
5805 12:33:56.681 [AWT-EventQueue-0] DEBUG anl.verdi.gui.DatasetListModel - in DatasetListModel elements
5806 12:33:56.681 [AWT-EventQueue-0] DEBUG org.java.plugin.standard.StandardPluginClassLoader - loadClass: trying local class guess, name=
     anl.verdi.loaders.SpreadsheetReader, this={PluginClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}
5807 12:33:56.683 [AWT-EventQueue-0] DEBUG org.java.plugin.standard.StandardPluginClassLoader - loadLocalClass: found class, class=class a     nl.verdi.loaders.SpreadsheetReader, this={PluginClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}, r     equestor={PluginClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}
5808 12:33:56.683 [AWT-EventQueue-0] DEBUG org.java.plugin.standard.StandardPluginClassLoader - loadClass: local class guess succeeds, nam     e=anl.verdi.loaders.SpreadsheetReader, this={PluginClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}
5809 12:33:56.683 [AWT-EventQueue-0] DEBUG org.java.plugin.standard.StandardPluginClassLoader - loadPluginClass: trying plug-in guess, nam     e=anl.verdi.data.Dataset, this={PluginClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}, requestor={     PluginClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}
5810 12:33:56.683 [AWT-EventQueue-0] DEBUG org.java.plugin.standard.StandardPluginClassLoader - loadLocalClass: found loaded class, class=     interface anl.verdi.data.Dataset, this={PluginClassLoader: uid=1259014228; {PluginDescriptor: uid=anl.verdi@1.0.0}}, requestor={Plugi     nClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}
5811 12:33:56.683 [AWT-EventQueue-0] DEBUG org.java.plugin.standard.StandardPluginClassLoader - loadPluginClass: plug-in guess succeeds, n     ame=anl.verdi.data.Dataset, this={PluginClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}, requestor     ={PluginClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}
5812 12:33:56.684 [AWT-EventQueue-0] DEBUG org.java.plugin.standard.StandardPluginClassLoader - loadPluginClass: trying plug-in guess, nam     e=anl.verdi.data.Variable, this={PluginClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}, requestor=     {PluginClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}
5813 12:33:56.685 [AWT-EventQueue-0] DEBUG org.java.plugin.standard.StandardPluginClassLoader - loadLocalClass: found class, class=interfa     ce anl.verdi.data.Variable, this={PluginClassLoader: uid=1259014228; {PluginDescriptor: uid=anl.verdi@1.0.0}}, requestor={PluginClass     Loader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}
5814 12:33:56.685 [AWT-EventQueue-0] DEBUG org.java.plugin.standard.StandardPluginClassLoader - loadPluginClass: plug-in guess succeeds, n     ame=anl.verdi.data.Variable, this={PluginClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}, requesto     r={PluginClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}
5815 12:33:56.688 [AWT-EventQueue-0] DEBUG org.java.plugin.standard.StandardPluginClassLoader - loadPluginClass: trying plug-in guess, nam     e=anl.verdi.data.BoundingBoxer, this={PluginClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}, reque     stor={PluginClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}
5816 12:33:56.689 [AWT-EventQueue-0] DEBUG org.java.plugin.standard.StandardPluginClassLoader - loadLocalClass: found class, class=interfa     ce anl.verdi.data.BoundingBoxer, this={PluginClassLoader: uid=1259014228; {PluginDescriptor: uid=anl.verdi@1.0.0}}, requestor={Plugin     ClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}
5817 12:33:56.689 [AWT-EventQueue-0] DEBUG org.java.plugin.standard.StandardPluginClassLoader - loadPluginClass: plug-in guess succeeds, n     ame=anl.verdi.data.BoundingBoxer, this={PluginClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}, req     uestor={PluginClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}
5818 12:33:56.692 [AWT-EventQueue-0] DEBUG org.java.plugin.standard.StandardPluginClassLoader - loadClass: trying local class guess, name=     anl.verdi.loaders.SpreadsheetReader, this={PluginClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}
5819 12:33:56.692 [AWT-EventQueue-0] DEBUG org.java.plugin.standard.StandardPluginClassLoader - loadLocalClass: found loaded class, class=     class anl.verdi.loaders.SpreadsheetReader, this={PluginClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0     .0}}, requestor={PluginClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}
5820 12:33:56.692 [AWT-EventQueue-0] DEBUG org.java.plugin.standard.StandardPluginClassLoader - loadClass: local class guess succeeds, nam     e=anl.verdi.loaders.SpreadsheetReader, this={PluginClassLoader: uid=1930837320; {PluginDescriptor: uid=anl.verdi.data.loaders@1.0.0}}
5821 12:33:56.689 [AWT-EventQueue-0] DEBUG anl.verdi.loaders.SpreadsheetLoader - Could not load data file
5822 java.lang.Exception: Number of columns are less than required!
5823         at anl.verdi.loaders.SpreadsheetReader.validateHeaderAndGetTimezone(SpreadsheetReader.java:55) ~[bin/:?]
5824         at anl.verdi.loaders.SpreadsheetLoader.canHandle(SpreadsheetLoader.java:43) [bin/:?]
5825         at anl.verdi.data.DataManager.createDatasets(DataManager.java:102) [bin/:?]
5826         at anl.verdi.core.VerdiApplication.loadDataset(VerdiApplication.java:584) [bin/:?]
5827         at anl.verdi.core.VerdiApplication.addDataset(VerdiApplication.java:644) [bin/:?]
5828         at anl.verdi.core.VerdiAppConfigurator$1.actionPerformed(VerdiAppConfigurator.java:67) [bin/:?]
5829         at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [?:1.8.0_60]
5830         at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) [?:1.8.0_60]
5831         at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [?:1.8.0_60]
5832         at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [?:1.8.0_60]
5833         at javax.swing.AbstractButton.doClick(AbstractButton.java:376) [?:1.8.0_60]
5834         at javax.swing.AbstractButton.doClick(AbstractButton.java:356) [?:1.8.0_60]
5835         at anl.verdi.gui.DataSetPanel$1.actionPerformed(DataSetPanel.java:194) [bin/:?]
5836         at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [?:1.8.0_60]
5837         at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) [?:1.8.0_60]
5838         at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [?:1.8.0_60]
5839         at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [?:1.8.0_60]
5840         at javax.swing.AbstractButton.doClick(AbstractButton.java:376) [?:1.8.0_60]
5841         at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833) [?:1.8.0_60]
5842         at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157) [?:1.8.0_60]
5843         at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877) [?:1.8.0_60]
5844         at java.awt.Component.processMouseEvent(Component.java:6535) [?:1.8.0_60]
5845         at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [?:1.8.0_60]
5846         at java.awt.Component.processEvent(Component.java:6300) [?:1.8.0_60]
5847         at java.awt.Container.processEvent(Container.java:2236) [?:1.8.0_60]
5848         at java.awt.Component.dispatchEventImpl(Component.java:4891) [?:1.8.0_60]
5849         at java.awt.Container.dispatchEventImpl(Container.java:2294) [?:1.8.0_60]
5850         at java.awt.Component.dispatchEvent(Component.java:4713) [?:1.8.0_60]
5851         at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) [?:1.8.0_60]
5852         at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) [?:1.8.0_60]
5853         at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) [?:1.8.0_60]
5854         at java.awt.Container.dispatchEventImpl(Container.java:2280) [?:1.8.0_60]
5855         at java.awt.Window.dispatchEventImpl(Window.java:2750) [?:1.8.0_60]
5856         at java.awt.Component.dispatchEvent(Component.java:4713) [?:1.8.0_60]
5857         at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_60]
5858         at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_60]
5859         at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_60]
5860         at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_60]
5861         at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_60]
5862         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [?:1.8.0_60]
5863         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [?:1.8.0_60]
5864         at java.awt.EventQueue$4.run(EventQueue.java:731) [?:1.8.0_60]
5865         at java.awt.EventQueue$4.run(EventQueue.java:729) [?:1.8.0_60]
5866         at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_60]
5867         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [?:1.8.0_60]
5868         at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_60]
5869         at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_60]
5870         at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_60]
5871         at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_60]
5872         at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_60]
5873         at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_60]
5874         at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_60]
5875 12:33:56.819 [AWT-EventQueue-0] DEBUG ucar.nc2.NetcdfFile - Using IOSP ucar.nc2.iosp.netcdf3.N3raf
5876 12:33:56.893 [AWT-EventQueue-0] DEBUG ucar.nc2.NetcdfFile - Using IOSP ucar.nc2.iosp.netcdf3.N3raf
5877 12:33:56.899 [AWT-EventQueue-0] DEBUG ucar.nc2.NetcdfFile - Using IOSP ucar.nc2.iosp.netcdf3.N3raf
5878 12:33:56.901 [AWT-EventQueue-0] DEBUG ucar.nc2.NetcdfFile - Using IOSP ucar.nc2.iosp.netcdf3.N3raf
5879 12:33:56.902 [AWT-EventQueue-0] DEBUG ucar.nc2.NetcdfFile - Using IOSP ucar.nc2.iosp.netcdf3.N3raf
5880 12:33:56.904 [AWT-EventQueue-0] DEBUG ucar.nc2.NetcdfFile - Using IOSP ucar.nc2.iosp.netcdf3.N3raf

**Comment by systemsgo** [comment]
While these aren't strictly MPAS files - they don't have the Convention=MPAS attribute, they're pretty much the same as an MPAS file, so I added support for them.  Be aware that they only have the grid info, so you won't see any actual data in the values.  It may still be useful to visualize the grid.
