### ISSUE TITLE
States and North America boundaries not matching on areal interpolation plot

### ISSUE THREAD

**Issue by joellenb** [CEMPD/VERDI#88]
I created an areal interpolation plot using the state boundaries shapefile as the polygon overlay layer. I noticed that the state boundaries that are in both the files are not matching. I zoomed in to see the boundaries better. When I made the window float, the widgets at the top of the frame also were not matching with the ones from the prior layer/time step:
![arealinterpstates_overlayoff_06062016](https://cloud.githubusercontent.com/assets/10145737/15836394/a987f20c-2c02-11e6-8457-74d567a60db3.PNG)

When I created the Tile Plot and then added the States as a GIS overlay, the boundaries match. Here is a zoomed in screenshot of that chart as a floating window:
![tileplot_wstatebndryoverlay_06062016](https://cloud.githubusercontent.com/assets/10145737/15836476/00b64790-2c03-11e6-97a0-1971db18a873.PNG)

**Comment by lizadams** [comment]
The areal interpolation shapefile of the state boundaries is lined up correctly in the areal interpolation plot.
![areal_inter_state_shapefile](https://cloud.githubusercontent.com/assets/1183863/17141714/37411b98-531b-11e6-8806-d20cf2dc9c0b.png)
