### ISSUE TITLE
numeric values on color map scale not working after merge

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#90]
1. Issue description – when I tried to change the numeric values on the color scale and hit apply the    intervals it created were not in line with the min and max I had set.  See the figure below.
2. Platform: I have now been able to replicate it on Linux and Windows.
3. VERDI distribution name: VERDI distribution – alpha1.6 6-15 version
4. Filename : METCRO2D_110515 (uploaded to Science FTP site) 
- [ ] Liz will place this test file on github under VERDI/verdi_dist/distfiles/data/test - under the shapefile_mpas branch, after this has been tested locally.
1. Variable: HFX
2. Plot type: Tile plot

Steps followed:
1. Open Configure Plot Dialog Box, Select the Color Map Tab
2. Change numeric values on color scale 
3. Click the rebuild button
4. If you can't see the rebuild button
5. Hover over a corner of the Configure Plot Dialog Box, when you see the double pointed arrow, click and drag to widen it
6. Once you see the rebuild button, click on it.
7. Once you click on the rebuild button it should show the new interval start and stop values in the Configure Plot Dialog Box (below the rebuild button)
8. Click the apply button  (this will apply the new interval start and stop values to the tile plot)

Additional Note from Donna:
 I used the same file with version 1.5 and did not have the problem and neither did the 1.6_alpha  from before the merge.  It is interesting that this doesn’t happen with all files.  I tried one of the deposition files and the re-scaling worked fine.
![color_map_values](https://cloud.githubusercontent.com/assets/1183863/16268660/40f01b40-385d-11e6-985a-6f18eac4ecea.jpeg)

**Comment by joellenb** [comment]
I tried to load the 2 test datasets into the 6/6/2016 compiled version on my Windows 7 computer. That version doesn't recognize either of those datasets. They both throw a Dataset Loading Error: No dataset handler registered for ... java.lang.IllegalArgumentException: unknown type == 538976288

When I tried doing a custom legend on the CCTM46_P16.baseO2a.36k.O3MAX dataset, O3 (ppmV)[1] parameter, it seemed to work OK. NOTE: After Step 1 I inserted another step:
Change Interval drop-down box to Custom.
![customlegendbreaktileplot_06222016](https://cloud.githubusercontent.com/assets/10145737/16273184/a5cf8882-386e-11e6-86b9-f72a3fd70107.PNG)

**Comment by lizadams** [comment]
I am getting the same error as Jo Ellen when I try to load the GRIDCRO2D_110701file.  Note: the METCRO2D_110515 file was > 400 MB, so it can't be loaded into github easily.  Or at least it causes a large file size issue.  All test datasets need to be checked for their file size before added to git.

![nodatasethandler](https://cloud.githubusercontent.com/assets/1183863/16274473/bc750cd8-3873-11e6-821f-06f98364cf47.png)

**Comment by lizadams** [comment]
using a ncdump command on the files, I am getting the following errors:
ncdump METCRO2D_110515
ncdump: v1hpg.c:190: v1h_get_nc_type: Assertion `type == NC_BYTE || type == NC_CHAR || type == NC_SHORT || type == NC_INT || type == NC_FLOAT || type == NC_DOUBLE' failed.
Abort 
Perhaps there was something wrong with the transfer of the files to scienceftp
ncdump GRIDCRO2D_110701
ncdump: v1hpg.c:190: v1h_get_nc_type: Assertion `type == NC_BYTE || type == NC_CHAR || type == NC_SHORT || type == NC_INT || type == NC_FLOAT || type == NC_DOUBLE' failed.
Abort

**Comment by lizadams** [comment]
Tony: I can't open the files either.  I'm guessing they may have been
transferred in ascii mode initially.  Donna, can you try uploading it
again in binary mode?  Here's a page that shows you how to set it before
you do the transfer:

http://www.templatemonster.com/help/how-to-set-binary-transfer-mode-in-filezilla-totalcommander-and-cuteftp.html#gref

**Comment by lizadams** [comment]
using VERDI_2.0_beta_linux64_20190623.tar.gz
Testing this issue with the SE53BENCH met data files.
./verdi.sh -f /proj/ie/proj/CMAS/CMAQ/*UNC5/*gcc*/data/SE53BENCH/met/mcipv4.5/METCRO2D_160701.nc

Was able to successfully change the numeric values on the color map scale.
<img width="1263" alt="Screen Shot 2019-06-24 at 7 23 01 PM" src="https://user-images.githubusercontent.com/1183863/60058216-8bc98e80-96b5-11e9-94a3-ba5060ff271c.png">
