### ISSUE TITLE
polar stereographic - map rotated 90 degrees

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#92]
Issue Description: In the June 6 build of VERDI, Jo Ellen noticed that the polar stereographic map is rotated by 90 degrees.
Platform: Windows64
VERDI distribution name:1.6.0_alpha 2016-05-11
Filename: GRIDCRO2D_2006075_polar_stereographic.ncf
Variable Name: HT
Plot type: Tile
Plot is rotated 90 degrees from what it should be:
![polar_stereographic_map_rotated](https://cloud.githubusercontent.com/assets/1183863/16277696/1046d770-3882-11e6-8f8d-ffef463f7fb4.png)
The following plot is from the VERDI 1.5 User Manual
https://www.cmascenter.org/verdi/documentation/1.5/VerdiUserManual1.5.htm#_Toc402111297
![polar_stereographic_map_correct](https://cloud.githubusercontent.com/assets/1183863/16277740/3d73429c-3882-11e6-88ae-221db23763fc.png)

Note: The mac version seems to have an issue loading the dataset, the variable is loading as an observational data HT[1](obs), and the tile plot can not be generated

**Comment by systemsgo** [comment]
This is resolved in shapefile_mpas

**Comment by lizadams** [comment]
GIS layer is correctly oriented when displaying the GRIDCRO2D_2006075_polar_stereographic.ncf using the updates in VERDI_1.6.0_shapefile_mpas.  Thanks!
