### ISSUE TITLE
state boundaries don't line up with data for this wrf output file

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#95]
Added an eclipse script: verdi_script_wrf.launch 
It loads the wrf_usgs_tx1km_04112012.nc data file that we distribute with VERDI
The tileplot shows a misalignment between the state boundary and the data.
This misalignment was also present at VERDI_1.6.0_alpha (prior to the merge with shapefile_mpas).
![wrf_usgs_landmask_state_boundaries_incorrectly_aligned](https://cloud.githubusercontent.com/assets/1183863/17142016/7d62b900-531c-11e6-8f68-3637dee3665f.png)

https://github.com/CEMPD/VERDI/commit/8980c5455f849ba833f00f599989d85708c71b66

**Comment by joellenb** [comment]
Replaced state boundaries file to match county boundaries file. Please retest. 
NOTE: These boundaries match each other but do not match the North America boundaries; that dataset is at lower resolution.

**Comment by lizadams** [comment]
This problem is still occurring.  Need to test with another WRF output file.

**Comment by lizadams** [comment]
Retried this after making edits to the WRFConvention.java to specify that Radius of the Earth was 6370, but it didn't have any impact with this new specification in the projection string.
The projection in WRFConvention.java is LambertConformal{earth_radius=6370.0, lat0=40.57356643676758, lon0=-97.0, par1=33.0, par2=45.0, falseEasting=0.0, falseNorthing=0.0}

**Comment by lizadams** [comment]
using VERDI_2.0_beta_linux64_20190623.tar.gz
This is still occurring, but it isn't as glaring an issue as in the past.
using the following script for testing
```
#!/bin/csh -f

#script for testing command line options

echo 'running verdi_script_wrf.csh'
setenv verdi_dir /proj/ie/apps/longleaf/VERDI_2.0_jun_23/VERDI_2.0_beta
cd $verdi_dir

foreach species ( LANDMASK )
./verdi.sh \
         -f $verdi_dir/data/model/wrf_usgs_tx1km_04112012.nc \
         -s "${species}[1]" \
         -g tile \
#          -quit
 end
```
<img width="880" alt="Screen Shot 2019-06-24 at 7 15 02 PM" src="https://user-images.githubusercontent.com/1183863/60057975-8a4b9680-96b4-11e9-88fd-dfb3ef3bdd8e.png">
